/**
 * Vocabulary expansion: generates additional nodes to reach 2,500+
 * by creating systematic character combinations, reading/writing nodes,
 * and additional HSK 4-6 vocabulary.
 */

import type { NodeType } from "../../src/types/graph";
import type { RawNode } from "./stage1-import";

function sanitizeId(prefix: string, hanzi: string): string {
  const hex = [...hanzi].map(c => c.codePointAt(0)!.toString(16)).join("");
  return `${prefix}_${hex}`;
}

const EXTRA_HSK4_WORDS: Array<{ hanzi: string; pinyin: string; meaning: string }> = [
  { hanzi: "普通话", pinyin: "pǔtōnghuà", meaning: "Mandarin (standard Chinese)" },
  { hanzi: "成绩", pinyin: "chéngjì", meaning: "grades/results" },
  { hanzi: "毕业", pinyin: "bìyè", meaning: "to graduate" },
  { hanzi: "职业", pinyin: "zhíyè", meaning: "career/profession" },
  { hanzi: "收入", pinyin: "shōurù", meaning: "income" },
  { hanzi: "消费", pinyin: "xiāofèi", meaning: "to consume/spending" },
  { hanzi: "节日", pinyin: "jiérì", meaning: "holiday/festival" },
  { hanzi: "春节", pinyin: "chūnjié", meaning: "Spring Festival" },
  { hanzi: "中秋节", pinyin: "zhōngqiūjié", meaning: "Mid-Autumn Festival" },
  { hanzi: "元宵节", pinyin: "yuánxiāojié", meaning: "Lantern Festival" },
  { hanzi: "端午节", pinyin: "duānwǔjié", meaning: "Dragon Boat Festival" },
  { hanzi: "感恩", pinyin: "gǎn'ēn", meaning: "gratitude/thanksgiving" },
  { hanzi: "礼物", pinyin: "lǐwù", meaning: "gift/present" },
  { hanzi: "压岁钱", pinyin: "yāsuìqián", meaning: "lucky money (New Year)" },
  { hanzi: "饺子", pinyin: "jiǎozi", meaning: "dumplings" },
  { hanzi: "月饼", pinyin: "yuèbǐng", meaning: "mooncake" },
  { hanzi: "粽子", pinyin: "zòngzi", meaning: "rice dumpling" },
  { hanzi: "筷子", pinyin: "kuàizi", meaning: "chopsticks" },
  { hanzi: "碗", pinyin: "wǎn", meaning: "bowl" },
  { hanzi: "盘子", pinyin: "pánzi", meaning: "plate/dish" },
  { hanzi: "勺子", pinyin: "sháozi", meaning: "spoon" },
  { hanzi: "叉子", pinyin: "chāzi", meaning: "fork" },
  { hanzi: "刀子", pinyin: "dāozi", meaning: "knife" },
  { hanzi: "厨房", pinyin: "chúfáng", meaning: "kitchen" },
  { hanzi: "客厅", pinyin: "kètīng", meaning: "living room" },
  { hanzi: "卧室", pinyin: "wòshì", meaning: "bedroom" },
  { hanzi: "阳台", pinyin: "yángtái", meaning: "balcony" },
  { hanzi: "花园", pinyin: "huāyuán", meaning: "garden" },
  { hanzi: "邻居", pinyin: "línjū", meaning: "neighbor" },
  { hanzi: "社区", pinyin: "shèqū", meaning: "community" },
  { hanzi: "超市", pinyin: "chāoshì", meaning: "supermarket" },
  { hanzi: "银行", pinyin: "yínháng", meaning: "bank" },
  { hanzi: "邮局", pinyin: "yóujú", meaning: "post office" },
  { hanzi: "警察局", pinyin: "jǐngchájú", meaning: "police station" },
  { hanzi: "消防站", pinyin: "xiāofángzhàn", meaning: "fire station" },
  { hanzi: "公园", pinyin: "gōngyuán", meaning: "park" },
  { hanzi: "博物馆", pinyin: "bówùguǎn", meaning: "museum" },
  { hanzi: "体育馆", pinyin: "tǐyùguǎn", meaning: "gymnasium" },
  { hanzi: "电影院", pinyin: "diànyǐngyuàn", meaning: "cinema/movie theater" },
  { hanzi: "动物园", pinyin: "dòngwùyuán", meaning: "zoo" },
  { hanzi: "植物园", pinyin: "zhíwùyuán", meaning: "botanical garden" },
  { hanzi: "游乐园", pinyin: "yóulèyuán", meaning: "amusement park" },
  { hanzi: "机场", pinyin: "jīchǎng", meaning: "airport" },
  { hanzi: "火车", pinyin: "huǒchē", meaning: "train" },
  { hanzi: "地铁", pinyin: "dìtiě", meaning: "subway/metro" },
  { hanzi: "出口", pinyin: "chūkǒu", meaning: "exit" },
  { hanzi: "入口", pinyin: "rùkǒu", meaning: "entrance" },
  { hanzi: "护照", pinyin: "hùzhào", meaning: "passport" },
  { hanzi: "签证", pinyin: "qiānzhèng", meaning: "visa" },
  { hanzi: "行李", pinyin: "xíngli", meaning: "luggage/baggage" },
  { hanzi: "箱子", pinyin: "xiāngzi", meaning: "suitcase/box" },
  { hanzi: "地图", pinyin: "dìtú", meaning: "map" },
  { hanzi: "导游", pinyin: "dǎoyóu", meaning: "tour guide" },
  { hanzi: "景点", pinyin: "jǐngdiǎn", meaning: "scenic spot" },
  { hanzi: "纪念品", pinyin: "jìniànpǐn", meaning: "souvenir" },
  { hanzi: "预订", pinyin: "yùdìng", meaning: "to reserve/book" },
  { hanzi: "宾馆", pinyin: "bīnguǎn", meaning: "hotel/guesthouse" },
  { hanzi: "服务员", pinyin: "fúwùyuán", meaning: "waiter/attendant" },
  { hanzi: "菜单", pinyin: "càidān", meaning: "menu" },
  { hanzi: "发票", pinyin: "fāpiào", meaning: "receipt/invoice" },
  { hanzi: "小费", pinyin: "xiǎofèi", meaning: "tip/gratuity" },
  { hanzi: "味道", pinyin: "wèidao", meaning: "taste/flavor" },
  { hanzi: "辣椒", pinyin: "làjiāo", meaning: "chili pepper" },
  { hanzi: "酱油", pinyin: "jiàngyóu", meaning: "soy sauce" },
  { hanzi: "牛肉", pinyin: "niúròu", meaning: "beef" },
  { hanzi: "猪肉", pinyin: "zhūròu", meaning: "pork" },
  { hanzi: "鸡肉", pinyin: "jīròu", meaning: "chicken (meat)" },
  { hanzi: "鱼肉", pinyin: "yúròu", meaning: "fish (meat)" },
  { hanzi: "蔬菜", pinyin: "shūcài", meaning: "vegetables" },
  { hanzi: "水果", pinyin: "shuǐguǒ", meaning: "fruit" },
  { hanzi: "面包", pinyin: "miànbāo", meaning: "bread" },
  { hanzi: "蛋糕", pinyin: "dàngāo", meaning: "cake" },
  { hanzi: "冰淇淋", pinyin: "bīngqílín", meaning: "ice cream" },
  { hanzi: "咖啡", pinyin: "kāfēi", meaning: "coffee" },
  { hanzi: "果汁", pinyin: "guǒzhī", meaning: "juice" },
  { hanzi: "啤酒", pinyin: "píjiǔ", meaning: "beer" },
  { hanzi: "饮料", pinyin: "yǐnliào", meaning: "beverage/drink" },
  { hanzi: "早餐", pinyin: "zǎocān", meaning: "breakfast" },
  { hanzi: "午餐", pinyin: "wǔcān", meaning: "lunch" },
  { hanzi: "晚餐", pinyin: "wǎncān", meaning: "dinner" },
  { hanzi: "衣服", pinyin: "yīfu", meaning: "clothing/clothes" },
  { hanzi: "裤子", pinyin: "kùzi", meaning: "pants/trousers" },
  { hanzi: "裙子", pinyin: "qúnzi", meaning: "skirt/dress" },
  { hanzi: "鞋子", pinyin: "xiézi", meaning: "shoes" },
  { hanzi: "帽子", pinyin: "màozi", meaning: "hat/cap" },
  { hanzi: "眼镜", pinyin: "yǎnjìng", meaning: "glasses/eyeglasses" },
  { hanzi: "手表", pinyin: "shǒubiǎo", meaning: "wristwatch" },
  { hanzi: "手套", pinyin: "shǒutào", meaning: "gloves" },
  { hanzi: "围巾", pinyin: "wéijīn", meaning: "scarf" },
  { hanzi: "雨伞", pinyin: "yǔsǎn", meaning: "umbrella" },
  { hanzi: "钱包", pinyin: "qiánbāo", meaning: "wallet/purse" },
  { hanzi: "背包", pinyin: "bēibāo", meaning: "backpack" },
  { hanzi: "颜色", pinyin: "yánsè", meaning: "color" },
  { hanzi: "蓝色", pinyin: "lánsè", meaning: "blue" },
  { hanzi: "绿色", pinyin: "lǜsè", meaning: "green" },
  { hanzi: "黄色", pinyin: "huángsè", meaning: "yellow" },
  { hanzi: "红色", pinyin: "hóngsè", meaning: "red" },
  { hanzi: "白色", pinyin: "báisè", meaning: "white" },
  { hanzi: "黑色", pinyin: "hēisè", meaning: "black" },
  { hanzi: "粉色", pinyin: "fěnsè", meaning: "pink" },
  { hanzi: "紫色", pinyin: "zǐsè", meaning: "purple" },
  { hanzi: "数学", pinyin: "shùxué", meaning: "mathematics" },
  { hanzi: "英语", pinyin: "yīngyǔ", meaning: "English" },
  { hanzi: "物理", pinyin: "wùlǐ", meaning: "physics" },
  { hanzi: "化学", pinyin: "huàxué", meaning: "chemistry" },
  { hanzi: "生物", pinyin: "shēngwù", meaning: "biology" },
  { hanzi: "地理", pinyin: "dìlǐ", meaning: "geography" },
  { hanzi: "体育", pinyin: "tǐyù", meaning: "physical education" },
  { hanzi: "美术", pinyin: "měishù", meaning: "fine arts" },
  { hanzi: "音乐课", pinyin: "yīnyuèkè", meaning: "music class" },
  { hanzi: "作业", pinyin: "zuòyè", meaning: "homework" },
  { hanzi: "考试", pinyin: "kǎoshì", meaning: "examination" },
  { hanzi: "成绩单", pinyin: "chéngjìdān", meaning: "report card" },
  { hanzi: "奖学金", pinyin: "jiǎngxuéjīn", meaning: "scholarship" },
  { hanzi: "毕业典礼", pinyin: "bìyè diǎnlǐ", meaning: "graduation ceremony" },
  { hanzi: "校园", pinyin: "xiàoyuán", meaning: "campus" },
  { hanzi: "操场", pinyin: "cāochǎng", meaning: "playground/sports field" },
  { hanzi: "食堂", pinyin: "shítáng", meaning: "cafeteria/dining hall" },
  { hanzi: "宿舍", pinyin: "sùshè", meaning: "dormitory" },
  { hanzi: "实验室", pinyin: "shíyànshì", meaning: "laboratory" },
  { hanzi: "图书", pinyin: "túshū", meaning: "books/publications" },
  { hanzi: "杂志", pinyin: "zázhì", meaning: "magazine" },
  { hanzi: "小说", pinyin: "xiǎoshuō", meaning: "novel/fiction" },
  { hanzi: "诗歌", pinyin: "shīgē", meaning: "poetry" },
  { hanzi: "故事", pinyin: "gùshi", meaning: "story" },
  { hanzi: "新闻", pinyin: "xīnwén", meaning: "news" },
  { hanzi: "广播", pinyin: "guǎngbō", meaning: "broadcast/radio" },
  { hanzi: "节目", pinyin: "jiémù", meaning: "program/show" },
  { hanzi: "广告", pinyin: "guǎnggào", meaning: "advertisement" },
  { hanzi: "网站", pinyin: "wǎngzhàn", meaning: "website" },
  { hanzi: "电子邮件", pinyin: "diànzǐ yóujiàn", meaning: "email" },
  { hanzi: "短信", pinyin: "duǎnxìn", meaning: "text message" },
  { hanzi: "聊天", pinyin: "liáotiān", meaning: "to chat" },
  { hanzi: "搜索", pinyin: "sōusuǒ", meaning: "to search" },
  { hanzi: "下载", pinyin: "xiàzǎi", meaning: "to download" },
  { hanzi: "上传", pinyin: "shàngchuán", meaning: "to upload" },
  { hanzi: "密码", pinyin: "mìmǎ", meaning: "password" },
  { hanzi: "账号", pinyin: "zhànghào", meaning: "account (online)" },
  { hanzi: "软件", pinyin: "ruǎnjiàn", meaning: "software" },
  { hanzi: "硬件", pinyin: "yìngjiàn", meaning: "hardware" },
  { hanzi: "打印", pinyin: "dǎyìn", meaning: "to print" },
  { hanzi: "复印", pinyin: "fùyìn", meaning: "to photocopy" },
  { hanzi: "空调", pinyin: "kōngtiáo", meaning: "air conditioning" },
  { hanzi: "电梯", pinyin: "diàntī", meaning: "elevator/lift" },
  { hanzi: "楼梯", pinyin: "lóutī", meaning: "stairs/staircase" },
  { hanzi: "洗衣机", pinyin: "xǐyījī", meaning: "washing machine" },
  { hanzi: "冰箱", pinyin: "bīngxiāng", meaning: "refrigerator" },
  { hanzi: "微波炉", pinyin: "wēibōlú", meaning: "microwave oven" },
  { hanzi: "锅", pinyin: "guō", meaning: "pot/wok" },
  { hanzi: "春天", pinyin: "chūntiān", meaning: "spring" },
  { hanzi: "夏天", pinyin: "xiàtiān", meaning: "summer" },
  { hanzi: "秋天", pinyin: "qiūtiān", meaning: "autumn/fall" },
  { hanzi: "冬天", pinyin: "dōngtiān", meaning: "winter" },
  { hanzi: "温度", pinyin: "wēndù", meaning: "temperature" },
  { hanzi: "湿度", pinyin: "shīdù", meaning: "humidity" },
  { hanzi: "阴天", pinyin: "yīntiān", meaning: "cloudy/overcast" },
  { hanzi: "晴天", pinyin: "qíngtiān", meaning: "sunny day" },
  { hanzi: "下雨", pinyin: "xiàyǔ", meaning: "to rain" },
  { hanzi: "下雪", pinyin: "xiàxuě", meaning: "to snow" },
  { hanzi: "台风", pinyin: "táifēng", meaning: "typhoon" },
  { hanzi: "地震", pinyin: "dìzhèn", meaning: "earthquake" },
  { hanzi: "洪水", pinyin: "hóngshuǐ", meaning: "flood" },
  { hanzi: "森林", pinyin: "sēnlín", meaning: "forest" },
  { hanzi: "沙漠", pinyin: "shāmò", meaning: "desert" },
  { hanzi: "海洋", pinyin: "hǎiyáng", meaning: "ocean" },
  { hanzi: "湖泊", pinyin: "húpō", meaning: "lake" },
  { hanzi: "岛屿", pinyin: "dǎoyǔ", meaning: "island" },
  { hanzi: "大陆", pinyin: "dàlù", meaning: "continent/mainland" },
  { hanzi: "国家", pinyin: "guójiā", meaning: "country/nation" },
  { hanzi: "首都", pinyin: "shǒudū", meaning: "capital city" },
  { hanzi: "省", pinyin: "shěng", meaning: "province" },
  { hanzi: "城镇", pinyin: "chéngzhèn", meaning: "town" },
  { hanzi: "农村", pinyin: "nóngcūn", meaning: "countryside/rural area" },
  { hanzi: "人口", pinyin: "rénkǒu", meaning: "population" },
  { hanzi: "民族", pinyin: "mínzú", meaning: "ethnic group/nationality" },
  { hanzi: "宗教", pinyin: "zōngjiào", meaning: "religion" },
  { hanzi: "语言", pinyin: "yǔyán", meaning: "language" },
  { hanzi: "方言", pinyin: "fāngyán", meaning: "dialect" },
  { hanzi: "翻译", pinyin: "fānyì", meaning: "to translate/translator" },
  { hanzi: "发音", pinyin: "fāyīn", meaning: "pronunciation" },
  { hanzi: "声调", pinyin: "shēngdiào", meaning: "tone (of Chinese)" },
  { hanzi: "笔画", pinyin: "bǐhuà", meaning: "stroke (of character)" },
  { hanzi: "偏旁", pinyin: "piānpáng", meaning: "radical (of character)" },
  { hanzi: "部首", pinyin: "bùshǒu", meaning: "radical (dictionary)" },
  { hanzi: "词语", pinyin: "cíyǔ", meaning: "word/term" },
  { hanzi: "句子", pinyin: "jùzi", meaning: "sentence" },
  { hanzi: "段落", pinyin: "duànluò", meaning: "paragraph" },
  { hanzi: "文章", pinyin: "wénzhāng", meaning: "article/essay" },
  { hanzi: "作文", pinyin: "zuòwén", meaning: "composition/essay" },
  { hanzi: "日记", pinyin: "rìjì", meaning: "diary/journal" },
  { hanzi: "信封", pinyin: "xìnfēng", meaning: "envelope" },
  { hanzi: "邮票", pinyin: "yóupiào", meaning: "stamp" },
  { hanzi: "地址", pinyin: "dìzhǐ", meaning: "address" },
  { hanzi: "电话号码", pinyin: "diànhuà hàomǎ", meaning: "phone number" },
  { hanzi: "生命", pinyin: "shēngmìng", meaning: "life" },
  { hanzi: "健康", pinyin: "jiànkāng", meaning: "health/healthy" },
  { hanzi: "疾病", pinyin: "jíbìng", meaning: "disease/illness" },
  { hanzi: "感冒", pinyin: "gǎnmào", meaning: "cold (illness)" },
  { hanzi: "发烧", pinyin: "fāshāo", meaning: "to have a fever" },
  { hanzi: "咳嗽", pinyin: "késou", meaning: "to cough" },
  { hanzi: "头痛", pinyin: "tóutòng", meaning: "headache" },
  { hanzi: "牙痛", pinyin: "yátòng", meaning: "toothache" },
  { hanzi: "过敏", pinyin: "guòmǐn", meaning: "allergy/allergic" },
  { hanzi: "维生素", pinyin: "wéishēngsù", meaning: "vitamin" },
  { hanzi: "锻炼", pinyin: "duànliàn", meaning: "to exercise/train" },
  { hanzi: "减肥", pinyin: "jiǎnféi", meaning: "to lose weight" },
  { hanzi: "营养", pinyin: "yíngyǎng", meaning: "nutrition" },
  { hanzi: "睡眠", pinyin: "shuìmián", meaning: "sleep" },
  { hanzi: "压力", pinyin: "yālì", meaning: "pressure/stress" },
  { hanzi: "放松", pinyin: "fàngsōng", meaning: "to relax" },
  { hanzi: "心情", pinyin: "xīnqíng", meaning: "mood/state of mind" },
  { hanzi: "高兴", pinyin: "gāoxìng", meaning: "happy/glad" },
  { hanzi: "难过", pinyin: "nánguò", meaning: "sad/upset" },
  { hanzi: "生气", pinyin: "shēngqì", meaning: "angry" },
  { hanzi: "紧张", pinyin: "jǐnzhāng", meaning: "nervous/tense" },
  { hanzi: "兴奋", pinyin: "xīngfèn", meaning: "excited" },
  { hanzi: "无聊", pinyin: "wúliáo", meaning: "bored/boring" },
  { hanzi: "满意", pinyin: "mǎnyì", meaning: "satisfied" },
  { hanzi: "失望", pinyin: "shīwàng", meaning: "disappointed" },
  { hanzi: "骄傲", pinyin: "jiāo'ào", meaning: "proud" },
  { hanzi: "羡慕", pinyin: "xiànmù", meaning: "to envy/admire" },
  { hanzi: "同情", pinyin: "tóngqíng", meaning: "sympathy" },
  { hanzi: "友谊", pinyin: "yǒuyì", meaning: "friendship" },
  { hanzi: "爱情", pinyin: "àiqíng", meaning: "romantic love" },
  { hanzi: "婚礼", pinyin: "hūnlǐ", meaning: "wedding" },
  { hanzi: "约会", pinyin: "yuēhuì", meaning: "date (romantic)" },
  { hanzi: "离婚", pinyin: "líhūn", meaning: "divorce" },
  { hanzi: "孕妇", pinyin: "yùnfù", meaning: "pregnant woman" },
  { hanzi: "婴儿", pinyin: "yīng'ér", meaning: "baby/infant" },
  { hanzi: "幼儿园", pinyin: "yòu'éryuán", meaning: "kindergarten" },
  { hanzi: "小学", pinyin: "xiǎoxué", meaning: "elementary school" },
  { hanzi: "中学", pinyin: "zhōngxué", meaning: "middle school" },
  { hanzi: "高中", pinyin: "gāozhōng", meaning: "high school" },
  { hanzi: "大学", pinyin: "dàxué", meaning: "university" },
  { hanzi: "硕士", pinyin: "shuòshì", meaning: "master's degree" },
  { hanzi: "博士", pinyin: "bóshì", meaning: "doctorate/Ph.D." },
  { hanzi: "律师", pinyin: "lǜshī", meaning: "lawyer" },
  { hanzi: "工程师", pinyin: "gōngchéngshī", meaning: "engineer" },
  { hanzi: "护士", pinyin: "hùshi", meaning: "nurse" },
  { hanzi: "警察", pinyin: "jǐngchá", meaning: "police officer" },
  { hanzi: "军人", pinyin: "jūnrén", meaning: "military personnel" },
  { hanzi: "记者", pinyin: "jìzhě", meaning: "journalist/reporter" },
  { hanzi: "画家", pinyin: "huàjiā", meaning: "painter/artist" },
  { hanzi: "作家", pinyin: "zuòjiā", meaning: "writer/author" },
  { hanzi: "歌手", pinyin: "gēshǒu", meaning: "singer" },
  { hanzi: "演员", pinyin: "yǎnyuán", meaning: "actor/actress" },
  { hanzi: "导演", pinyin: "dǎoyǎn", meaning: "director (film)" },
  { hanzi: "运动员", pinyin: "yùndòngyuán", meaning: "athlete" },
  { hanzi: "教练", pinyin: "jiàoliàn", meaning: "coach/trainer" },
  { hanzi: "厨师", pinyin: "chúshī", meaning: "chef/cook" },
  { hanzi: "司机", pinyin: "sījī", meaning: "driver" },
  { hanzi: "农民", pinyin: "nóngmín", meaning: "farmer" },
  { hanzi: "商人", pinyin: "shāngrén", meaning: "businessperson" },
  { hanzi: "志愿者", pinyin: "zhìyuànzhě", meaning: "volunteer" },
  { hanzi: "民主", pinyin: "mínzhǔ", meaning: "democracy" },
  { hanzi: "自由", pinyin: "zìyóu", meaning: "freedom/liberty" },
  { hanzi: "平等", pinyin: "píngděng", meaning: "equality" },
  { hanzi: "权利", pinyin: "quánlì", meaning: "rights" },
  { hanzi: "义务", pinyin: "yìwù", meaning: "duty/obligation" },
  { hanzi: "法律", pinyin: "fǎlǜ", meaning: "law" },
  { hanzi: "规则", pinyin: "guīzé", meaning: "rule" },
  { hanzi: "合同", pinyin: "hétong", meaning: "contract" },
  { hanzi: "保险", pinyin: "bǎoxiǎn", meaning: "insurance" },
  { hanzi: "税收", pinyin: "shuìshōu", meaning: "taxation" },
  { hanzi: "投资", pinyin: "tóuzī", meaning: "investment" },
  { hanzi: "贸易", pinyin: "màoyì", meaning: "trade/commerce" },
  { hanzi: "进口", pinyin: "jìnkǒu", meaning: "import" },
  { hanzi: "出口", pinyin: "chūkǒu", meaning: "export" },
  { hanzi: "市场", pinyin: "shìchǎng", meaning: "market" },
  { hanzi: "品牌", pinyin: "pǐnpái", meaning: "brand" },
  { hanzi: "广告", pinyin: "guǎnggào", meaning: "advertisement" },
  { hanzi: "消费者", pinyin: "xiāofèizhě", meaning: "consumer" },
  { hanzi: "顾客", pinyin: "gùkè", meaning: "customer" },
  { hanzi: "服务", pinyin: "fúwù", meaning: "service" },
  { hanzi: "满意度", pinyin: "mǎnyìdù", meaning: "satisfaction level" },
  { hanzi: "投诉", pinyin: "tóusù", meaning: "complaint" },
  { hanzi: "退货", pinyin: "tuìhuò", meaning: "return goods" },
  { hanzi: "换货", pinyin: "huànhuò", meaning: "exchange goods" },
  { hanzi: "打折", pinyin: "dǎzhé", meaning: "discount" },
  { hanzi: "优惠", pinyin: "yōuhuì", meaning: "special offer" },
  { hanzi: "会员", pinyin: "huìyuán", meaning: "member" },
  { hanzi: "积分", pinyin: "jīfēn", meaning: "points (reward)" },
  { hanzi: "快递", pinyin: "kuàidì", meaning: "express delivery" },
  { hanzi: "包裹", pinyin: "bāoguǒ", meaning: "package/parcel" },
  { hanzi: "收件人", pinyin: "shōujiànrén", meaning: "recipient" },
  { hanzi: "发件人", pinyin: "fājiànrén", meaning: "sender" },
  { hanzi: "跑步", pinyin: "pǎobù", meaning: "to jog/run" },
  { hanzi: "瑜伽", pinyin: "yújiā", meaning: "yoga" },
  { hanzi: "太极拳", pinyin: "tàijíquán", meaning: "tai chi" },
  { hanzi: "武术", pinyin: "wǔshù", meaning: "martial arts" },
  { hanzi: "网球", pinyin: "wǎngqiú", meaning: "tennis" },
  { hanzi: "乒乓球", pinyin: "pīngpāngqiú", meaning: "table tennis" },
  { hanzi: "羽毛球", pinyin: "yǔmáoqiú", meaning: "badminton" },
  { hanzi: "排球", pinyin: "páiqiú", meaning: "volleyball" },
  { hanzi: "高尔夫", pinyin: "gāo'ěrfū", meaning: "golf" },
  { hanzi: "滑雪", pinyin: "huáxuě", meaning: "to ski/skiing" },
  { hanzi: "滑冰", pinyin: "huábīng", meaning: "to ice skate" },
  { hanzi: "登山", pinyin: "dēngshān", meaning: "to climb mountains" },
  { hanzi: "钓鱼", pinyin: "diàoyú", meaning: "to fish" },
  { hanzi: "摄影", pinyin: "shèyǐng", meaning: "photography" },
  { hanzi: "书法", pinyin: "shūfǎ", meaning: "calligraphy" },
  { hanzi: "绘画", pinyin: "huìhuà", meaning: "painting/drawing" },
  { hanzi: "陶艺", pinyin: "táoyì", meaning: "pottery/ceramics" },
  { hanzi: "园艺", pinyin: "yuányì", meaning: "gardening" },
  { hanzi: "烹饪", pinyin: "pēngrèn", meaning: "cooking/culinary arts" },
  { hanzi: "下棋", pinyin: "xiàqí", meaning: "to play chess" },
  { hanzi: "象棋", pinyin: "xiàngqí", meaning: "Chinese chess" },
  { hanzi: "围棋", pinyin: "wéiqí", meaning: "Go (board game)" },
  { hanzi: "京剧", pinyin: "jīngjù", meaning: "Peking opera" },
  { hanzi: "相声", pinyin: "xiàngsheng", meaning: "cross-talk comedy" },
  { hanzi: "电视剧", pinyin: "diànshìjù", meaning: "TV drama" },
  { hanzi: "纪录片", pinyin: "jìlùpiàn", meaning: "documentary" },
  { hanzi: "动画片", pinyin: "dònghuàpiàn", meaning: "cartoon/animation" },
  { hanzi: "科幻", pinyin: "kēhuàn", meaning: "science fiction" },
  { hanzi: "喜剧", pinyin: "xǐjù", meaning: "comedy" },
  { hanzi: "悲剧", pinyin: "bēijù", meaning: "tragedy" },
  { hanzi: "长城", pinyin: "Chángchéng", meaning: "Great Wall" },
  { hanzi: "故宫", pinyin: "Gùgōng", meaning: "Forbidden City" },
  { hanzi: "天安门", pinyin: "Tiān'ānmén", meaning: "Tiananmen" },
  { hanzi: "黄河", pinyin: "Huánghé", meaning: "Yellow River" },
  { hanzi: "长江", pinyin: "Chángjiāng", meaning: "Yangtze River" },
  { hanzi: "泰山", pinyin: "Tàishān", meaning: "Mount Tai" },
  { hanzi: "兵马俑", pinyin: "bīngmǎyǒng", meaning: "Terracotta Warriors" },
  { hanzi: "丝绸之路", pinyin: "Sīchóu zhī Lù", meaning: "Silk Road" },
  { hanzi: "四大发明", pinyin: "sì dà fāmíng", meaning: "Four Great Inventions" },
  { hanzi: "孔子", pinyin: "Kǒngzǐ", meaning: "Confucius" },
  { hanzi: "熊猫", pinyin: "xióngmāo", meaning: "panda" },
  { hanzi: "龙", pinyin: "lóng", meaning: "dragon" },
  { hanzi: "凤凰", pinyin: "fènghuáng", meaning: "phoenix" },
  { hanzi: "功夫", pinyin: "gōngfu", meaning: "kung fu" },
  { hanzi: "太极", pinyin: "tàijí", meaning: "tai chi" },
  { hanzi: "中医", pinyin: "zhōngyī", meaning: "Chinese medicine" },
  { hanzi: "针灸", pinyin: "zhēnjiǔ", meaning: "acupuncture" },
  { hanzi: "气功", pinyin: "qìgōng", meaning: "qigong" },
  { hanzi: "风水", pinyin: "fēngshuǐ", meaning: "feng shui" },
  { hanzi: "阴阳", pinyin: "yīnyáng", meaning: "yin and yang" },
  { hanzi: "成语", pinyin: "chéngyǔ", meaning: "idiom (4-character)" },
  { hanzi: "谚语", pinyin: "yànyǔ", meaning: "proverb" },
  { hanzi: "歇后语", pinyin: "xiēhòuyǔ", meaning: "riddle-like saying" },
  { hanzi: "绕口令", pinyin: "ràokǒulìng", meaning: "tongue twister" },
];

const EXTRA_HSK56_CHARS: Array<{ hanzi: string; pinyin: string; meaning: string; hsk: number }> = [
  { hanzi: "领", pinyin: "lǐng", meaning: "to lead/collar", hsk: 5 },
  { hanzi: "导", pinyin: "dǎo", meaning: "to guide/direct", hsk: 5 },
  { hanzi: "创", pinyin: "chuàng", meaning: "to create/initiate", hsk: 5 },
  { hanzi: "造", pinyin: "zào", meaning: "to make/build", hsk: 5 },
  { hanzi: "破", pinyin: "pò", meaning: "to break/broken", hsk: 5 },
  { hanzi: "坏", pinyin: "huài", meaning: "bad/broken", hsk: 5 },
  { hanzi: "修", pinyin: "xiū", meaning: "to repair/study", hsk: 5 },
  { hanzi: "复", pinyin: "fù", meaning: "to repeat/recover", hsk: 5 },
  { hanzi: "杂", pinyin: "zá", meaning: "mixed/miscellaneous", hsk: 5 },
  { hanzi: "纯", pinyin: "chún", meaning: "pure/simple", hsk: 5 },
  { hanzi: "精", pinyin: "jīng", meaning: "essence/fine", hsk: 5 },
  { hanzi: "粗", pinyin: "cū", meaning: "rough/thick", hsk: 5 },
  { hanzi: "细", pinyin: "xì", meaning: "thin/fine/careful", hsk: 5 },
  { hanzi: "深", pinyin: "shēn", meaning: "deep/profound", hsk: 5 },
  { hanzi: "浅", pinyin: "qiǎn", meaning: "shallow/light", hsk: 5 },
  { hanzi: "宽", pinyin: "kuān", meaning: "wide/broad", hsk: 5 },
  { hanzi: "窄", pinyin: "zhǎi", meaning: "narrow", hsk: 5 },
  { hanzi: "厚", pinyin: "hòu", meaning: "thick/generous", hsk: 5 },
  { hanzi: "薄", pinyin: "báo", meaning: "thin/slight", hsk: 5 },
  { hanzi: "软", pinyin: "ruǎn", meaning: "soft/flexible", hsk: 5 },
  { hanzi: "硬", pinyin: "yìng", meaning: "hard/stiff", hsk: 5 },
  { hanzi: "松", pinyin: "sōng", meaning: "loose/pine tree", hsk: 5 },
  { hanzi: "紧", pinyin: "jǐn", meaning: "tight/urgent", hsk: 5 },
  { hanzi: "湿", pinyin: "shī", meaning: "wet/damp", hsk: 5 },
  { hanzi: "枯", pinyin: "kū", meaning: "withered/dried", hsk: 5 },
  { hanzi: "鲜", pinyin: "xiān", meaning: "fresh/delicious", hsk: 5 },
  { hanzi: "甜", pinyin: "tián", meaning: "sweet", hsk: 5 },
  { hanzi: "苦", pinyin: "kǔ", meaning: "bitter/suffering", hsk: 5 },
  { hanzi: "酸", pinyin: "suān", meaning: "sour/acid", hsk: 5 },
  { hanzi: "辣", pinyin: "là", meaning: "spicy/hot", hsk: 5 },
  { hanzi: "咸", pinyin: "xián", meaning: "salty", hsk: 5 },
  { hanzi: "淡", pinyin: "dàn", meaning: "bland/light", hsk: 5 },
  { hanzi: "香", pinyin: "xiāng", meaning: "fragrant/delicious", hsk: 5 },
  { hanzi: "臭", pinyin: "chòu", meaning: "smelly/stinky", hsk: 5 },
  { hanzi: "暖", pinyin: "nuǎn", meaning: "warm", hsk: 5 },
  { hanzi: "凉", pinyin: "liáng", meaning: "cool/cold", hsk: 5 },
  { hanzi: "亮", pinyin: "liàng", meaning: "bright/light", hsk: 5 },
  { hanzi: "暗", pinyin: "àn", meaning: "dark/dim", hsk: 5 },
  { hanzi: "空", pinyin: "kōng", meaning: "empty/sky", hsk: 5 },
  { hanzi: "满", pinyin: "mǎn", meaning: "full/satisfied", hsk: 5 },
  { hanzi: "活", pinyin: "huó", meaning: "to live/alive", hsk: 5 },
  { hanzi: "死", pinyin: "sǐ", meaning: "to die/dead", hsk: 5 },
  { hanzi: "胖", pinyin: "pàng", meaning: "fat/plump", hsk: 5 },
  { hanzi: "瘦", pinyin: "shòu", meaning: "thin/skinny", hsk: 5 },
  { hanzi: "聪", pinyin: "cōng", meaning: "intelligent/clever", hsk: 5 },
  { hanzi: "笨", pinyin: "bèn", meaning: "stupid/clumsy", hsk: 5 },
  { hanzi: "勤", pinyin: "qín", meaning: "diligent/frequent", hsk: 5 },
  { hanzi: "懒", pinyin: "lǎn", meaning: "lazy", hsk: 5 },
  { hanzi: "富", pinyin: "fù", meaning: "rich/wealthy", hsk: 5 },
  { hanzi: "穷", pinyin: "qióng", meaning: "poor/poverty", hsk: 5 },
  { hanzi: "忙", pinyin: "máng", meaning: "busy", hsk: 5 },
  { hanzi: "闲", pinyin: "xián", meaning: "idle/free", hsk: 5 },
  { hanzi: "急", pinyin: "jí", meaning: "urgent/anxious", hsk: 5 },
  { hanzi: "慌", pinyin: "huāng", meaning: "flustered/panic", hsk: 5 },
  { hanzi: "稳", pinyin: "wěn", meaning: "stable/steady", hsk: 5 },
  { hanzi: "乱", pinyin: "luàn", meaning: "messy/chaotic", hsk: 5 },
  { hanzi: "整", pinyin: "zhěng", meaning: "whole/tidy", hsk: 5 },
  { hanzi: "齐", pinyin: "qí", meaning: "neat/even", hsk: 5 },
  { hanzi: "美", pinyin: "měi", meaning: "beautiful/America", hsk: 5 },
  { hanzi: "丑", pinyin: "chǒu", meaning: "ugly", hsk: 5 },
  { hanzi: "奇", pinyin: "qí", meaning: "strange/wonderful", hsk: 5 },
  { hanzi: "怪", pinyin: "guài", meaning: "strange/blame", hsk: 5 },
  { hanzi: "妙", pinyin: "miào", meaning: "wonderful/clever", hsk: 5 },
  { hanzi: "巧", pinyin: "qiǎo", meaning: "clever/skillful", hsk: 5 },
  { hanzi: "灵", pinyin: "líng", meaning: "spirit/clever", hsk: 6 },
  { hanzi: "聊", pinyin: "liáo", meaning: "to chat", hsk: 5 },
  { hanzi: "抱", pinyin: "bào", meaning: "to hold/hug", hsk: 5 },
  { hanzi: "推", pinyin: "tuī", meaning: "to push", hsk: 5 },
  { hanzi: "拉", pinyin: "lā", meaning: "to pull", hsk: 5 },
  { hanzi: "扔", pinyin: "rēng", meaning: "to throw", hsk: 5 },
  { hanzi: "捡", pinyin: "jiǎn", meaning: "to pick up", hsk: 5 },
  { hanzi: "挂", pinyin: "guà", meaning: "to hang", hsk: 5 },
  { hanzi: "摸", pinyin: "mō", meaning: "to touch/feel", hsk: 5 },
  { hanzi: "擦", pinyin: "cā", meaning: "to wipe/rub", hsk: 5 },
  { hanzi: "按", pinyin: "àn", meaning: "to press/according to", hsk: 5 },
  { hanzi: "弯", pinyin: "wān", meaning: "to bend/curved", hsk: 5 },
  { hanzi: "倒", pinyin: "dào", meaning: "to pour/fall", hsk: 5 },
  { hanzi: "翻", pinyin: "fān", meaning: "to turn over/flip", hsk: 5 },
  { hanzi: "摇", pinyin: "yáo", meaning: "to shake/wave", hsk: 5 },
  { hanzi: "躺", pinyin: "tǎng", meaning: "to lie down", hsk: 5 },
  { hanzi: "蹲", pinyin: "dūn", meaning: "to squat", hsk: 5 },
  { hanzi: "爬", pinyin: "pá", meaning: "to climb/crawl", hsk: 5 },
  { hanzi: "追", pinyin: "zhuī", meaning: "to chase/pursue", hsk: 5 },
  { hanzi: "逃", pinyin: "táo", meaning: "to escape/flee", hsk: 5 },
  { hanzi: "藏", pinyin: "cáng", meaning: "to hide/store", hsk: 5 },
  { hanzi: "猜", pinyin: "cāi", meaning: "to guess", hsk: 5 },
  { hanzi: "骗", pinyin: "piàn", meaning: "to deceive/cheat", hsk: 5 },
  { hanzi: "偷", pinyin: "tōu", meaning: "to steal", hsk: 5 },
  { hanzi: "救", pinyin: "jiù", meaning: "to save/rescue", hsk: 5 },
  { hanzi: "保", pinyin: "bǎo", meaning: "to protect/keep", hsk: 5 },
  { hanzi: "护", pinyin: "hù", meaning: "to protect/guard", hsk: 5 },
  { hanzi: "防", pinyin: "fáng", meaning: "to prevent/defend", hsk: 5 },
  { hanzi: "挡", pinyin: "dǎng", meaning: "to block/shield", hsk: 5 },
  { hanzi: "避", pinyin: "bì", meaning: "to avoid/escape", hsk: 6 },
  { hanzi: "份", pinyin: "fèn", meaning: "portion/share", hsk: 5 },
  { hanzi: "堆", pinyin: "duī", meaning: "pile/heap", hsk: 5 },
  { hanzi: "批", pinyin: "pī", meaning: "batch/criticize", hsk: 5 },
  { hanzi: "套", pinyin: "tào", meaning: "set/suite", hsk: 5 },
  { hanzi: "双", pinyin: "shuāng", meaning: "pair/double", hsk: 5 },
];

export function expandVocabulary(existingNodes: RawNode[]): RawNode[] {
  const expanded: RawNode[] = [...existingNodes];
  const seenIds = new Set(existingNodes.map(n => n.id));

  function addNode(node: RawNode) {
    if (seenIds.has(node.id)) return;
    seenIds.add(node.id);
    expanded.push(node);
  }

  // Add extra HSK 5-6 characters
  for (const c of EXTRA_HSK56_CHARS) {
    const id = sanitizeId("c", c.hanzi);
    addNode({
      id,
      type: "character",
      hanzi: c.hanzi,
      pinyin: c.pinyin,
      meaning: c.meaning,
      hskLevel: c.hsk,
    });
  }

  // Add extra words
  for (const w of EXTRA_HSK4_WORDS) {
    const id = sanitizeId("w", w.hanzi);
    addNode({
      id,
      type: "word",
      hanzi: w.hanzi,
      pinyin: w.pinyin,
      meaning: w.meaning,
      hskLevel: 4,
    });
  }

  // Generate reading comprehension nodes from existing words
  const readingTopics = [
    { title: "自我介绍", pinyin: "zìwǒ jièshào", meaning: "Self-introduction passage", level: 1 },
    { title: "我的家", pinyin: "wǒ de jiā", meaning: "My family passage", level: 1 },
    { title: "在学校", pinyin: "zài xuéxiào", meaning: "At school passage", level: 1 },
    { title: "去商店", pinyin: "qù shāngdiàn", meaning: "Going shopping passage", level: 1 },
    { title: "看医生", pinyin: "kàn yīshēng", meaning: "Seeing a doctor passage", level: 2 },
    { title: "坐公车", pinyin: "zuò gōngchē", meaning: "Taking the bus passage", level: 2 },
    { title: "过生日", pinyin: "guò shēngrì", meaning: "Birthday celebration passage", level: 2 },
    { title: "运动会", pinyin: "yùndònghuì", meaning: "Sports day passage", level: 2 },
    { title: "旅游经历", pinyin: "lǚyóu jīnglì", meaning: "Travel experience passage", level: 3 },
    { title: "环境保护", pinyin: "huánjìng bǎohù", meaning: "Environmental protection passage", level: 3 },
    { title: "中国文化", pinyin: "zhōngguó wénhuà", meaning: "Chinese culture passage", level: 3 },
    { title: "科技发展", pinyin: "kējì fāzhǎn", meaning: "Technology development passage", level: 4 },
    { title: "城市生活", pinyin: "chéngshì shēnghuó", meaning: "City life passage", level: 3 },
    { title: "农村生活", pinyin: "nóngcūn shēnghuó", meaning: "Rural life passage", level: 4 },
    { title: "中国美食", pinyin: "zhōngguó měishí", meaning: "Chinese cuisine passage", level: 3 },
    { title: "传统节日", pinyin: "chuántǒng jiérì", meaning: "Traditional festivals passage", level: 3 },
    { title: "交通工具", pinyin: "jiāotōng gōngjù", meaning: "Transportation passage", level: 2 },
    { title: "天气预报", pinyin: "tiānqì yùbào", meaning: "Weather forecast passage", level: 2 },
    { title: "学习方法", pinyin: "xuéxí fāngfǎ", meaning: "Study methods passage", level: 3 },
    { title: "未来计划", pinyin: "wèilái jìhuà", meaning: "Future plans passage", level: 3 },
    { title: "健康饮食", pinyin: "jiànkāng yǐnshí", meaning: "Healthy eating passage", level: 4 },
    { title: "网络安全", pinyin: "wǎngluò ānquán", meaning: "Internet safety passage", level: 5 },
    { title: "教育改革", pinyin: "jiàoyù gǎigé", meaning: "Education reform passage", level: 5 },
    { title: "国际关系", pinyin: "guójì guānxì", meaning: "International relations passage", level: 5 },
    { title: "艺术欣赏", pinyin: "yìshù xīnshǎng", meaning: "Art appreciation passage", level: 4 },
  ];

  for (const rt of readingTopics) {
    addNode({
      id: sanitizeId("rd", rt.title),
      type: "reading" as NodeType,
      hanzi: rt.title,
      pinyin: rt.pinyin,
      meaning: rt.meaning,
      hskLevel: rt.level,
    });
  }

  // Generate writing practice nodes
  const writingTopics = [
    { title: "写信:给朋友", pinyin: "xiě xìn: gěi péngyou", meaning: "Writing: letter to a friend", level: 2 },
    { title: "写信:给老师", pinyin: "xiě xìn: gěi lǎoshī", meaning: "Writing: letter to a teacher", level: 2 },
    { title: "写日记", pinyin: "xiě rìjì", meaning: "Writing: diary entry", level: 2 },
    { title: "自我介绍写作", pinyin: "zìwǒ jièshào xiězuò", meaning: "Writing: self-introduction", level: 1 },
    { title: "描写家庭", pinyin: "miáoxiě jiātíng", meaning: "Writing: describe your family", level: 2 },
    { title: "描写学校", pinyin: "miáoxiě xuéxiào", meaning: "Writing: describe your school", level: 2 },
    { title: "描写城市", pinyin: "miáoxiě chéngshì", meaning: "Writing: describe a city", level: 3 },
    { title: "写故事", pinyin: "xiě gùshi", meaning: "Writing: write a short story", level: 3 },
    { title: "议论文:教育", pinyin: "yìlùnwén: jiàoyù", meaning: "Writing: argumentative essay on education", level: 4 },
    { title: "议论文:科技", pinyin: "yìlùnwén: kējì", meaning: "Writing: argumentative essay on technology", level: 4 },
    { title: "申请信", pinyin: "shēnqǐng xìn", meaning: "Writing: application letter", level: 4 },
    { title: "投诉信", pinyin: "tóusù xìn", meaning: "Writing: complaint letter", level: 4 },
    { title: "邀请函", pinyin: "yāoqǐng hán", meaning: "Writing: invitation letter", level: 3 },
    { title: "感谢信", pinyin: "gǎnxiè xìn", meaning: "Writing: thank-you letter", level: 3 },
    { title: "演讲稿", pinyin: "yǎnjiǎng gǎo", meaning: "Writing: speech draft", level: 5 },
    { title: "读后感", pinyin: "dú hòu gǎn", meaning: "Writing: book report", level: 4 },
    { title: "新闻报道", pinyin: "xīnwén bàodào", meaning: "Writing: news report", level: 5 },
    { title: "广告文案", pinyin: "guǎnggào wén'àn", meaning: "Writing: advertisement copy", level: 5 },
    { title: "旅行攻略", pinyin: "lǚxíng gōnglüè", meaning: "Writing: travel guide", level: 3 },
    { title: "菜谱写作", pinyin: "càipǔ xiězuò", meaning: "Writing: recipe", level: 3 },
  ];

  for (const wt of writingTopics) {
    addNode({
      id: sanitizeId("wr", wt.title),
      type: "writing" as NodeType,
      hanzi: wt.title,
      pinyin: wt.pinyin,
      meaning: wt.meaning,
      hskLevel: wt.level,
    });
  }

  // Generate additional grammar patterns
  const extraGrammar = [
    { id: "g_de_result", pattern: "Verb+得+Result", pinyin: "verb + de + result", meaning: "Result complement pattern", hsk: 3 },
    { id: "g_dao_result", pattern: "Verb+到+Object", pinyin: "verb + dào + object", meaning: "Successfully completed action", hsk: 3 },
    { id: "g_zhu_result", pattern: "Verb+住", pinyin: "verb + zhù", meaning: "Action held firmly", hsk: 3 },
    { id: "g_wan_complete", pattern: "Verb+完", pinyin: "verb + wán", meaning: "Completed to the end", hsk: 3 },
    { id: "g_lai_direction", pattern: "Verb+来", pinyin: "verb + lái", meaning: "Directional toward speaker", hsk: 2 },
    { id: "g_qu_direction", pattern: "Verb+去", pinyin: "verb + qù", meaning: "Directional away from speaker", hsk: 2 },
    { id: "g_zai_progressive", pattern: "在+Verb", pinyin: "zài + verb", meaning: "Currently doing (progressive)", hsk: 2 },
    { id: "g_yao_future", pattern: "要+Verb", pinyin: "yào + verb", meaning: "About to / going to", hsk: 2 },
    { id: "g_gang_just", pattern: "刚+Verb", pinyin: "gāng + verb", meaning: "Just did something", hsk: 3 },
    { id: "g_yijing_already", pattern: "已经+Verb+了", pinyin: "yǐjīng + verb + le", meaning: "Already completed", hsk: 3 },
    { id: "g_hai_still", pattern: "还+Verb", pinyin: "hái + verb", meaning: "Still doing / also", hsk: 2 },
    { id: "g_jiu_then", pattern: "就+Verb", pinyin: "jiù + verb", meaning: "Then / right away", hsk: 3 },
    { id: "g_cai_only_then", pattern: "才+Verb", pinyin: "cái + verb", meaning: "Only then / not until", hsk: 3 },
    { id: "g_dou_all", pattern: "都+Verb", pinyin: "dōu + verb", meaning: "All / both", hsk: 1 },
    { id: "g_you_again", pattern: "又+Verb", pinyin: "yòu + verb", meaning: "Again (past)", hsk: 3 },
    { id: "g_zai_again_future", pattern: "再+Verb", pinyin: "zài + verb", meaning: "Again (future)", hsk: 2 },
    { id: "g_yidianr", pattern: "Adj+一点儿", pinyin: "adj + yīdiǎnr", meaning: "A little bit + adj", hsk: 2 },
    { id: "g_duole", pattern: "Adj+多了", pinyin: "adj + duō le", meaning: "Much more + adj", hsk: 3 },
    { id: "g_yue_yue", pattern: "越...越...", pinyin: "yuè...yuè...", meaning: "The more...the more...", hsk: 3 },
    { id: "g_shi_de_emphasis", pattern: "是...的", pinyin: "shì...de", meaning: "Emphasis on time/place/manner", hsk: 3 },
    { id: "g_rang_causative", pattern: "让+Sb+Verb", pinyin: "ràng + sb + verb", meaning: "To let/make someone do", hsk: 3 },
    { id: "g_jiao_causative", pattern: "叫+Sb+Verb", pinyin: "jiào + sb + verb", meaning: "To tell/make someone do", hsk: 3 },
    { id: "g_gen_with", pattern: "跟+Sb+Verb", pinyin: "gēn + sb + verb", meaning: "With someone do", hsk: 2 },
    { id: "g_dui_toward", pattern: "对+Sb+Verb", pinyin: "duì + sb + verb", meaning: "Toward someone do", hsk: 3 },
    { id: "g_gei_for", pattern: "给+Sb+Verb", pinyin: "gěi + sb + verb", meaning: "For someone do", hsk: 2 },
    { id: "g_you_some", pattern: "有的...有的...", pinyin: "yǒude...yǒude...", meaning: "Some...some...", hsk: 3 },
    { id: "g_meiyou_comparison", pattern: "没有+A+Adj", pinyin: "méiyǒu + A + adj", meaning: "Not as...as...", hsk: 3 },
    { id: "g_kuai_about_to", pattern: "快要...了", pinyin: "kuài yào...le", meaning: "About to / soon", hsk: 3 },
    { id: "g_zheng_in_process", pattern: "正在+Verb", pinyin: "zhèng zài + verb", meaning: "Right in the middle of", hsk: 2 },
    { id: "g_conglai_never", pattern: "从来不/没+Verb", pinyin: "cónglái bù/méi + verb", meaning: "Never have/do", hsk: 4 },
  ];

  for (const g of extraGrammar) {
    addNode({
      id: g.id,
      type: "grammar",
      hanzi: g.pattern,
      pinyin: g.pinyin,
      meaning: g.meaning,
      hskLevel: g.hsk,
    });
  }

  // Large additional HSK5-6 word batch to reach 2,500+
  const moreWords: Array<{ hanzi: string; pinyin: string; meaning: string; hsk: number }> = [
    { hanzi: "实际", pinyin: "shíjì", meaning: "actual/practical", hsk: 5 },
    { hanzi: "具体", pinyin: "jùtǐ", meaning: "specific/concrete", hsk: 5 },
    { hanzi: "抽象", pinyin: "chōuxiàng", meaning: "abstract", hsk: 6 },
    { hanzi: "复杂", pinyin: "fùzá", meaning: "complicated/complex", hsk: 5 },
    { hanzi: "简单", pinyin: "jiǎndān", meaning: "simple/easy", hsk: 3 },
    { hanzi: "丰富", pinyin: "fēngfù", meaning: "rich/abundant", hsk: 5 },
    { hanzi: "贫穷", pinyin: "pínqióng", meaning: "poverty/poor", hsk: 6 },
    { hanzi: "平衡", pinyin: "pínghéng", meaning: "balance/equilibrium", hsk: 5 },
    { hanzi: "稳定", pinyin: "wěndìng", meaning: "stable/steady", hsk: 5 },
    { hanzi: "混乱", pinyin: "hùnluàn", meaning: "chaos/confusion", hsk: 6 },
    { hanzi: "秩序", pinyin: "zhìxù", meaning: "order/sequence", hsk: 6 },
    { hanzi: "规律", pinyin: "guīlǜ", meaning: "pattern/law", hsk: 5 },
    { hanzi: "现象", pinyin: "xiànxiàng", meaning: "phenomenon", hsk: 5 },
    { hanzi: "本质", pinyin: "běnzhì", meaning: "essence/nature", hsk: 6 },
    { hanzi: "特征", pinyin: "tèzhēng", meaning: "characteristic/feature", hsk: 5 },
    { hanzi: "区别", pinyin: "qūbié", meaning: "difference/distinction", hsk: 5 },
    { hanzi: "联系", pinyin: "liánxì", meaning: "connection/contact", hsk: 4 },
    { hanzi: "矛盾", pinyin: "máodùn", meaning: "contradiction/conflict", hsk: 6 },
    { hanzi: "和谐", pinyin: "héxié", meaning: "harmony/harmonious", hsk: 6 },
    { hanzi: "冲突", pinyin: "chōngtū", meaning: "conflict/clash", hsk: 6 },
    { hanzi: "妥协", pinyin: "tuǒxié", meaning: "compromise", hsk: 6 },
    { hanzi: "协商", pinyin: "xiéshāng", meaning: "to negotiate", hsk: 6 },
    { hanzi: "谈判", pinyin: "tánpàn", meaning: "negotiation", hsk: 6 },
    { hanzi: "讨价还价", pinyin: "tǎojià huánjià", meaning: "to bargain", hsk: 5 },
    { hanzi: "主动", pinyin: "zhǔdòng", meaning: "initiative/active", hsk: 5 },
    { hanzi: "被动", pinyin: "bèidòng", meaning: "passive", hsk: 5 },
    { hanzi: "积极", pinyin: "jījí", meaning: "positive/active", hsk: 5 },
    { hanzi: "消极", pinyin: "xiāojí", meaning: "negative/passive", hsk: 5 },
    { hanzi: "乐观", pinyin: "lèguān", meaning: "optimistic", hsk: 5 },
    { hanzi: "悲观", pinyin: "bēiguān", meaning: "pessimistic", hsk: 5 },
    { hanzi: "独立", pinyin: "dúlì", meaning: "independent", hsk: 5 },
    { hanzi: "依赖", pinyin: "yīlài", meaning: "to depend on", hsk: 6 },
    { hanzi: "负责", pinyin: "fùzé", meaning: "responsible", hsk: 5 },
    { hanzi: "敬佩", pinyin: "jìngpèi", meaning: "to admire/respect", hsk: 6 },
    { hanzi: "崇拜", pinyin: "chóngbài", meaning: "to worship/admire", hsk: 6 },
    { hanzi: "鼓励", pinyin: "gǔlì", meaning: "to encourage", hsk: 5 },
    { hanzi: "批评", pinyin: "pīpíng", meaning: "to criticize", hsk: 5 },
    { hanzi: "表扬", pinyin: "biǎoyáng", meaning: "to praise", hsk: 5 },
    { hanzi: "赞美", pinyin: "zànměi", meaning: "to praise/admire", hsk: 6 },
    { hanzi: "安慰", pinyin: "ānwèi", meaning: "to comfort/console", hsk: 5 },
    { hanzi: "道歉", pinyin: "dàoqiàn", meaning: "to apologize", hsk: 5 },
    { hanzi: "原谅", pinyin: "yuánliàng", meaning: "to forgive", hsk: 5 },
    { hanzi: "后悔", pinyin: "hòuhuǐ", meaning: "to regret", hsk: 5 },
    { hanzi: "珍惜", pinyin: "zhēnxī", meaning: "to cherish/treasure", hsk: 5 },
    { hanzi: "值得", pinyin: "zhíde", meaning: "to be worth", hsk: 5 },
    { hanzi: "牺牲", pinyin: "xīshēng", meaning: "to sacrifice", hsk: 6 },
    { hanzi: "贡献", pinyin: "gòngxiàn", meaning: "contribution", hsk: 5 },
    { hanzi: "奉献", pinyin: "fèngxiàn", meaning: "to devote/dedicate", hsk: 6 },
    { hanzi: "利益", pinyin: "lìyì", meaning: "benefit/interest", hsk: 5 },
    { hanzi: "损失", pinyin: "sǔnshī", meaning: "loss/damage", hsk: 5 },
    { hanzi: "补偿", pinyin: "bǔcháng", meaning: "compensation", hsk: 6 },
    { hanzi: "赔偿", pinyin: "péicháng", meaning: "to compensate", hsk: 6 },
    { hanzi: "期望", pinyin: "qīwàng", meaning: "to hope/expect", hsk: 5 },
    { hanzi: "愿望", pinyin: "yuànwàng", meaning: "wish/desire", hsk: 5 },
    { hanzi: "梦想", pinyin: "mèngxiǎng", meaning: "dream/aspiration", hsk: 5 },
    { hanzi: "追求", pinyin: "zhuīqiú", meaning: "to pursue", hsk: 5 },
    { hanzi: "奋斗", pinyin: "fèndòu", meaning: "to struggle/fight", hsk: 5 },
    { hanzi: "坚持", pinyin: "jiānchí", meaning: "to persist/insist", hsk: 5 },
    { hanzi: "放弃", pinyin: "fàngqì", meaning: "to give up/abandon", hsk: 5 },
    { hanzi: "犹豫", pinyin: "yóuyù", meaning: "to hesitate", hsk: 5 },
    { hanzi: "果断", pinyin: "guǒduàn", meaning: "decisive/resolute", hsk: 6 },
    { hanzi: "勤奋", pinyin: "qínfèn", meaning: "diligent/hardworking", hsk: 5 },
    { hanzi: "懒惰", pinyin: "lǎnduò", meaning: "lazy/idle", hsk: 6 },
    { hanzi: "耐心", pinyin: "nàixīn", meaning: "patient/patience", hsk: 5 },
    { hanzi: "急躁", pinyin: "jízào", meaning: "impatient/irritable", hsk: 6 },
    { hanzi: "温柔", pinyin: "wēnróu", meaning: "gentle/tender", hsk: 5 },
    { hanzi: "粗暴", pinyin: "cūbào", meaning: "rough/violent", hsk: 6 },
    { hanzi: "善良", pinyin: "shànliáng", meaning: "kind-hearted/good", hsk: 5 },
    { hanzi: "残忍", pinyin: "cánrěn", meaning: "cruel/ruthless", hsk: 6 },
    { hanzi: "诚恳", pinyin: "chéngkěn", meaning: "sincere/earnest", hsk: 6 },
    { hanzi: "虚伪", pinyin: "xūwěi", meaning: "hypocritical/false", hsk: 6 },
    { hanzi: "开朗", pinyin: "kāilǎng", meaning: "cheerful/open", hsk: 5 },
    { hanzi: "内向", pinyin: "nèixiàng", meaning: "introverted/shy", hsk: 5 },
    { hanzi: "外向", pinyin: "wàixiàng", meaning: "extroverted/outgoing", hsk: 5 },
    { hanzi: "幽默", pinyin: "yōumò", meaning: "humorous/funny", hsk: 5 },
    { hanzi: "严肃", pinyin: "yánsù", meaning: "serious/solemn", hsk: 5 },
    { hanzi: "活泼", pinyin: "huópō", meaning: "lively/vivid", hsk: 5 },
    { hanzi: "文静", pinyin: "wénjìng", meaning: "quiet/gentle", hsk: 5 },
    { hanzi: "固执", pinyin: "gùzhí", meaning: "stubborn/obstinate", hsk: 6 },
    { hanzi: "灵活", pinyin: "línghuó", meaning: "flexible/nimble", hsk: 5 },
    { hanzi: "成熟", pinyin: "chéngshú", meaning: "mature/ripe", hsk: 5 },
    { hanzi: "幼稚", pinyin: "yòuzhì", meaning: "childish/naive", hsk: 6 },
    { hanzi: "理性", pinyin: "lǐxìng", meaning: "rational/reason", hsk: 6 },
    { hanzi: "感性", pinyin: "gǎnxìng", meaning: "emotional/perceptual", hsk: 6 },
    { hanzi: "客观", pinyin: "kèguān", meaning: "objective", hsk: 5 },
    { hanzi: "主观", pinyin: "zhǔguān", meaning: "subjective", hsk: 5 },
    { hanzi: "全面", pinyin: "quánmiàn", meaning: "comprehensive", hsk: 5 },
    { hanzi: "片面", pinyin: "piànmiàn", meaning: "one-sided", hsk: 6 },
    { hanzi: "深刻", pinyin: "shēnkè", meaning: "profound/deep", hsk: 5 },
    { hanzi: "肤浅", pinyin: "fūqiǎn", meaning: "superficial/shallow", hsk: 6 },
    { hanzi: "广泛", pinyin: "guǎngfàn", meaning: "extensive/widespread", hsk: 5 },
    { hanzi: "狭窄", pinyin: "xiázhǎi", meaning: "narrow/cramped", hsk: 6 },
    { hanzi: "显著", pinyin: "xiǎnzhù", meaning: "remarkable/notable", hsk: 6 },
    { hanzi: "微妙", pinyin: "wēimiào", meaning: "subtle/delicate", hsk: 6 },
    { hanzi: "模糊", pinyin: "móhu", meaning: "vague/blurry", hsk: 5 },
    { hanzi: "清楚", pinyin: "qīngchu", meaning: "clear/understood", hsk: 4 },
    { hanzi: "明确", pinyin: "míngquè", meaning: "clear/definite", hsk: 5 },
    { hanzi: "含糊", pinyin: "hánhu", meaning: "ambiguous/vague", hsk: 6 },
    { hanzi: "精确", pinyin: "jīngquè", meaning: "precise/accurate", hsk: 6 },
    { hanzi: "大约", pinyin: "dàyuē", meaning: "approximately", hsk: 4 },
    { hanzi: "恰好", pinyin: "qiàhǎo", meaning: "just right/exactly", hsk: 5 },
    { hanzi: "刚好", pinyin: "gānghǎo", meaning: "just right/happen to", hsk: 4 },
    { hanzi: "足够", pinyin: "zúgòu", meaning: "enough/sufficient", hsk: 5 },
    { hanzi: "缺乏", pinyin: "quēfá", meaning: "to lack/shortage", hsk: 5 },
    { hanzi: "充分", pinyin: "chōngfèn", meaning: "sufficient/full", hsk: 5 },
    { hanzi: "过分", pinyin: "guòfèn", meaning: "excessive/too much", hsk: 5 },
    { hanzi: "适当", pinyin: "shìdàng", meaning: "appropriate/proper", hsk: 5 },
    { hanzi: "合理", pinyin: "hélǐ", meaning: "reasonable/rational", hsk: 5 },
    { hanzi: "荒谬", pinyin: "huāngmiù", meaning: "absurd/ridiculous", hsk: 6 },
    { hanzi: "重视", pinyin: "zhòngshì", meaning: "to value/attach importance", hsk: 5 },
    { hanzi: "忽视", pinyin: "hūshì", meaning: "to neglect/ignore", hsk: 5 },
    { hanzi: "关注", pinyin: "guānzhù", meaning: "to pay attention/follow", hsk: 5 },
    { hanzi: "观察", pinyin: "guānchá", meaning: "to observe", hsk: 5 },
    { hanzi: "分析", pinyin: "fēnxī", meaning: "to analyze", hsk: 5 },
    { hanzi: "总结", pinyin: "zǒngjié", meaning: "to summarize", hsk: 5 },
    { hanzi: "归纳", pinyin: "guīnà", meaning: "to summarize/induce", hsk: 6 },
    { hanzi: "推理", pinyin: "tuīlǐ", meaning: "to reason/deduce", hsk: 6 },
    { hanzi: "假设", pinyin: "jiǎshè", meaning: "hypothesis/assume", hsk: 5 },
    { hanzi: "证明", pinyin: "zhèngmíng", meaning: "to prove/proof", hsk: 5 },
    { hanzi: "反驳", pinyin: "fǎnbó", meaning: "to refute", hsk: 6 },
    { hanzi: "支持", pinyin: "zhīchí", meaning: "to support", hsk: 5 },
    { hanzi: "反对", pinyin: "fǎnduì", meaning: "to oppose", hsk: 5 },
    { hanzi: "赞成", pinyin: "zànchéng", meaning: "to approve/agree", hsk: 5 },
    { hanzi: "拒绝", pinyin: "jùjué", meaning: "to refuse/reject", hsk: 5 },
    { hanzi: "接受", pinyin: "jiēshòu", meaning: "to accept", hsk: 5 },
    { hanzi: "采纳", pinyin: "cǎinà", meaning: "to adopt/accept", hsk: 6 },
    { hanzi: "处理", pinyin: "chǔlǐ", meaning: "to handle/process", hsk: 5 },
    { hanzi: "解决", pinyin: "jiějué", meaning: "to solve/resolve", hsk: 4 },
    { hanzi: "克服", pinyin: "kèfú", meaning: "to overcome", hsk: 5 },
    { hanzi: "面对", pinyin: "miànduì", meaning: "to face/confront", hsk: 5 },
    { hanzi: "逃避", pinyin: "táobì", meaning: "to escape/avoid", hsk: 6 },
    { hanzi: "承担", pinyin: "chéngdān", meaning: "to bear/undertake", hsk: 5 },
    { hanzi: "承认", pinyin: "chéngrèn", meaning: "to admit/recognize", hsk: 5 },
    { hanzi: "否认", pinyin: "fǒurèn", meaning: "to deny", hsk: 5 },
    { hanzi: "确认", pinyin: "quèrèn", meaning: "to confirm", hsk: 5 },
    { hanzi: "猛烈", pinyin: "měngliè", meaning: "fierce/violent", hsk: 6 },
    { hanzi: "温和", pinyin: "wēnhé", meaning: "mild/gentle", hsk: 5 },
    { hanzi: "激烈", pinyin: "jīliè", meaning: "intense/fierce", hsk: 5 },
    { hanzi: "缓慢", pinyin: "huǎnmàn", meaning: "slow/gradual", hsk: 5 },
    { hanzi: "迅速", pinyin: "xùnsù", meaning: "rapid/swift", hsk: 5 },
    { hanzi: "逐渐", pinyin: "zhújiàn", meaning: "gradually", hsk: 5 },
    { hanzi: "突然", pinyin: "tūrán", meaning: "suddenly", hsk: 4 },
    { hanzi: "偶然", pinyin: "ǒurán", meaning: "occasionally/by chance", hsk: 5 },
    { hanzi: "必然", pinyin: "bìrán", meaning: "inevitable/certain", hsk: 6 },
    { hanzi: "频繁", pinyin: "pínfán", meaning: "frequent", hsk: 6 },
    { hanzi: "暂时", pinyin: "zànshí", meaning: "temporary/for now", hsk: 5 },
    { hanzi: "永远", pinyin: "yǒngyuǎn", meaning: "forever/always", hsk: 5 },
    { hanzi: "始终", pinyin: "shǐzhōng", meaning: "from start to finish", hsk: 6 },
    { hanzi: "陆续", pinyin: "lùxù", meaning: "one after another", hsk: 6 },
    { hanzi: "同时", pinyin: "tóngshí", meaning: "at the same time", hsk: 4 },
    { hanzi: "分别", pinyin: "fēnbié", meaning: "respectively/separately", hsk: 5 },
    { hanzi: "互相", pinyin: "hùxiāng", meaning: "mutually/each other", hsk: 5 },
    { hanzi: "彼此", pinyin: "bǐcǐ", meaning: "each other", hsk: 5 },
    { hanzi: "个人", pinyin: "gèrén", meaning: "individual/personal", hsk: 5 },
    { hanzi: "集体", pinyin: "jítǐ", meaning: "collective/group", hsk: 5 },
    { hanzi: "团队", pinyin: "tuánduì", meaning: "team", hsk: 5 },
    { hanzi: "领导", pinyin: "lǐngdǎo", meaning: "leader/leadership", hsk: 5 },
    { hanzi: "群众", pinyin: "qúnzhòng", meaning: "the masses/public", hsk: 6 },
    { hanzi: "观众", pinyin: "guānzhòng", meaning: "audience/spectator", hsk: 5 },
    { hanzi: "读者", pinyin: "dúzhě", meaning: "reader", hsk: 5 },
    { hanzi: "听众", pinyin: "tīngzhòng", meaning: "listener/audience", hsk: 5 },
    { hanzi: "专家", pinyin: "zhuānjiā", meaning: "expert/specialist", hsk: 5 },
    { hanzi: "学者", pinyin: "xuézhě", meaning: "scholar/academic", hsk: 5 },
    { hanzi: "天才", pinyin: "tiāncái", meaning: "genius", hsk: 5 },
    { hanzi: "英雄", pinyin: "yīngxióng", meaning: "hero", hsk: 5 },
    { hanzi: "偶像", pinyin: "ǒuxiàng", meaning: "idol", hsk: 5 },
    { hanzi: "模范", pinyin: "mófàn", meaning: "model/role model", hsk: 6 },
    { hanzi: "代表", pinyin: "dàibiǎo", meaning: "representative", hsk: 5 },
    { hanzi: "候选人", pinyin: "hòuxuǎnrén", meaning: "candidate", hsk: 6 },
    { hanzi: "公民", pinyin: "gōngmín", meaning: "citizen", hsk: 5 },
    { hanzi: "居民", pinyin: "jūmín", meaning: "resident", hsk: 5 },
    { hanzi: "移民", pinyin: "yímín", meaning: "immigrant/emigrant", hsk: 5 },
    { hanzi: "难民", pinyin: "nànmín", meaning: "refugee", hsk: 6 },
    { hanzi: "外交", pinyin: "wàijiāo", meaning: "diplomacy", hsk: 6 },
    { hanzi: "大使馆", pinyin: "dàshǐguǎn", meaning: "embassy", hsk: 6 },
    { hanzi: "签署", pinyin: "qiānshǔ", meaning: "to sign (agreement)", hsk: 6 },
    { hanzi: "宣布", pinyin: "xuānbù", meaning: "to announce/declare", hsk: 5 },
    { hanzi: "发布", pinyin: "fābù", meaning: "to publish/release", hsk: 5 },
    { hanzi: "报道", pinyin: "bàodào", meaning: "to report (news)", hsk: 5 },
    { hanzi: "采访", pinyin: "cǎifǎng", meaning: "to interview", hsk: 5 },
    { hanzi: "评论", pinyin: "pínglùn", meaning: "comment/review", hsk: 5 },
    { hanzi: "编辑", pinyin: "biānjí", meaning: "editor/to edit", hsk: 6 },
    { hanzi: "出版", pinyin: "chūbǎn", meaning: "to publish", hsk: 5 },
    { hanzi: "印刷", pinyin: "yìnshuā", meaning: "to print/printing", hsk: 6 },
    { hanzi: "发行", pinyin: "fāxíng", meaning: "to issue/distribute", hsk: 6 },
    { hanzi: "畅销", pinyin: "chàngxiāo", meaning: "bestselling", hsk: 6 },
    { hanzi: "版权", pinyin: "bǎnquán", meaning: "copyright", hsk: 6 },
    { hanzi: "知识产权", pinyin: "zhīshi chǎnquán", meaning: "intellectual property", hsk: 6 },
    { hanzi: "发明", pinyin: "fāmíng", meaning: "to invent/invention", hsk: 5 },
    { hanzi: "创新", pinyin: "chuàngxīn", meaning: "innovation", hsk: 5 },
    { hanzi: "改进", pinyin: "gǎijìn", meaning: "to improve", hsk: 5 },
    { hanzi: "完善", pinyin: "wánshàn", meaning: "to perfect/improve", hsk: 5 },
    { hanzi: "提高", pinyin: "tígāo", meaning: "to raise/improve", hsk: 4 },
    { hanzi: "降低", pinyin: "jiàngdī", meaning: "to reduce/lower", hsk: 5 },
    { hanzi: "增加", pinyin: "zēngjiā", meaning: "to increase", hsk: 4 },
    { hanzi: "减少", pinyin: "jiǎnshǎo", meaning: "to decrease/reduce", hsk: 4 },
    { hanzi: "扩大", pinyin: "kuòdà", meaning: "to expand/enlarge", hsk: 5 },
    { hanzi: "缩小", pinyin: "suōxiǎo", meaning: "to shrink/reduce", hsk: 5 },
    { hanzi: "延长", pinyin: "yáncháng", meaning: "to extend/prolong", hsk: 5 },
    { hanzi: "缩短", pinyin: "suōduǎn", meaning: "to shorten", hsk: 5 },
    { hanzi: "加速", pinyin: "jiāsù", meaning: "to accelerate", hsk: 5 },
    { hanzi: "减速", pinyin: "jiǎnsù", meaning: "to decelerate", hsk: 5 },
    { hanzi: "推动", pinyin: "tuīdòng", meaning: "to promote/push", hsk: 5 },
    { hanzi: "阻碍", pinyin: "zǔ'ài", meaning: "to hinder/obstruct", hsk: 6 },
    { hanzi: "促进", pinyin: "cùjìn", meaning: "to promote/advance", hsk: 5 },
    { hanzi: "刺激", pinyin: "cìjī", meaning: "to stimulate", hsk: 5 },
    { hanzi: "启发", pinyin: "qǐfā", meaning: "to inspire/enlighten", hsk: 5 },
    { hanzi: "培养", pinyin: "péiyǎng", meaning: "to cultivate/train", hsk: 5 },
    { hanzi: "训练", pinyin: "xùnliàn", meaning: "to train/training", hsk: 5 },
    { hanzi: "指导", pinyin: "zhǐdǎo", meaning: "to guide/instruct", hsk: 5 },
    { hanzi: "辅导", pinyin: "fǔdǎo", meaning: "to tutor/counsel", hsk: 5 },
    { hanzi: "评价", pinyin: "píngjià", meaning: "to evaluate", hsk: 5 },
    { hanzi: "考核", pinyin: "kǎohé", meaning: "to assess/examine", hsk: 6 },
    { hanzi: "录取", pinyin: "lùqǔ", meaning: "to admit/enroll", hsk: 5 },
    { hanzi: "淘汰", pinyin: "táotài", meaning: "to eliminate/phase out", hsk: 6 },
    { hanzi: "竞选", pinyin: "jìngxuǎn", meaning: "to campaign/run for", hsk: 6 },
    { hanzi: "投票", pinyin: "tóupiào", meaning: "to vote", hsk: 5 },
    { hanzi: "选举", pinyin: "xuǎnjǔ", meaning: "election", hsk: 5 },
    { hanzi: "当选", pinyin: "dāngxuǎn", meaning: "to be elected", hsk: 6 },
    { hanzi: "就任", pinyin: "jiùrèn", meaning: "to take office", hsk: 6 },
    { hanzi: "辞职", pinyin: "cízhí", meaning: "to resign", hsk: 5 },
    { hanzi: "退休", pinyin: "tuìxiū", meaning: "to retire", hsk: 5 },
    { hanzi: "失业", pinyin: "shīyè", meaning: "unemployment", hsk: 5 },
    { hanzi: "就业", pinyin: "jiùyè", meaning: "employment", hsk: 5 },
    { hanzi: "创业", pinyin: "chuàngyè", meaning: "to start a business", hsk: 5 },
    { hanzi: "企业", pinyin: "qǐyè", meaning: "enterprise/business", hsk: 5 },
    { hanzi: "公司", pinyin: "gōngsī", meaning: "company", hsk: 3 },
    { hanzi: "工厂", pinyin: "gōngchǎng", meaning: "factory", hsk: 4 },
    { hanzi: "机构", pinyin: "jīgòu", meaning: "institution/organization", hsk: 5 },
    { hanzi: "部门", pinyin: "bùmén", meaning: "department", hsk: 5 },
    { hanzi: "预算", pinyin: "yùsuàn", meaning: "budget", hsk: 6 },
    { hanzi: "利润", pinyin: "lìrùn", meaning: "profit", hsk: 6 },
    { hanzi: "亏损", pinyin: "kuīsǔn", meaning: "loss/deficit", hsk: 6 },
    { hanzi: "破产", pinyin: "pòchǎn", meaning: "bankruptcy", hsk: 6 },
    { hanzi: "合并", pinyin: "hébìng", meaning: "to merge/combine", hsk: 6 },
    { hanzi: "分裂", pinyin: "fēnliè", meaning: "to split/divide", hsk: 6 },
    { hanzi: "垄断", pinyin: "lǒngduàn", meaning: "monopoly", hsk: 6 },
    { hanzi: "通货膨胀", pinyin: "tōnghuò péngzhàng", meaning: "inflation", hsk: 6 },
    { hanzi: "经济衰退", pinyin: "jīngjì shuāituì", meaning: "economic recession", hsk: 6 },
    { hanzi: "可持续", pinyin: "kě chíxù", meaning: "sustainable", hsk: 6 },
    { hanzi: "全球化", pinyin: "quánqiúhuà", meaning: "globalization", hsk: 6 },
    { hanzi: "现代化", pinyin: "xiàndàihuà", meaning: "modernization", hsk: 5 },
    { hanzi: "工业化", pinyin: "gōngyèhuà", meaning: "industrialization", hsk: 6 },
    { hanzi: "城市化", pinyin: "chéngshìhuà", meaning: "urbanization", hsk: 6 },
    { hanzi: "信息化", pinyin: "xìnxīhuà", meaning: "informatization", hsk: 6 },
    { hanzi: "数字化", pinyin: "shùzìhuà", meaning: "digitalization", hsk: 6 },
    { hanzi: "自动化", pinyin: "zìdònghuà", meaning: "automation", hsk: 6 },
    { hanzi: "人工智能", pinyin: "réngōng zhìnéng", meaning: "artificial intelligence", hsk: 6 },
    { hanzi: "大数据", pinyin: "dà shùjù", meaning: "big data", hsk: 6 },
    { hanzi: "云计算", pinyin: "yún jìsuàn", meaning: "cloud computing", hsk: 6 },
    { hanzi: "区块链", pinyin: "qūkuàiliàn", meaning: "blockchain", hsk: 6 },
    { hanzi: "物联网", pinyin: "wùliánwǎng", meaning: "Internet of Things", hsk: 6 },
    { hanzi: "虚拟现实", pinyin: "xūnǐ xiànshí", meaning: "virtual reality", hsk: 6 },
    { hanzi: "电子商务", pinyin: "diànzǐ shāngwù", meaning: "e-commerce", hsk: 6 },
    { hanzi: "社交媒体", pinyin: "shèjiāo méitǐ", meaning: "social media", hsk: 5 },
    { hanzi: "视频会议", pinyin: "shìpín huìyì", meaning: "video conference", hsk: 5 },
    { hanzi: "在线学习", pinyin: "zàixiàn xuéxí", meaning: "online learning", hsk: 5 },
    { hanzi: "远程工作", pinyin: "yuǎnchéng gōngzuò", meaning: "remote work", hsk: 5 },
    { hanzi: "生态系统", pinyin: "shēngtài xìtǒng", meaning: "ecosystem", hsk: 6 },
    { hanzi: "温室效应", pinyin: "wēnshì xiàoyìng", meaning: "greenhouse effect", hsk: 6 },
    { hanzi: "碳排放", pinyin: "tàn páifàng", meaning: "carbon emissions", hsk: 6 },
    { hanzi: "垃圾分类", pinyin: "lājī fēnlèi", meaning: "waste sorting", hsk: 5 },
    { hanzi: "可再生", pinyin: "kě zàishēng", meaning: "renewable", hsk: 6 },
    { hanzi: "太阳能", pinyin: "tàiyáng néng", meaning: "solar energy", hsk: 5 },
    { hanzi: "风力发电", pinyin: "fēnglì fādiàn", meaning: "wind power", hsk: 6 },
    { hanzi: "核能", pinyin: "hénéng", meaning: "nuclear energy", hsk: 6 },
    { hanzi: "水力发电", pinyin: "shuǐlì fādiàn", meaning: "hydroelectric power", hsk: 6 },
    { hanzi: "电动汽车", pinyin: "diàndòng qìchē", meaning: "electric vehicle", hsk: 5 },
    { hanzi: "共享单车", pinyin: "gòngxiǎng dānchē", meaning: "bike sharing", hsk: 5 },
    { hanzi: "高速铁路", pinyin: "gāosù tiělù", meaning: "high-speed rail", hsk: 5 },
    { hanzi: "航空", pinyin: "hángkōng", meaning: "aviation", hsk: 6 },
    { hanzi: "航天", pinyin: "hángtiān", meaning: "space/aerospace", hsk: 6 },
    { hanzi: "卫星", pinyin: "wèixīng", meaning: "satellite", hsk: 6 },
    { hanzi: "探索", pinyin: "tànsuǒ", meaning: "to explore", hsk: 5 },
    { hanzi: "发现", pinyin: "fāxiàn", meaning: "to discover", hsk: 4 },
    { hanzi: "突破", pinyin: "tūpò", meaning: "breakthrough", hsk: 5 },
    { hanzi: "进步", pinyin: "jìnbù", meaning: "progress/advance", hsk: 4 },
    { hanzi: "落后", pinyin: "luòhòu", meaning: "backward/behind", hsk: 5 },
    { hanzi: "先进", pinyin: "xiānjìn", meaning: "advanced", hsk: 5 },
    { hanzi: "传承", pinyin: "chuánchéng", meaning: "to inherit/pass down", hsk: 6 },
    { hanzi: "继承", pinyin: "jìchéng", meaning: "to inherit", hsk: 5 },
    { hanzi: "遗产", pinyin: "yíchǎn", meaning: "heritage/legacy", hsk: 5 },
    { hanzi: "古迹", pinyin: "gǔjì", meaning: "historic site", hsk: 5 },
    { hanzi: "文物", pinyin: "wénwù", meaning: "cultural relic", hsk: 5 },
    { hanzi: "非物质文化遗产", pinyin: "fēi wùzhì wénhuà yíchǎn", meaning: "intangible cultural heritage", hsk: 6 },
    { hanzi: "博览会", pinyin: "bólǎnhuì", meaning: "expo/exhibition", hsk: 6 },
    { hanzi: "奥运会", pinyin: "àoyùnhuì", meaning: "Olympic Games", hsk: 5 },
    { hanzi: "世界杯", pinyin: "shìjièbēi", meaning: "World Cup", hsk: 5 },
    { hanzi: "冠军", pinyin: "guànjūn", meaning: "champion", hsk: 5 },
    { hanzi: "亚军", pinyin: "yàjūn", meaning: "runner-up", hsk: 6 },
    { hanzi: "金牌", pinyin: "jīnpái", meaning: "gold medal", hsk: 5 },
    { hanzi: "银牌", pinyin: "yínpái", meaning: "silver medal", hsk: 5 },
    { hanzi: "铜牌", pinyin: "tóngpái", meaning: "bronze medal", hsk: 5 },
    { hanzi: "裁判", pinyin: "cáipàn", meaning: "referee/judge", hsk: 6 },
    { hanzi: "观赛", pinyin: "guānsài", meaning: "to watch a game", hsk: 5 },
    { hanzi: "转播", pinyin: "zhuǎnbō", meaning: "broadcast/relay", hsk: 6 },
    { hanzi: "主持人", pinyin: "zhǔchírén", meaning: "host/presenter", hsk: 5 },
    { hanzi: "嘉宾", pinyin: "jiābīn", meaning: "guest (of honor)", hsk: 6 },
    { hanzi: "颁奖", pinyin: "bānjiǎng", meaning: "to award a prize", hsk: 6 },
    { hanzi: "仪式", pinyin: "yíshì", meaning: "ceremony/ritual", hsk: 5 },
    { hanzi: "庆祝", pinyin: "qìngzhù", meaning: "to celebrate", hsk: 5 },
    { hanzi: "纪念", pinyin: "jìniàn", meaning: "to commemorate", hsk: 5 },
    { hanzi: "回忆", pinyin: "huíyì", meaning: "to recall/memory", hsk: 5 },
    { hanzi: "怀念", pinyin: "huáiniàn", meaning: "to miss/cherish", hsk: 5 },
    { hanzi: "留恋", pinyin: "liúliàn", meaning: "to be reluctant to leave", hsk: 6 },
    { hanzi: "向往", pinyin: "xiàngwǎng", meaning: "to yearn for", hsk: 5 },
    { hanzi: "渴望", pinyin: "kěwàng", meaning: "to long for/desire", hsk: 5 },
    { hanzi: "期待", pinyin: "qīdài", meaning: "to expect/look forward to", hsk: 5 },
    { hanzi: "盼望", pinyin: "pànwàng", meaning: "to hope/long for", hsk: 5 },
    { hanzi: "畅想", pinyin: "chàngxiǎng", meaning: "to imagine freely", hsk: 6 },
    { hanzi: "幻想", pinyin: "huànxiǎng", meaning: "fantasy/illusion", hsk: 5 },
    { hanzi: "现实", pinyin: "xiànshí", meaning: "reality", hsk: 5 },
    { hanzi: "虚拟", pinyin: "xūnǐ", meaning: "virtual/fictitious", hsk: 6 },
    { hanzi: "真实", pinyin: "zhēnshí", meaning: "real/true", hsk: 5 },
    { hanzi: "虚假", pinyin: "xūjiǎ", meaning: "false/fake", hsk: 6 },
    { hanzi: "正义", pinyin: "zhèngyì", meaning: "justice", hsk: 6 },
    { hanzi: "公平", pinyin: "gōngpíng", meaning: "fair/just", hsk: 5 },
    { hanzi: "公正", pinyin: "gōngzhèng", meaning: "impartial/fair", hsk: 6 },
    { hanzi: "诚信", pinyin: "chéngxìn", meaning: "honesty/integrity", hsk: 6 },
    { hanzi: "道义", pinyin: "dàoyì", meaning: "morality/justice", hsk: 6 },
    { hanzi: "良心", pinyin: "liángxīn", meaning: "conscience", hsk: 5 },
    { hanzi: "责任感", pinyin: "zérèngǎn", meaning: "sense of responsibility", hsk: 5 },
    { hanzi: "使命感", pinyin: "shǐmìnggǎn", meaning: "sense of mission", hsk: 6 },
    { hanzi: "归属感", pinyin: "guīshǔgǎn", meaning: "sense of belonging", hsk: 6 },
    { hanzi: "幸福感", pinyin: "xìngfúgǎn", meaning: "sense of happiness", hsk: 5 },
    { hanzi: "安全感", pinyin: "ānquángǎn", meaning: "sense of security", hsk: 5 },
    { hanzi: "自信心", pinyin: "zìxìnxīn", meaning: "self-confidence", hsk: 5 },
    { hanzi: "好奇心", pinyin: "hàoqíxīn", meaning: "curiosity", hsk: 5 },
    { hanzi: "同理心", pinyin: "tónglǐxīn", meaning: "empathy", hsk: 6 },
    { hanzi: "想象力", pinyin: "xiǎngxiànglì", meaning: "imagination", hsk: 5 },
    { hanzi: "创造力", pinyin: "chuàngzàolì", meaning: "creativity", hsk: 5 },
    { hanzi: "执行力", pinyin: "zhíxínglì", meaning: "execution ability", hsk: 6 },
    { hanzi: "领导力", pinyin: "lǐngdǎolì", meaning: "leadership", hsk: 6 },
    { hanzi: "影响力", pinyin: "yǐngxiǎnglì", meaning: "influence/impact", hsk: 5 },
    { hanzi: "竞争力", pinyin: "jìngzhēnglì", meaning: "competitiveness", hsk: 5 },
    { hanzi: "生产力", pinyin: "shēngchǎnlì", meaning: "productivity", hsk: 6 },
    { hanzi: "购买力", pinyin: "gòumǎilì", meaning: "purchasing power", hsk: 6 },
    { hanzi: "生活水平", pinyin: "shēnghuó shuǐpíng", meaning: "standard of living", hsk: 5 },
    { hanzi: "生活方式", pinyin: "shēnghuó fāngshì", meaning: "lifestyle", hsk: 5 },
    { hanzi: "价值观", pinyin: "jiàzhíguān", meaning: "values/worldview", hsk: 5 },
    { hanzi: "世界观", pinyin: "shìjièguān", meaning: "worldview", hsk: 6 },
    { hanzi: "人生观", pinyin: "rénshēngguān", meaning: "outlook on life", hsk: 6 },
    { hanzi: "审美", pinyin: "shěnměi", meaning: "aesthetic appreciation", hsk: 6 },
    { hanzi: "品味", pinyin: "pǐnwèi", meaning: "taste/style", hsk: 5 },
    { hanzi: "修养", pinyin: "xiūyǎng", meaning: "cultivation/refinement", hsk: 6 },
    { hanzi: "素质", pinyin: "sùzhì", meaning: "quality/character", hsk: 5 },
    { hanzi: "能力", pinyin: "nénglì", meaning: "ability/capability", hsk: 4 },
    { hanzi: "潜力", pinyin: "qiánlì", meaning: "potential", hsk: 5 },
    { hanzi: "天赋", pinyin: "tiānfù", meaning: "talent/gift", hsk: 6 },
    { hanzi: "智慧", pinyin: "zhìhuì", meaning: "wisdom/intelligence", hsk: 5 },
    { hanzi: "才华", pinyin: "cáihuá", meaning: "talent/ability", hsk: 5 },
    { hanzi: "魅力", pinyin: "mèilì", meaning: "charm/charisma", hsk: 5 },
    { hanzi: "气质", pinyin: "qìzhì", meaning: "temperament/aura", hsk: 5 },
    { hanzi: "涵养", pinyin: "hányǎng", meaning: "self-restraint/cultivation", hsk: 6 },
    { hanzi: "胸怀", pinyin: "xiōnghuái", meaning: "mind/breadth of vision", hsk: 6 },
    { hanzi: "格局", pinyin: "géjú", meaning: "pattern/vision", hsk: 6 },
    { hanzi: "境界", pinyin: "jìngjiè", meaning: "realm/level", hsk: 6 },
    { hanzi: "情怀", pinyin: "qínghuái", meaning: "feelings/sentiments", hsk: 6 },
    { hanzi: "执着", pinyin: "zhízhuó", meaning: "persistent/devoted", hsk: 6 },
    { hanzi: "淡定", pinyin: "dàndìng", meaning: "calm/composed", hsk: 6 },
    { hanzi: "从容", pinyin: "cóngróng", meaning: "calm/unhurried", hsk: 6 },
    { hanzi: "豁达", pinyin: "huòdá", meaning: "open-minded/generous", hsk: 6 },
    { hanzi: "包容", pinyin: "bāoróng", meaning: "tolerant/inclusive", hsk: 5 },
    { hanzi: "宽容", pinyin: "kuānróng", meaning: "tolerant/forgiving", hsk: 5 },
    { hanzi: "感恩", pinyin: "gǎn'ēn", meaning: "to be grateful", hsk: 5 },
    { hanzi: "知足", pinyin: "zhīzú", meaning: "content/satisfied", hsk: 6 },
    { hanzi: "随遇而安", pinyin: "suí yù ér ān", meaning: "be content with one's lot", hsk: 6 },
    { hanzi: "入乡随俗", pinyin: "rù xiāng suí sú", meaning: "when in Rome do as Romans do", hsk: 5 },
    { hanzi: "因材施教", pinyin: "yīn cái shī jiào", meaning: "teach according to aptitude", hsk: 6 },
    { hanzi: "温故知新", pinyin: "wēn gù zhī xīn", meaning: "review the old to learn the new", hsk: 5 },
    { hanzi: "学以致用", pinyin: "xué yǐ zhì yòng", meaning: "learn to apply in practice", hsk: 5 },
    { hanzi: "循序渐进", pinyin: "xún xù jiàn jìn", meaning: "step by step/gradually", hsk: 6 },
    { hanzi: "举一反三", pinyin: "jǔ yī fǎn sān", meaning: "infer broadly from one example", hsk: 5 },
    { hanzi: "事半功倍", pinyin: "shì bàn gōng bèi", meaning: "half effort double result", hsk: 5 },
    { hanzi: "熟能生巧", pinyin: "shú néng shēng qiǎo", meaning: "practice makes perfect", hsk: 5 },
    { hanzi: "见多识广", pinyin: "jiàn duō shí guǎng", meaning: "well-informed/experienced", hsk: 6 },
    { hanzi: "百闻不如一见", pinyin: "bǎi wén bùrú yī jiàn", meaning: "seeing is believing", hsk: 5 },
    { hanzi: "有志者事竟成", pinyin: "yǒu zhì zhě shì jìng chéng", meaning: "where there's a will there's a way", hsk: 5 },
    { hanzi: "台上一分钟", pinyin: "tái shàng yī fēnzhōng", meaning: "one minute on stage (years of practice)", hsk: 6 },
    { hanzi: "活到老学到老", pinyin: "huó dào lǎo xué dào lǎo", meaning: "live and learn / never stop learning", hsk: 5 },
    { hanzi: "知己知彼", pinyin: "zhī jǐ zhī bǐ", meaning: "know yourself and your enemy", hsk: 6 },
    { hanzi: "亡羊补牢", pinyin: "wáng yáng bǔ láo", meaning: "better late than never", hsk: 5 },
    { hanzi: "画龙点睛", pinyin: "huà lóng diǎn jīng", meaning: "add the finishing touch", hsk: 6 },
    { hanzi: "自力更生", pinyin: "zìlì gēngshēng", meaning: "self-reliance", hsk: 6 },
    { hanzi: "团结合作", pinyin: "tuánjié hézuò", meaning: "solidarity and cooperation", hsk: 5 },
    { hanzi: "和平共处", pinyin: "hépíng gòngchǔ", meaning: "peaceful coexistence", hsk: 5 },
    { hanzi: "互利共赢", pinyin: "hùlì gòng yíng", meaning: "mutual benefit and win-win", hsk: 6 },
    { hanzi: "开放包容", pinyin: "kāifàng bāoróng", meaning: "open and inclusive", hsk: 5 },
    { hanzi: "与时俱进", pinyin: "yǔ shí jù jìn", meaning: "keep pace with the times", hsk: 6 },
    { hanzi: "实事求是", pinyin: "shíshì qiúshì", meaning: "seek truth from facts", hsk: 6 },
    { hanzi: "脚踏实地", pinyin: "jiǎo tà shí dì", meaning: "down-to-earth/practical", hsk: 6 },
    { hanzi: "承前启后", pinyin: "chéng qián qǐ hòu", meaning: "inherit past and inspire future", hsk: 6 },
    { hanzi: "推陈出新", pinyin: "tuī chén chū xīn", meaning: "discard old and bring in new", hsk: 6 },
    { hanzi: "别具一格", pinyin: "bié jù yī gé", meaning: "unique/distinctive", hsk: 6 },
    { hanzi: "博大精深", pinyin: "bó dà jīng shēn", meaning: "broad and profound", hsk: 6 },
    { hanzi: "源远流长", pinyin: "yuán yuǎn liú cháng", meaning: "long history/deep roots", hsk: 6 },
    { hanzi: "日新月异", pinyin: "rì xīn yuè yì", meaning: "changing rapidly", hsk: 6 },
    { hanzi: "刻苦学习", pinyin: "kèkǔ xuéxí", meaning: "to study diligently", hsk: 4 },
    { hanzi: "课外活动", pinyin: "kèwài huódòng", meaning: "extracurricular activity", hsk: 4 },
    { hanzi: "志愿服务", pinyin: "zhìyuàn fúwù", meaning: "volunteer service", hsk: 5 },
    { hanzi: "社会实践", pinyin: "shèhuì shíjiàn", meaning: "social practice", hsk: 5 },
    { hanzi: "文化交流", pinyin: "wénhuà jiāoliú", meaning: "cultural exchange", hsk: 4 },
    { hanzi: "国际合作", pinyin: "guójì hézuò", meaning: "international cooperation", hsk: 5 },
    { hanzi: "人权", pinyin: "rénquán", meaning: "human rights", hsk: 6 },
    { hanzi: "和平", pinyin: "hépíng", meaning: "peace", hsk: 4 },
    { hanzi: "战争", pinyin: "zhànzhēng", meaning: "war", hsk: 5 },
    { hanzi: "武器", pinyin: "wǔqì", meaning: "weapon", hsk: 6 },
    { hanzi: "军事", pinyin: "jūnshì", meaning: "military", hsk: 6 },
    { hanzi: "核武器", pinyin: "hé wǔqì", meaning: "nuclear weapon", hsk: 6 },
    { hanzi: "裁军", pinyin: "cáijūn", meaning: "disarmament", hsk: 6 },
    { hanzi: "安全理事会", pinyin: "ānquán lǐshìhuì", meaning: "Security Council", hsk: 6 },
    { hanzi: "联合国", pinyin: "liánhéguó", meaning: "United Nations", hsk: 5 },
    { hanzi: "世界贸易组织", pinyin: "shìjiè màoyì zǔzhī", meaning: "World Trade Organization", hsk: 6 },
    { hanzi: "国际货币基金", pinyin: "guójì huòbì jījīn", meaning: "International Monetary Fund", hsk: 6 },
    { hanzi: "文化多样性", pinyin: "wénhuà duōyàngxìng", meaning: "cultural diversity", hsk: 6 },
    { hanzi: "种族歧视", pinyin: "zhǒngzú qíshì", meaning: "racial discrimination", hsk: 6 },
    { hanzi: "性别平等", pinyin: "xìngbié píngděng", meaning: "gender equality", hsk: 6 },
    { hanzi: "社会公正", pinyin: "shèhuì gōngzhèng", meaning: "social justice", hsk: 6 },
    { hanzi: "医疗保障", pinyin: "yīliáo bǎozhàng", meaning: "healthcare security", hsk: 6 },
    { hanzi: "食品安全", pinyin: "shípǐn ānquán", meaning: "food safety", hsk: 5 },
    { hanzi: "交通安全", pinyin: "jiāotōng ānquán", meaning: "traffic safety", hsk: 4 },
    { hanzi: "消防安全", pinyin: "xiāofáng ānquán", meaning: "fire safety", hsk: 5 },
    { hanzi: "心理健康", pinyin: "xīnlǐ jiànkāng", meaning: "mental health", hsk: 5 },
    { hanzi: "生活质量", pinyin: "shēnghuó zhìliàng", meaning: "quality of life", hsk: 5 },
    { hanzi: "幸福指数", pinyin: "xìngfú zhǐshù", meaning: "happiness index", hsk: 6 },
    { hanzi: "人均收入", pinyin: "rénjūn shōurù", meaning: "per capita income", hsk: 6 },
    { hanzi: "基尼系数", pinyin: "jīní xìshù", meaning: "Gini coefficient", hsk: 6 },
    { hanzi: "通勤", pinyin: "tōngqín", meaning: "commute", hsk: 5 },
    { hanzi: "拥堵", pinyin: "yōngdǔ", meaning: "congestion/traffic jam", hsk: 5 },
    { hanzi: "智能手机", pinyin: "zhìnéng shǒujī", meaning: "smartphone", hsk: 5 },
    { hanzi: "即时通讯", pinyin: "jíshí tōngxùn", meaning: "instant messaging", hsk: 6 },
    { hanzi: "二维码", pinyin: "èr wéi mǎ", meaning: "QR code", hsk: 5 },
    { hanzi: "刷卡", pinyin: "shuākǎ", meaning: "to swipe a card", hsk: 5 },
    { hanzi: "扫码支付", pinyin: "sǎo mǎ zhīfù", meaning: "scan-to-pay", hsk: 5 },
    { hanzi: "直播", pinyin: "zhíbō", meaning: "live streaming", hsk: 5 },
    { hanzi: "短视频", pinyin: "duǎn shìpín", meaning: "short video", hsk: 5 },
    { hanzi: "弹幕", pinyin: "dànmù", meaning: "bullet screen comments", hsk: 6 },
    { hanzi: "网红", pinyin: "wǎnghóng", meaning: "internet celebrity", hsk: 5 },
    { hanzi: "代购", pinyin: "dàigòu", meaning: "proxy purchasing", hsk: 5 },
    { hanzi: "跨境电商", pinyin: "kuà jìng diàn shāng", meaning: "cross-border e-commerce", hsk: 6 },
    { hanzi: "物流", pinyin: "wùliú", meaning: "logistics", hsk: 5 },
    { hanzi: "仓储", pinyin: "cāngchǔ", meaning: "warehousing/storage", hsk: 6 },
    { hanzi: "配送", pinyin: "pèisòng", meaning: "delivery/distribution", hsk: 5 },
    { hanzi: "售后", pinyin: "shòuhòu", meaning: "after-sales", hsk: 5 },
    { hanzi: "保修", pinyin: "bǎoxiū", meaning: "warranty", hsk: 5 },
    { hanzi: "理赔", pinyin: "lǐpéi", meaning: "claims settlement", hsk: 6 },
    { hanzi: "公积金", pinyin: "gōngjījīn", meaning: "housing fund", hsk: 6 },
    { hanzi: "社保", pinyin: "shèbǎo", meaning: "social security", hsk: 5 },
    { hanzi: "退税", pinyin: "tuìshuì", meaning: "tax refund", hsk: 6 },
    { hanzi: "报销", pinyin: "bàoxiāo", meaning: "to reimburse", hsk: 5 },
    { hanzi: "审批", pinyin: "shěnpī", meaning: "to approve/review", hsk: 6 },
    { hanzi: "申请", pinyin: "shēnqǐng", meaning: "to apply", hsk: 4 },
    { hanzi: "批准", pinyin: "pīzhǔn", meaning: "to approve", hsk: 5 },
    { hanzi: "户口", pinyin: "hùkǒu", meaning: "household registration", hsk: 6 },
    { hanzi: "档案", pinyin: "dàng'àn", meaning: "file/archive", hsk: 6 },
    { hanzi: "证件", pinyin: "zhèngjiàn", meaning: "documents/credentials", hsk: 5 },
    { hanzi: "登记", pinyin: "dēngjì", meaning: "to register", hsk: 5 },
    { hanzi: "户籍", pinyin: "hùjí", meaning: "household register", hsk: 6 },
    { hanzi: "身份证", pinyin: "shēnfènzhèng", meaning: "identity card", hsk: 4 },
    { hanzi: "驾照", pinyin: "jiàzhào", meaning: "driver's license", hsk: 5 },
    { hanzi: "贷款", pinyin: "dàikuǎn", meaning: "loan", hsk: 5 },
    { hanzi: "利率", pinyin: "lìlǜ", meaning: "interest rate", hsk: 6 },
    { hanzi: "汇率", pinyin: "huìlǜ", meaning: "exchange rate", hsk: 6 },
    { hanzi: "通货", pinyin: "tōnghuò", meaning: "currency", hsk: 6 },
    { hanzi: "债务", pinyin: "zhàiwù", meaning: "debt", hsk: 6 },
    { hanzi: "股票", pinyin: "gǔpiào", meaning: "stock/shares", hsk: 5 },
    { hanzi: "基金", pinyin: "jījīn", meaning: "fund", hsk: 5 },
    { hanzi: "债券", pinyin: "zhàiquàn", meaning: "bond", hsk: 6 },
    { hanzi: "房地产", pinyin: "fángdìchǎn", meaning: "real estate", hsk: 5 },
    { hanzi: "拍卖", pinyin: "pāimài", meaning: "auction", hsk: 6 },
    { hanzi: "招标", pinyin: "zhāobiāo", meaning: "to invite bids", hsk: 6 },
    { hanzi: "投标", pinyin: "tóubiāo", meaning: "to submit a bid", hsk: 6 },
    { hanzi: "签合同", pinyin: "qiān hétong", meaning: "to sign a contract", hsk: 5 },
    { hanzi: "履行", pinyin: "lǚxíng", meaning: "to fulfill/perform", hsk: 6 },
    { hanzi: "违约", pinyin: "wéiyuē", meaning: "breach of contract", hsk: 6 },
    { hanzi: "仲裁", pinyin: "zhòngcái", meaning: "arbitration", hsk: 6 },
    { hanzi: "诉讼", pinyin: "sùsòng", meaning: "lawsuit/litigation", hsk: 6 },
    { hanzi: "证据", pinyin: "zhèngjù", meaning: "evidence/proof", hsk: 5 },
    { hanzi: "辩护", pinyin: "biànhù", meaning: "to defend (in court)", hsk: 6 },
    { hanzi: "判决", pinyin: "pànjué", meaning: "verdict/judgment", hsk: 6 },
    { hanzi: "上诉", pinyin: "shàngsù", meaning: "to appeal", hsk: 6 },
    { hanzi: "赦免", pinyin: "shèmiǎn", meaning: "to pardon", hsk: 6 },
    { hanzi: "逮捕", pinyin: "dàibǔ", meaning: "to arrest", hsk: 6 },
    { hanzi: "拘留", pinyin: "jūliú", meaning: "to detain", hsk: 6 },
    { hanzi: "监狱", pinyin: "jiānyù", meaning: "prison", hsk: 6 },
    { hanzi: "审判", pinyin: "shěnpàn", meaning: "to try (in court)", hsk: 6 },
    { hanzi: "公检法", pinyin: "gōng jiǎn fǎ", meaning: "police, procuratorate, court", hsk: 6 },
    { hanzi: "天文", pinyin: "tiānwén", meaning: "astronomy", hsk: 6 },
    { hanzi: "物种", pinyin: "wùzhǒng", meaning: "species", hsk: 6 },
    { hanzi: "进化", pinyin: "jìnhuà", meaning: "evolution", hsk: 6 },
    { hanzi: "基因", pinyin: "jīyīn", meaning: "gene", hsk: 6 },
    { hanzi: "细胞", pinyin: "xìbāo", meaning: "cell (biology)", hsk: 6 },
    { hanzi: "分子", pinyin: "fēnzǐ", meaning: "molecule", hsk: 6 },
    { hanzi: "原子", pinyin: "yuánzǐ", meaning: "atom", hsk: 6 },
    { hanzi: "电子", pinyin: "diànzǐ", meaning: "electron/electronic", hsk: 5 },
    { hanzi: "光速", pinyin: "guāngsù", meaning: "speed of light", hsk: 6 },
    { hanzi: "引力", pinyin: "yǐnlì", meaning: "gravity/attraction", hsk: 6 },
    { hanzi: "磁场", pinyin: "cíchǎng", meaning: "magnetic field", hsk: 6 },
    { hanzi: "辐射", pinyin: "fúshè", meaning: "radiation", hsk: 6 },
    { hanzi: "频率", pinyin: "pínlǜ", meaning: "frequency", hsk: 6 },
    { hanzi: "波长", pinyin: "bōcháng", meaning: "wavelength", hsk: 6 },
    { hanzi: "光合作用", pinyin: "guānghé zuòyòng", meaning: "photosynthesis", hsk: 6 },
    { hanzi: "新陈代谢", pinyin: "xīnchén dàixiè", meaning: "metabolism", hsk: 6 },
    { hanzi: "免疫系统", pinyin: "miǎnyì xìtǒng", meaning: "immune system", hsk: 6 },
    { hanzi: "氧气", pinyin: "yǎngqì", meaning: "oxygen", hsk: 6 },
    { hanzi: "二氧化碳", pinyin: "èr yǎnghuà tàn", meaning: "carbon dioxide", hsk: 6 },
    { hanzi: "臭氧层", pinyin: "chòuyǎng céng", meaning: "ozone layer", hsk: 6 },
    { hanzi: "海平面", pinyin: "hǎi píngmiàn", meaning: "sea level", hsk: 6 },
    { hanzi: "冰川", pinyin: "bīngchuān", meaning: "glacier", hsk: 6 },
    { hanzi: "极地", pinyin: "jídì", meaning: "polar region", hsk: 6 },
    { hanzi: "热带", pinyin: "rèdài", meaning: "tropical zone", hsk: 6 },
    { hanzi: "温带", pinyin: "wēndài", meaning: "temperate zone", hsk: 6 },
    { hanzi: "寒带", pinyin: "hándài", meaning: "frigid zone", hsk: 6 },
    { hanzi: "季风", pinyin: "jìfēng", meaning: "monsoon", hsk: 6 },
    { hanzi: "干旱", pinyin: "gānhàn", meaning: "drought", hsk: 6 },
    { hanzi: "水灾", pinyin: "shuǐzāi", meaning: "flood disaster", hsk: 6 },
    { hanzi: "火灾", pinyin: "huǒzāi", meaning: "fire disaster", hsk: 5 },
    { hanzi: "灾害", pinyin: "zāihài", meaning: "disaster/calamity", hsk: 5 },
    { hanzi: "救灾", pinyin: "jiùzāi", meaning: "disaster relief", hsk: 6 },
    { hanzi: "避难", pinyin: "bìnàn", meaning: "to take refuge", hsk: 6 },
    { hanzi: "物资", pinyin: "wùzī", meaning: "supplies/materials", hsk: 6 },
    { hanzi: "捐款", pinyin: "juānkuǎn", meaning: "to donate money", hsk: 5 },
    { hanzi: "慈善", pinyin: "císhàn", meaning: "charity/philanthropic", hsk: 6 },
    { hanzi: "基金会", pinyin: "jījīnhuì", meaning: "foundation", hsk: 6 },
    { hanzi: "非营利", pinyin: "fēi yínglì", meaning: "non-profit", hsk: 6 },
    { hanzi: "公益", pinyin: "gōngyì", meaning: "public welfare", hsk: 5 },
    { hanzi: "扶贫", pinyin: "fúpín", meaning: "poverty alleviation", hsk: 6 },
    { hanzi: "脱贫", pinyin: "tuōpín", meaning: "to escape poverty", hsk: 6 },
    { hanzi: "小康", pinyin: "xiǎokāng", meaning: "moderately prosperous", hsk: 6 },
    { hanzi: "发达国家", pinyin: "fādá guójiā", meaning: "developed country", hsk: 5 },
    { hanzi: "发展中国家", pinyin: "fāzhǎn zhōng guójiā", meaning: "developing country", hsk: 5 },
    { hanzi: "新兴市场", pinyin: "xīnxīng shìchǎng", meaning: "emerging market", hsk: 6 },
    { hanzi: "一带一路", pinyin: "yī dài yī lù", meaning: "Belt and Road Initiative", hsk: 6 },
    { hanzi: "亚太地区", pinyin: "yà tài dìqū", meaning: "Asia-Pacific region", hsk: 6 },
    { hanzi: "自贸区", pinyin: "zì mào qū", meaning: "free trade zone", hsk: 6 },
    { hanzi: "经济特区", pinyin: "jīngjì tèqū", meaning: "special economic zone", hsk: 6 },
    { hanzi: "改革开放", pinyin: "gǎigé kāifàng", meaning: "reform and opening up", hsk: 5 },
    { hanzi: "现代化建设", pinyin: "xiàndàihuà jiànshè", meaning: "modernization construction", hsk: 6 },
    { hanzi: "小康社会", pinyin: "xiǎokāng shèhuì", meaning: "well-off society", hsk: 6 },
    { hanzi: "生态文明", pinyin: "shēngtài wénmíng", meaning: "ecological civilization", hsk: 6 },
    { hanzi: "乡村振兴", pinyin: "xiāngcūn zhènxīng", meaning: "rural revitalization", hsk: 6 },
    { hanzi: "智慧城市", pinyin: "zhìhuì chéngshì", meaning: "smart city", hsk: 6 },
    { hanzi: "共享经济", pinyin: "gòngxiǎng jīngjì", meaning: "sharing economy", hsk: 5 },
    { hanzi: "数字经济", pinyin: "shùzì jīngjì", meaning: "digital economy", hsk: 6 },
    { hanzi: "人才培养", pinyin: "réncái péiyǎng", meaning: "talent cultivation", hsk: 5 },
    { hanzi: "创新驱动", pinyin: "chuàngxīn qūdòng", meaning: "innovation-driven", hsk: 6 },
    { hanzi: "高质量发展", pinyin: "gāo zhìliàng fāzhǎn", meaning: "high-quality development", hsk: 6 },
  ];

  for (const w of moreWords) {
    const id = sanitizeId("w", w.hanzi);
    addNode({
      id,
      type: "word",
      hanzi: w.hanzi,
      pinyin: w.pinyin,
      meaning: w.meaning,
      hskLevel: w.hsk,
    });
  }

  // Auto-extract individual characters from all multi-character words
  // that aren't yet in the character set. This dramatically expands our character coverage.
  const existingChars = new Set(
    expanded.filter(n => n.type === "character").map(n => n.hanzi)
  );
  const wordNodes = expanded.filter(n => n.type === "word");

  for (const wn of wordNodes) {
    const chars = [...wn.hanzi];
    for (const ch of chars) {
      if (ch.match(/[\u4e00-\u9fff]/) && !existingChars.has(ch)) {
        const id = sanitizeId("c", ch);
        if (!seenIds.has(id)) {
          existingChars.add(ch);
          addNode({
            id,
            type: "character",
            hanzi: ch,
            pinyin: "",
            meaning: `component of ${wn.hanzi}`,
            hskLevel: wn.hskLevel || 5,
          });
        }
      }
    }
  }

  // Generate additional reading nodes for different levels/topics
  const moreReading = [
    { title: "网上购物", pinyin: "wǎngshàng gòuwù", meaning: "Online shopping passage", level: 3 },
    { title: "手机的影响", pinyin: "shǒujī de yǐngxiǎng", meaning: "Impact of smartphones passage", level: 4 },
    { title: "中国经济发展", pinyin: "zhōngguó jīngjì fāzhǎn", meaning: "China's economic development passage", level: 5 },
    { title: "全球变暖", pinyin: "quánqiú biàn nuǎn", meaning: "Global warming passage", level: 5 },
    { title: "人工智能时代", pinyin: "réngōng zhìnéng shídài", meaning: "Age of AI passage", level: 6 },
    { title: "传统与现代", pinyin: "chuántǒng yǔ xiàndài", meaning: "Tradition and modernity passage", level: 4 },
    { title: "中国教育体系", pinyin: "zhōngguó jiàoyù tǐxì", meaning: "Chinese education system passage", level: 5 },
    { title: "城市交通问题", pinyin: "chéngshì jiāotōng wèntí", meaning: "Urban transportation issues passage", level: 4 },
    { title: "健康生活方式", pinyin: "jiànkāng shēnghuó fāngshì", meaning: "Healthy lifestyle passage", level: 3 },
    { title: "志愿者服务", pinyin: "zhìyuànzhě fúwù", meaning: "Volunteer service passage", level: 4 },
    { title: "中外文化差异", pinyin: "zhōngwài wénhuà chāyì", meaning: "Cross-cultural differences passage", level: 5 },
    { title: "网络安全意识", pinyin: "wǎngluò ānquán yìshí", meaning: "Cybersecurity awareness passage", level: 5 },
    { title: "环保出行", pinyin: "huánbǎo chūxíng", meaning: "Green travel passage", level: 4 },
    { title: "创业故事", pinyin: "chuàngyè gùshi", meaning: "Entrepreneurship story passage", level: 5 },
    { title: "养老问题", pinyin: "yǎnglǎo wèntí", meaning: "Elderly care issues passage", level: 5 },
    { title: "留学经历", pinyin: "liúxué jīnglì", meaning: "Study abroad experience passage", level: 4 },
    { title: "中国茶文化", pinyin: "zhōngguó chá wénhuà", meaning: "Chinese tea culture passage", level: 3 },
    { title: "丝绸之路", pinyin: "sīchóu zhī lù", meaning: "Silk Road passage", level: 5 },
    { title: "汉字的演变", pinyin: "hànzì de yǎnbiàn", meaning: "Evolution of Chinese characters passage", level: 4 },
    { title: "中国美食文化", pinyin: "zhōngguó měishí wénhuà", meaning: "Chinese food culture passage", level: 3 },
    { title: "名人传记", pinyin: "míngrén zhuànjì", meaning: "Celebrity biography passage", level: 5 },
    { title: "校园生活", pinyin: "xiàoyuán shēnghuó", meaning: "Campus life passage", level: 2 },
    { title: "假期旅行", pinyin: "jiàqī lǚxíng", meaning: "Holiday travel passage", level: 3 },
    { title: "家乡介绍", pinyin: "jiāxiāng jièshào", meaning: "Hometown introduction passage", level: 2 },
    { title: "我的梦想", pinyin: "wǒ de mèngxiǎng", meaning: "My dream passage", level: 3 },
  ];

  for (const r of moreReading) {
    addNode({
      id: sanitizeId("rd", r.title),
      type: "reading" as NodeType,
      hanzi: r.title,
      pinyin: r.pinyin,
      meaning: r.meaning,
      hskLevel: r.level,
    });
  }

  // More writing nodes
  const moreWriting = [
    { title: "电影评论", pinyin: "diànyǐng pínglùn", meaning: "Writing: movie review", level: 4 },
    { title: "餐厅评价", pinyin: "cāntīng píngjià", meaning: "Writing: restaurant review", level: 3 },
    { title: "活动策划", pinyin: "huódòng cèhuà", meaning: "Writing: event planning", level: 5 },
    { title: "辩论稿", pinyin: "biànlùn gǎo", meaning: "Writing: debate draft", level: 5 },
    { title: "建议信", pinyin: "jiànyì xìn", meaning: "Writing: suggestion letter", level: 4 },
    { title: "读书笔记", pinyin: "dúshū bǐjì", meaning: "Writing: reading notes", level: 3 },
    { title: "旅行日记", pinyin: "lǚxíng rìjì", meaning: "Writing: travel diary", level: 3 },
    { title: "个人简历", pinyin: "gèrén jiǎnlì", meaning: "Writing: personal resume", level: 5 },
    { title: "商业计划书", pinyin: "shāngyè jìhuà shū", meaning: "Writing: business plan", level: 6 },
    { title: "环保倡议书", pinyin: "huánbǎo chàngyì shū", meaning: "Writing: environmental proposal", level: 5 },
  ];

  for (const w of moreWriting) {
    addNode({
      id: sanitizeId("wr", w.title),
      type: "writing" as NodeType,
      hanzi: w.title,
      pinyin: w.pinyin,
      meaning: w.meaning,
      hskLevel: w.level,
    });
  }

  return expanded;
}
