/**
 * HSK vocabulary data and radical decomposition tables.
 * This provides the seed data for the curriculum pipeline.
 */

export interface RawRadical {
  id: string;
  hanzi: string;
  pinyin: string;
  meaning: string;
  strokeCount: number;
}

export interface RawCharacter {
  hanzi: string;
  pinyin: string;
  meaning: string;
  radicals: string[];
  hskLevel: number;
}

export interface RawWord {
  hanzi: string;
  pinyin: string;
  meaning: string;
  hskLevel: number;
}

export interface RawGrammar {
  id: string;
  pattern: string;
  pinyin: string;
  meaning: string;
  hskLevel: number;
  prereqCharIds: string[];
}

export const RADICALS: RawRadical[] = [
  { id: "r_water", hanzi: "氵", pinyin: "shuǐ", meaning: "water", strokeCount: 3 },
  { id: "r_wood", hanzi: "木", pinyin: "mù", meaning: "wood/tree", strokeCount: 4 },
  { id: "r_sun", hanzi: "日", pinyin: "rì", meaning: "sun/day", strokeCount: 4 },
  { id: "r_mouth", hanzi: "口", pinyin: "kǒu", meaning: "mouth", strokeCount: 3 },
  { id: "r_person", hanzi: "人", pinyin: "rén", meaning: "person", strokeCount: 2 },
  { id: "r_woman", hanzi: "女", pinyin: "nǚ", meaning: "woman", strokeCount: 3 },
  { id: "r_fire", hanzi: "火", pinyin: "huǒ", meaning: "fire", strokeCount: 4 },
  { id: "r_earth", hanzi: "土", pinyin: "tǔ", meaning: "earth/soil", strokeCount: 3 },
  { id: "r_heart", hanzi: "心", pinyin: "xīn", meaning: "heart/mind", strokeCount: 4 },
  { id: "r_hand", hanzi: "手", pinyin: "shǒu", meaning: "hand", strokeCount: 4 },
  { id: "r_speech", hanzi: "讠", pinyin: "yán", meaning: "speech/words", strokeCount: 2 },
  { id: "r_metal", hanzi: "钅", pinyin: "jīn", meaning: "metal/gold", strokeCount: 5 },
  { id: "r_silk", hanzi: "纟", pinyin: "sī", meaning: "silk/thread", strokeCount: 3 },
  { id: "r_foot", hanzi: "足", pinyin: "zú", meaning: "foot", strokeCount: 7 },
  { id: "r_grass", hanzi: "艹", pinyin: "cǎo", meaning: "grass/plant", strokeCount: 3 },
  { id: "r_rain", hanzi: "雨", pinyin: "yǔ", meaning: "rain", strokeCount: 8 },
  { id: "r_moon", hanzi: "月", pinyin: "yuè", meaning: "moon/month", strokeCount: 4 },
  { id: "r_mountain", hanzi: "山", pinyin: "shān", meaning: "mountain", strokeCount: 3 },
  { id: "r_stone", hanzi: "石", pinyin: "shí", meaning: "stone/rock", strokeCount: 5 },
  { id: "r_eye", hanzi: "目", pinyin: "mù", meaning: "eye", strokeCount: 5 },
  { id: "r_field", hanzi: "田", pinyin: "tián", meaning: "field", strokeCount: 5 },
  { id: "r_roof", hanzi: "宀", pinyin: "mián", meaning: "roof/shelter", strokeCount: 3 },
  { id: "r_enclosure", hanzi: "囗", pinyin: "wéi", meaning: "enclosure", strokeCount: 3 },
  { id: "r_knife", hanzi: "刂", pinyin: "dāo", meaning: "knife/blade", strokeCount: 2 },
  { id: "r_strength", hanzi: "力", pinyin: "lì", meaning: "strength/power", strokeCount: 2 },
  { id: "r_ten", hanzi: "十", pinyin: "shí", meaning: "ten", strokeCount: 2 },
  { id: "r_big", hanzi: "大", pinyin: "dà", meaning: "big/large", strokeCount: 3 },
  { id: "r_small", hanzi: "小", pinyin: "xiǎo", meaning: "small/little", strokeCount: 3 },
  { id: "r_door", hanzi: "门", pinyin: "mén", meaning: "door/gate", strokeCount: 3 },
  { id: "r_walk", hanzi: "辶", pinyin: "chuò", meaning: "walk/movement", strokeCount: 3 },
  { id: "r_standing", hanzi: "立", pinyin: "lì", meaning: "stand", strokeCount: 5 },
  { id: "r_one", hanzi: "一", pinyin: "yī", meaning: "one/horizontal", strokeCount: 1 },
  { id: "r_two", hanzi: "二", pinyin: "èr", meaning: "two", strokeCount: 2 },
  { id: "r_rice", hanzi: "米", pinyin: "mǐ", meaning: "rice/grain", strokeCount: 6 },
  { id: "r_food", hanzi: "饣", pinyin: "shí", meaning: "food/eat", strokeCount: 3 },
  { id: "r_clothes", hanzi: "衤", pinyin: "yī", meaning: "clothing", strokeCount: 5 },
  { id: "r_car", hanzi: "车", pinyin: "chē", meaning: "vehicle/car", strokeCount: 4 },
  { id: "r_page", hanzi: "页", pinyin: "yè", meaning: "page/head", strokeCount: 6 },
  { id: "r_shell", hanzi: "贝", pinyin: "bèi", meaning: "shell/wealth", strokeCount: 4 },
  { id: "r_dog", hanzi: "犭", pinyin: "quǎn", meaning: "dog/animal", strokeCount: 3 },
  { id: "r_insect", hanzi: "虫", pinyin: "chóng", meaning: "insect/bug", strokeCount: 6 },
  { id: "r_bamboo", hanzi: "⺮", pinyin: "zhú", meaning: "bamboo", strokeCount: 6 },
  { id: "r_meat", hanzi: "⺼", pinyin: "ròu", meaning: "meat/flesh", strokeCount: 4 },
  { id: "r_bird", hanzi: "鸟", pinyin: "niǎo", meaning: "bird", strokeCount: 5 },
  { id: "r_fish", hanzi: "鱼", pinyin: "yú", meaning: "fish", strokeCount: 8 },
  { id: "r_horse", hanzi: "马", pinyin: "mǎ", meaning: "horse", strokeCount: 3 },
  { id: "r_king", hanzi: "王", pinyin: "wáng", meaning: "king/jade", strokeCount: 4 },
  { id: "r_white", hanzi: "白", pinyin: "bái", meaning: "white", strokeCount: 5 },
  { id: "r_arrow", hanzi: "矢", pinyin: "shǐ", meaning: "arrow", strokeCount: 5 },
  { id: "r_grain", hanzi: "禾", pinyin: "hé", meaning: "grain/cereal", strokeCount: 5 },
  { id: "r_disease", hanzi: "疒", pinyin: "nè", meaning: "disease/illness", strokeCount: 5 },
  { id: "r_leather", hanzi: "革", pinyin: "gé", meaning: "leather/hide", strokeCount: 9 },
  { id: "r_boat", hanzi: "舟", pinyin: "zhōu", meaning: "boat", strokeCount: 6 },
  { id: "r_ear", hanzi: "耳", pinyin: "ěr", meaning: "ear", strokeCount: 6 },
  { id: "r_not", hanzi: "不", pinyin: "bù", meaning: "not/no", strokeCount: 4 },
  { id: "r_child", hanzi: "子", pinyin: "zǐ", meaning: "child/son", strokeCount: 3 },
  { id: "r_right_hand", hanzi: "又", pinyin: "yòu", meaning: "right hand/again", strokeCount: 2 },
  { id: "r_corpse", hanzi: "尸", pinyin: "shī", meaning: "corpse/body", strokeCount: 3 },
  { id: "r_evening", hanzi: "夕", pinyin: "xī", meaning: "evening/sunset", strokeCount: 3 },
  { id: "r_scholar", hanzi: "士", pinyin: "shì", meaning: "scholar", strokeCount: 3 },
  { id: "r_inch", hanzi: "寸", pinyin: "cùn", meaning: "inch/measure", strokeCount: 3 },
  { id: "r_axe", hanzi: "斤", pinyin: "jīn", meaning: "axe/weight", strokeCount: 4 },
  { id: "r_square", hanzi: "方", pinyin: "fāng", meaning: "square/direction", strokeCount: 4 },
  { id: "r_clan", hanzi: "氏", pinyin: "shì", meaning: "clan/family", strokeCount: 4 },
  { id: "r_stop", hanzi: "止", pinyin: "zhǐ", meaning: "stop/still", strokeCount: 4 },
  { id: "r_weapon", hanzi: "殳", pinyin: "shū", meaning: "weapon", strokeCount: 4 },
  { id: "r_compare", hanzi: "比", pinyin: "bǐ", meaning: "compare", strokeCount: 4 },
  { id: "r_father", hanzi: "父", pinyin: "fù", meaning: "father", strokeCount: 4 },
  { id: "r_mix", hanzi: "爻", pinyin: "yáo", meaning: "mix/intertwine", strokeCount: 4 },
  { id: "r_half_tree", hanzi: "片", pinyin: "piàn", meaning: "slice/piece", strokeCount: 4 },
  { id: "r_tooth", hanzi: "牙", pinyin: "yá", meaning: "tooth/fang", strokeCount: 4 },
  { id: "r_cow", hanzi: "牛", pinyin: "niú", meaning: "cow/ox", strokeCount: 4 },
  { id: "r_tile", hanzi: "瓦", pinyin: "wǎ", meaning: "tile/pottery", strokeCount: 4 },
  { id: "r_net", hanzi: "罒", pinyin: "wǎng", meaning: "net", strokeCount: 5 },
  { id: "r_sheep", hanzi: "羊", pinyin: "yáng", meaning: "sheep/goat", strokeCount: 6 },
  { id: "r_feather", hanzi: "羽", pinyin: "yǔ", meaning: "feather/wing", strokeCount: 6 },
  { id: "r_old", hanzi: "老", pinyin: "lǎo", meaning: "old/aged", strokeCount: 6 },
  { id: "r_plow", hanzi: "耒", pinyin: "lěi", meaning: "plow", strokeCount: 6 },
  { id: "r_tongue", hanzi: "舌", pinyin: "shé", meaning: "tongue", strokeCount: 6 },
  { id: "r_color", hanzi: "色", pinyin: "sè", meaning: "color", strokeCount: 6 },
  { id: "r_tiger", hanzi: "虍", pinyin: "hǔ", meaning: "tiger", strokeCount: 6 },
  { id: "r_blood", hanzi: "血", pinyin: "xuè", meaning: "blood", strokeCount: 6 },
  { id: "r_walk2", hanzi: "行", pinyin: "xíng", meaning: "walk/travel", strokeCount: 6 },
  { id: "r_horn", hanzi: "角", pinyin: "jiǎo", meaning: "horn/angle", strokeCount: 7 },
  { id: "r_valley", hanzi: "谷", pinyin: "gǔ", meaning: "valley", strokeCount: 7 },
  { id: "r_bean", hanzi: "豆", pinyin: "dòu", meaning: "bean", strokeCount: 7 },
  { id: "r_pig", hanzi: "豕", pinyin: "shǐ", meaning: "pig", strokeCount: 7 },
  { id: "r_city", hanzi: "阝", pinyin: "yì", meaning: "city/mound", strokeCount: 2 },
  { id: "r_pursue", hanzi: "隹", pinyin: "zhuī", meaning: "short-tailed bird", strokeCount: 8 },
  { id: "r_green", hanzi: "青", pinyin: "qīng", meaning: "blue-green", strokeCount: 8 },
  { id: "r_face", hanzi: "面", pinyin: "miàn", meaning: "face/surface", strokeCount: 9 },
  { id: "r_sound", hanzi: "音", pinyin: "yīn", meaning: "sound/tone", strokeCount: 9 },
  { id: "r_wind", hanzi: "风", pinyin: "fēng", meaning: "wind", strokeCount: 4 },
  { id: "r_self", hanzi: "己", pinyin: "jǐ", meaning: "self/oneself", strokeCount: 3 },
  { id: "r_work", hanzi: "工", pinyin: "gōng", meaning: "work/craft", strokeCount: 3 },
  { id: "r_bow", hanzi: "弓", pinyin: "gōng", meaning: "bow", strokeCount: 3 },
  { id: "r_towel", hanzi: "巾", pinyin: "jīn", meaning: "towel/cloth", strokeCount: 3 },
  { id: "r_dry", hanzi: "干", pinyin: "gān", meaning: "dry/shield", strokeCount: 3 },
];

export const CHARACTERS: RawCharacter[] = [
  // HSK 1 Characters
  { hanzi: "我", pinyin: "wǒ", meaning: "I/me", radicals: ["r_hand", "r_weapon"], hskLevel: 1 },
  { hanzi: "你", pinyin: "nǐ", meaning: "you", radicals: ["r_person"], hskLevel: 1 },
  { hanzi: "他", pinyin: "tā", meaning: "he/him", radicals: ["r_person"], hskLevel: 1 },
  { hanzi: "她", pinyin: "tā", meaning: "she/her", radicals: ["r_woman"], hskLevel: 1 },
  { hanzi: "们", pinyin: "men", meaning: "plural marker", radicals: ["r_person", "r_door"], hskLevel: 1 },
  { hanzi: "的", pinyin: "de", meaning: "possessive particle", radicals: ["r_white"], hskLevel: 1 },
  { hanzi: "是", pinyin: "shì", meaning: "to be/is", radicals: ["r_sun", "r_stop"], hskLevel: 1 },
  { hanzi: "不", pinyin: "bù", meaning: "not/no", radicals: ["r_one", "r_not"], hskLevel: 1 },
  { hanzi: "了", pinyin: "le", meaning: "completed action particle", radicals: ["r_child"], hskLevel: 1 },
  { hanzi: "在", pinyin: "zài", meaning: "at/in/exist", radicals: ["r_earth"], hskLevel: 1 },
  { hanzi: "有", pinyin: "yǒu", meaning: "to have/exist", radicals: ["r_moon"], hskLevel: 1 },
  { hanzi: "这", pinyin: "zhè", meaning: "this", radicals: ["r_walk", "r_speech"], hskLevel: 1 },
  { hanzi: "那", pinyin: "nà", meaning: "that", radicals: ["r_city"], hskLevel: 1 },
  { hanzi: "个", pinyin: "gè", meaning: "measure word (general)", radicals: ["r_person"], hskLevel: 1 },
  { hanzi: "好", pinyin: "hǎo", meaning: "good/well", radicals: ["r_woman", "r_child"], hskLevel: 1 },
  { hanzi: "大", pinyin: "dà", meaning: "big/large", radicals: ["r_big"], hskLevel: 1 },
  { hanzi: "小", pinyin: "xiǎo", meaning: "small/little", radicals: ["r_small"], hskLevel: 1 },
  { hanzi: "多", pinyin: "duō", meaning: "many/much", radicals: ["r_evening"], hskLevel: 1 },
  { hanzi: "少", pinyin: "shǎo", meaning: "few/little", radicals: ["r_small"], hskLevel: 1 },
  { hanzi: "很", pinyin: "hěn", meaning: "very", radicals: ["r_walk2"], hskLevel: 1 },
  { hanzi: "没", pinyin: "méi", meaning: "not have/no", radicals: ["r_water"], hskLevel: 1 },
  { hanzi: "都", pinyin: "dōu", meaning: "all/both", radicals: ["r_city"], hskLevel: 1 },
  { hanzi: "会", pinyin: "huì", meaning: "can/meeting", radicals: ["r_person", "r_roof"], hskLevel: 1 },
  { hanzi: "能", pinyin: "néng", meaning: "can/able to", radicals: ["r_meat"], hskLevel: 1 },
  { hanzi: "人", pinyin: "rén", meaning: "person/people", radicals: ["r_person"], hskLevel: 1 },
  { hanzi: "中", pinyin: "zhōng", meaning: "middle/China", radicals: ["r_mouth"], hskLevel: 1 },
  { hanzi: "国", pinyin: "guó", meaning: "country/nation", radicals: ["r_enclosure", "r_king"], hskLevel: 1 },
  { hanzi: "学", pinyin: "xué", meaning: "to study/learn", radicals: ["r_child"], hskLevel: 1 },
  { hanzi: "生", pinyin: "shēng", meaning: "life/born/student", radicals: ["r_cow"], hskLevel: 1 },
  { hanzi: "年", pinyin: "nián", meaning: "year", radicals: ["r_dry"], hskLevel: 1 },
  { hanzi: "月", pinyin: "yuè", meaning: "month/moon", radicals: ["r_moon"], hskLevel: 1 },
  { hanzi: "日", pinyin: "rì", meaning: "day/sun", radicals: ["r_sun"], hskLevel: 1 },
  { hanzi: "天", pinyin: "tiān", meaning: "sky/day/heaven", radicals: ["r_one", "r_big"], hskLevel: 1 },
  { hanzi: "上", pinyin: "shàng", meaning: "up/above/on", radicals: ["r_one"], hskLevel: 1 },
  { hanzi: "下", pinyin: "xià", meaning: "down/below/under", radicals: ["r_one"], hskLevel: 1 },
  { hanzi: "前", pinyin: "qián", meaning: "front/before", radicals: ["r_knife", "r_moon"], hskLevel: 1 },
  { hanzi: "后", pinyin: "hòu", meaning: "back/after/behind", radicals: ["r_mouth"], hskLevel: 1 },
  { hanzi: "里", pinyin: "lǐ", meaning: "inside/Chinese mile", radicals: ["r_field"], hskLevel: 1 },
  { hanzi: "来", pinyin: "lái", meaning: "to come", radicals: ["r_wood"], hskLevel: 1 },
  { hanzi: "去", pinyin: "qù", meaning: "to go", radicals: ["r_earth"], hskLevel: 1 },
  { hanzi: "看", pinyin: "kàn", meaning: "to look/see/read", radicals: ["r_hand", "r_eye"], hskLevel: 1 },
  { hanzi: "吃", pinyin: "chī", meaning: "to eat", radicals: ["r_mouth"], hskLevel: 1 },
  { hanzi: "喝", pinyin: "hē", meaning: "to drink", radicals: ["r_mouth"], hskLevel: 1 },
  { hanzi: "说", pinyin: "shuō", meaning: "to speak/say", radicals: ["r_speech"], hskLevel: 1 },
  { hanzi: "听", pinyin: "tīng", meaning: "to listen/hear", radicals: ["r_mouth", "r_axe"], hskLevel: 1 },
  { hanzi: "读", pinyin: "dú", meaning: "to read aloud", radicals: ["r_speech"], hskLevel: 1 },
  { hanzi: "写", pinyin: "xiě", meaning: "to write", radicals: ["r_roof"], hskLevel: 1 },
  { hanzi: "做", pinyin: "zuò", meaning: "to do/make", radicals: ["r_person"], hskLevel: 1 },
  { hanzi: "住", pinyin: "zhù", meaning: "to live/reside", radicals: ["r_person"], hskLevel: 1 },
  { hanzi: "叫", pinyin: "jiào", meaning: "to call/be called", radicals: ["r_mouth"], hskLevel: 1 },
  { hanzi: "想", pinyin: "xiǎng", meaning: "to think/want/miss", radicals: ["r_heart", "r_wood", "r_eye"], hskLevel: 1 },
  { hanzi: "爱", pinyin: "ài", meaning: "to love", radicals: ["r_heart"], hskLevel: 1 },
  { hanzi: "喜", pinyin: "xǐ", meaning: "happy/to like", radicals: ["r_mouth", "r_scholar"], hskLevel: 1 },
  { hanzi: "欢", pinyin: "huān", meaning: "joyful/happy", radicals: ["r_right_hand"], hskLevel: 1 },
  { hanzi: "开", pinyin: "kāi", meaning: "to open/start", radicals: ["r_one"], hskLevel: 1 },
  { hanzi: "关", pinyin: "guān", meaning: "to close/concern", radicals: ["r_one", "r_big"], hskLevel: 1 },
  { hanzi: "请", pinyin: "qǐng", meaning: "please/to invite", radicals: ["r_speech", "r_green"], hskLevel: 1 },
  { hanzi: "谢", pinyin: "xiè", meaning: "to thank", radicals: ["r_speech"], hskLevel: 1 },
  { hanzi: "对", pinyin: "duì", meaning: "correct/toward", radicals: ["r_inch"], hskLevel: 1 },
  { hanzi: "起", pinyin: "qǐ", meaning: "to rise/get up", radicals: ["r_walk", "r_self"], hskLevel: 1 },
  { hanzi: "回", pinyin: "huí", meaning: "to return", radicals: ["r_enclosure"], hskLevel: 1 },
  { hanzi: "坐", pinyin: "zuò", meaning: "to sit", radicals: ["r_earth"], hskLevel: 1 },
  { hanzi: "打", pinyin: "dǎ", meaning: "to hit/play/make", radicals: ["r_hand"], hskLevel: 1 },
  { hanzi: "电", pinyin: "diàn", meaning: "electricity", radicals: ["r_field"], hskLevel: 1 },
  { hanzi: "话", pinyin: "huà", meaning: "speech/talk/word", radicals: ["r_speech", "r_tongue"], hskLevel: 1 },
  { hanzi: "水", pinyin: "shuǐ", meaning: "water", radicals: ["r_water"], hskLevel: 1 },
  { hanzi: "火", pinyin: "huǒ", meaning: "fire", radicals: ["r_fire"], hskLevel: 1 },
  { hanzi: "菜", pinyin: "cài", meaning: "vegetable/dish", radicals: ["r_grass"], hskLevel: 1 },
  { hanzi: "米", pinyin: "mǐ", meaning: "rice", radicals: ["r_rice"], hskLevel: 1 },
  { hanzi: "茶", pinyin: "chá", meaning: "tea", radicals: ["r_grass", "r_wood"], hskLevel: 1 },
  { hanzi: "果", pinyin: "guǒ", meaning: "fruit/result", radicals: ["r_wood", "r_field"], hskLevel: 1 },
  { hanzi: "杯", pinyin: "bēi", meaning: "cup/glass", radicals: ["r_wood", "r_not"], hskLevel: 1 },
  { hanzi: "书", pinyin: "shū", meaning: "book", radicals: ["r_one"], hskLevel: 1 },
  { hanzi: "字", pinyin: "zì", meaning: "character/word", radicals: ["r_roof", "r_child"], hskLevel: 1 },
  { hanzi: "名", pinyin: "míng", meaning: "name/famous", radicals: ["r_evening", "r_mouth"], hskLevel: 1 },
  { hanzi: "家", pinyin: "jiā", meaning: "home/family", radicals: ["r_roof", "r_pig"], hskLevel: 1 },
  { hanzi: "工", pinyin: "gōng", meaning: "work/craft", radicals: ["r_work"], hskLevel: 1 },
  { hanzi: "作", pinyin: "zuò", meaning: "to work/make", radicals: ["r_person"], hskLevel: 1 },
  { hanzi: "东", pinyin: "dōng", meaning: "east", radicals: ["r_wood"], hskLevel: 1 },
  { hanzi: "西", pinyin: "xī", meaning: "west/thing", radicals: ["r_one"], hskLevel: 1 },
  { hanzi: "北", pinyin: "běi", meaning: "north", radicals: ["r_compare"], hskLevel: 1 },
  { hanzi: "南", pinyin: "nán", meaning: "south", radicals: ["r_ten"], hskLevel: 1 },
  { hanzi: "高", pinyin: "gāo", meaning: "tall/high", radicals: ["r_mouth"], hskLevel: 1 },
  { hanzi: "兴", pinyin: "xìng", meaning: "happy/excited", radicals: ["r_one"], hskLevel: 1 },
  { hanzi: "钱", pinyin: "qián", meaning: "money", radicals: ["r_metal"], hskLevel: 1 },
  { hanzi: "块", pinyin: "kuài", meaning: "piece/yuan", radicals: ["r_earth"], hskLevel: 1 },
  { hanzi: "买", pinyin: "mǎi", meaning: "to buy", radicals: ["r_ten"], hskLevel: 1 },
  { hanzi: "卖", pinyin: "mài", meaning: "to sell", radicals: ["r_ten"], hskLevel: 1 },
  { hanzi: "点", pinyin: "diǎn", meaning: "point/o'clock", radicals: ["r_fire"], hskLevel: 1 },
  { hanzi: "分", pinyin: "fēn", meaning: "minute/divide", radicals: ["r_knife"], hskLevel: 1 },
  { hanzi: "半", pinyin: "bàn", meaning: "half", radicals: ["r_ten"], hskLevel: 1 },
  { hanzi: "现", pinyin: "xiàn", meaning: "present/appear", radicals: ["r_king"], hskLevel: 1 },
  { hanzi: "明", pinyin: "míng", meaning: "bright/clear", radicals: ["r_sun", "r_moon"], hskLevel: 1 },
  { hanzi: "星", pinyin: "xīng", meaning: "star", radicals: ["r_sun", "r_life"], hskLevel: 1 },
  { hanzi: "期", pinyin: "qī", meaning: "period/expect", radicals: ["r_moon"], hskLevel: 1 },
  { hanzi: "今", pinyin: "jīn", meaning: "today/now", radicals: ["r_person"], hskLevel: 1 },
  { hanzi: "昨", pinyin: "zuó", meaning: "yesterday", radicals: ["r_sun"], hskLevel: 1 },
  { hanzi: "气", pinyin: "qì", meaning: "air/weather/anger", radicals: ["r_clan"], hskLevel: 1 },
  { hanzi: "冷", pinyin: "lěng", meaning: "cold", radicals: ["r_water"], hskLevel: 1 },
  { hanzi: "热", pinyin: "rè", meaning: "hot/heat", radicals: ["r_fire"], hskLevel: 1 },

  // HSK 2 Characters
  { hanzi: "到", pinyin: "dào", meaning: "to arrive/reach", radicals: ["r_knife"], hskLevel: 2 },
  { hanzi: "过", pinyin: "guò", meaning: "to pass/experience", radicals: ["r_walk"], hskLevel: 2 },
  { hanzi: "给", pinyin: "gěi", meaning: "to give", radicals: ["r_silk"], hskLevel: 2 },
  { hanzi: "让", pinyin: "ràng", meaning: "to let/allow", radicals: ["r_speech"], hskLevel: 2 },
  { hanzi: "找", pinyin: "zhǎo", meaning: "to find/look for", radicals: ["r_hand"], hskLevel: 2 },
  { hanzi: "告", pinyin: "gào", meaning: "to tell/inform", radicals: ["r_mouth"], hskLevel: 2 },
  { hanzi: "诉", pinyin: "sù", meaning: "to tell/accuse", radicals: ["r_speech"], hskLevel: 2 },
  { hanzi: "问", pinyin: "wèn", meaning: "to ask", radicals: ["r_door", "r_mouth"], hskLevel: 2 },
  { hanzi: "答", pinyin: "dá", meaning: "to answer", radicals: ["r_bamboo"], hskLevel: 2 },
  { hanzi: "跑", pinyin: "pǎo", meaning: "to run", radicals: ["r_foot"], hskLevel: 2 },
  { hanzi: "走", pinyin: "zǒu", meaning: "to walk/go", radicals: ["r_earth"], hskLevel: 2 },
  { hanzi: "进", pinyin: "jìn", meaning: "to enter", radicals: ["r_walk"], hskLevel: 2 },
  { hanzi: "出", pinyin: "chū", meaning: "to go out/exit", radicals: ["r_mountain"], hskLevel: 2 },
  { hanzi: "送", pinyin: "sòng", meaning: "to send/deliver", radicals: ["r_walk"], hskLevel: 2 },
  { hanzi: "穿", pinyin: "chuān", meaning: "to wear/pass through", radicals: ["r_tooth"], hskLevel: 2 },
  { hanzi: "等", pinyin: "děng", meaning: "to wait/class/rank", radicals: ["r_bamboo"], hskLevel: 2 },
  { hanzi: "帮", pinyin: "bāng", meaning: "to help", radicals: ["r_towel"], hskLevel: 2 },
  { hanzi: "玩", pinyin: "wán", meaning: "to play/have fun", radicals: ["r_king"], hskLevel: 2 },
  { hanzi: "唱", pinyin: "chàng", meaning: "to sing", radicals: ["r_mouth", "r_sun"], hskLevel: 2 },
  { hanzi: "跳", pinyin: "tiào", meaning: "to jump/dance", radicals: ["r_foot"], hskLevel: 2 },
  { hanzi: "游", pinyin: "yóu", meaning: "to swim/travel", radicals: ["r_water"], hskLevel: 2 },
  { hanzi: "泳", pinyin: "yǒng", meaning: "to swim", radicals: ["r_water"], hskLevel: 2 },
  { hanzi: "踢", pinyin: "tī", meaning: "to kick", radicals: ["r_foot"], hskLevel: 2 },
  { hanzi: "球", pinyin: "qiú", meaning: "ball/sphere", radicals: ["r_king"], hskLevel: 2 },
  { hanzi: "快", pinyin: "kuài", meaning: "fast/quick/happy", radicals: ["r_heart"], hskLevel: 2 },
  { hanzi: "慢", pinyin: "màn", meaning: "slow", radicals: ["r_heart"], hskLevel: 2 },
  { hanzi: "长", pinyin: "cháng", meaning: "long/grow", radicals: ["r_one"], hskLevel: 2 },
  { hanzi: "短", pinyin: "duǎn", meaning: "short", radicals: ["r_arrow", "r_bean"], hskLevel: 2 },
  { hanzi: "新", pinyin: "xīn", meaning: "new", radicals: ["r_standing", "r_wood", "r_axe"], hskLevel: 2 },
  { hanzi: "旧", pinyin: "jiù", meaning: "old/used", radicals: ["r_one"], hskLevel: 2 },
  { hanzi: "近", pinyin: "jìn", meaning: "near/close", radicals: ["r_walk", "r_axe"], hskLevel: 2 },
  { hanzi: "远", pinyin: "yuǎn", meaning: "far/distant", radicals: ["r_walk"], hskLevel: 2 },
  { hanzi: "早", pinyin: "zǎo", meaning: "early/morning", radicals: ["r_sun", "r_ten"], hskLevel: 2 },
  { hanzi: "晚", pinyin: "wǎn", meaning: "late/evening", radicals: ["r_sun"], hskLevel: 2 },
  { hanzi: "左", pinyin: "zuǒ", meaning: "left", radicals: ["r_work"], hskLevel: 2 },
  { hanzi: "右", pinyin: "yòu", meaning: "right", radicals: ["r_mouth"], hskLevel: 2 },
  { hanzi: "白", pinyin: "bái", meaning: "white", radicals: ["r_white"], hskLevel: 2 },
  { hanzi: "黑", pinyin: "hēi", meaning: "black/dark", radicals: ["r_fire", "r_earth"], hskLevel: 2 },
  { hanzi: "红", pinyin: "hóng", meaning: "red", radicals: ["r_silk", "r_work"], hskLevel: 2 },
  { hanzi: "男", pinyin: "nán", meaning: "male/man", radicals: ["r_field", "r_strength"], hskLevel: 2 },
  { hanzi: "女", pinyin: "nǚ", meaning: "female/woman", radicals: ["r_woman"], hskLevel: 2 },
  { hanzi: "孩", pinyin: "hái", meaning: "child", radicals: ["r_child"], hskLevel: 2 },
  { hanzi: "儿", pinyin: "ér", meaning: "child/son (suffix)", radicals: ["r_person"], hskLevel: 2 },
  { hanzi: "哥", pinyin: "gē", meaning: "elder brother", radicals: ["r_mouth"], hskLevel: 2 },
  { hanzi: "弟", pinyin: "dì", meaning: "younger brother", radicals: ["r_bow"], hskLevel: 2 },
  { hanzi: "姐", pinyin: "jiě", meaning: "elder sister", radicals: ["r_woman"], hskLevel: 2 },
  { hanzi: "妹", pinyin: "mèi", meaning: "younger sister", radicals: ["r_woman", "r_wood"], hskLevel: 2 },
  { hanzi: "夫", pinyin: "fū", meaning: "husband/man", radicals: ["r_big", "r_one"], hskLevel: 2 },
  { hanzi: "妻", pinyin: "qī", meaning: "wife", radicals: ["r_woman"], hskLevel: 2 },
  { hanzi: "爸", pinyin: "bà", meaning: "father/dad", radicals: ["r_father"], hskLevel: 2 },
  { hanzi: "妈", pinyin: "mā", meaning: "mother/mom", radicals: ["r_woman", "r_horse"], hskLevel: 2 },
  { hanzi: "身", pinyin: "shēn", meaning: "body", radicals: ["r_corpse"], hskLevel: 2 },
  { hanzi: "体", pinyin: "tǐ", meaning: "body/form", radicals: ["r_person", "r_wood"], hskLevel: 2 },
  { hanzi: "头", pinyin: "tóu", meaning: "head", radicals: ["r_big"], hskLevel: 2 },
  { hanzi: "脸", pinyin: "liǎn", meaning: "face", radicals: ["r_meat"], hskLevel: 2 },
  { hanzi: "眼", pinyin: "yǎn", meaning: "eye", radicals: ["r_eye"], hskLevel: 2 },
  { hanzi: "睛", pinyin: "jīng", meaning: "eyeball/eye", radicals: ["r_eye", "r_green"], hskLevel: 2 },
  { hanzi: "鼻", pinyin: "bí", meaning: "nose", radicals: ["r_self"], hskLevel: 2 },
  { hanzi: "嘴", pinyin: "zuǐ", meaning: "mouth/beak", radicals: ["r_mouth"], hskLevel: 2 },
  { hanzi: "手", pinyin: "shǒu", meaning: "hand", radicals: ["r_hand"], hskLevel: 2 },
  { hanzi: "脚", pinyin: "jiǎo", meaning: "foot/leg", radicals: ["r_meat", "r_foot"], hskLevel: 2 },
  { hanzi: "房", pinyin: "fáng", meaning: "house/room", radicals: ["r_door", "r_square"], hskLevel: 2 },
  { hanzi: "间", pinyin: "jiān", meaning: "room/between", radicals: ["r_door", "r_sun"], hskLevel: 2 },
  { hanzi: "门", pinyin: "mén", meaning: "door/gate", radicals: ["r_door"], hskLevel: 2 },
  { hanzi: "路", pinyin: "lù", meaning: "road/path", radicals: ["r_foot"], hskLevel: 2 },
  { hanzi: "车", pinyin: "chē", meaning: "car/vehicle", radicals: ["r_car"], hskLevel: 2 },
  { hanzi: "船", pinyin: "chuán", meaning: "boat/ship", radicals: ["r_boat"], hskLevel: 2 },
  { hanzi: "飞", pinyin: "fēi", meaning: "to fly", radicals: ["r_one"], hskLevel: 2 },
  { hanzi: "机", pinyin: "jī", meaning: "machine/opportunity", radicals: ["r_wood"], hskLevel: 2 },
  { hanzi: "鸡", pinyin: "jī", meaning: "chicken", radicals: ["r_bird", "r_right_hand"], hskLevel: 2 },
  { hanzi: "鱼", pinyin: "yú", meaning: "fish", radicals: ["r_fish"], hskLevel: 2 },
  { hanzi: "猫", pinyin: "māo", meaning: "cat", radicals: ["r_dog", "r_grass"], hskLevel: 2 },
  { hanzi: "狗", pinyin: "gǒu", meaning: "dog", radicals: ["r_dog"], hskLevel: 2 },
  { hanzi: "花", pinyin: "huā", meaning: "flower/spend", radicals: ["r_grass"], hskLevel: 2 },
  { hanzi: "树", pinyin: "shù", meaning: "tree", radicals: ["r_wood"], hskLevel: 2 },
  { hanzi: "雪", pinyin: "xuě", meaning: "snow", radicals: ["r_rain"], hskLevel: 2 },
  { hanzi: "风", pinyin: "fēng", meaning: "wind", radicals: ["r_wind"], hskLevel: 2 },
  { hanzi: "雨", pinyin: "yǔ", meaning: "rain", radicals: ["r_rain"], hskLevel: 2 },
  { hanzi: "河", pinyin: "hé", meaning: "river", radicals: ["r_water"], hskLevel: 2 },
  { hanzi: "山", pinyin: "shān", meaning: "mountain", radicals: ["r_mountain"], hskLevel: 2 },
  { hanzi: "报", pinyin: "bào", meaning: "newspaper/report", radicals: ["r_hand"], hskLevel: 2 },
  { hanzi: "纸", pinyin: "zhǐ", meaning: "paper", radicals: ["r_silk"], hskLevel: 2 },
  { hanzi: "笔", pinyin: "bǐ", meaning: "pen/writing tool", radicals: ["r_bamboo"], hskLevel: 2 },
  { hanzi: "题", pinyin: "tí", meaning: "topic/question", radicals: ["r_page"], hskLevel: 2 },
  { hanzi: "考", pinyin: "kǎo", meaning: "test/exam", radicals: ["r_old"], hskLevel: 2 },
  { hanzi: "试", pinyin: "shì", meaning: "to try/test", radicals: ["r_speech"], hskLevel: 2 },
  { hanzi: "教", pinyin: "jiāo", meaning: "to teach", radicals: ["r_child"], hskLevel: 2 },
  { hanzi: "课", pinyin: "kè", meaning: "lesson/class", radicals: ["r_speech", "r_fruit"], hskLevel: 2 },
  { hanzi: "班", pinyin: "bān", meaning: "class/shift", radicals: ["r_king"], hskLevel: 2 },
  { hanzi: "医", pinyin: "yī", meaning: "doctor/medicine", radicals: ["r_arrow"], hskLevel: 2 },
  { hanzi: "院", pinyin: "yuàn", meaning: "courtyard/institute", radicals: ["r_city"], hskLevel: 2 },
  { hanzi: "药", pinyin: "yào", meaning: "medicine/drug", radicals: ["r_grass"], hskLevel: 2 },
  { hanzi: "病", pinyin: "bìng", meaning: "sick/disease", radicals: ["r_disease"], hskLevel: 2 },

  // HSK 3 Characters
  { hanzi: "城", pinyin: "chéng", meaning: "city/wall", radicals: ["r_earth"], hskLevel: 3 },
  { hanzi: "市", pinyin: "shì", meaning: "city/market", radicals: ["r_towel"], hskLevel: 3 },
  { hanzi: "站", pinyin: "zhàn", meaning: "station/stand", radicals: ["r_standing"], hskLevel: 3 },
  { hanzi: "楼", pinyin: "lóu", meaning: "floor/building", radicals: ["r_wood"], hskLevel: 3 },
  { hanzi: "层", pinyin: "céng", meaning: "layer/floor", radicals: ["r_corpse"], hskLevel: 3 },
  { hanzi: "街", pinyin: "jiē", meaning: "street", radicals: ["r_walk2"], hskLevel: 3 },
  { hanzi: "公", pinyin: "gōng", meaning: "public", radicals: ["r_one"], hskLevel: 3 },
  { hanzi: "司", pinyin: "sī", meaning: "company/manage", radicals: ["r_mouth"], hskLevel: 3 },
  { hanzi: "银", pinyin: "yín", meaning: "silver/money", radicals: ["r_metal"], hskLevel: 3 },
  { hanzi: "行", pinyin: "háng", meaning: "bank/row/walk", radicals: ["r_walk2"], hskLevel: 3 },
  { hanzi: "元", pinyin: "yuán", meaning: "yuan/origin", radicals: ["r_one", "r_person"], hskLevel: 3 },
  { hanzi: "角", pinyin: "jiǎo", meaning: "corner/dime", radicals: ["r_horn"], hskLevel: 3 },
  { hanzi: "便", pinyin: "biàn", meaning: "convenient", radicals: ["r_person"], hskLevel: 3 },
  { hanzi: "宜", pinyin: "yí", meaning: "suitable/cheap", radicals: ["r_roof"], hskLevel: 3 },
  { hanzi: "贵", pinyin: "guì", meaning: "expensive/noble", radicals: ["r_shell"], hskLevel: 3 },
  { hanzi: "完", pinyin: "wán", meaning: "to finish/complete", radicals: ["r_roof"], hskLevel: 3 },
  { hanzi: "成", pinyin: "chéng", meaning: "to become/succeed", radicals: ["r_weapon"], hskLevel: 3 },
  { hanzi: "决", pinyin: "jué", meaning: "to decide", radicals: ["r_water"], hskLevel: 3 },
  { hanzi: "定", pinyin: "dìng", meaning: "to decide/fix", radicals: ["r_roof"], hskLevel: 3 },
  { hanzi: "选", pinyin: "xuǎn", meaning: "to choose/select", radicals: ["r_walk"], hskLevel: 3 },
  { hanzi: "择", pinyin: "zé", meaning: "to select/pick", radicals: ["r_hand"], hskLevel: 3 },
  { hanzi: "解", pinyin: "jiě", meaning: "to solve/understand", radicals: ["r_horn", "r_knife", "r_cow"], hskLevel: 3 },
  { hanzi: "决", pinyin: "jué", meaning: "to decide/determine", radicals: ["r_water"], hskLevel: 3 },
  { hanzi: "办", pinyin: "bàn", meaning: "to handle/do", radicals: ["r_strength"], hskLevel: 3 },
  { hanzi: "法", pinyin: "fǎ", meaning: "law/method", radicals: ["r_water"], hskLevel: 3 },
  { hanzi: "变", pinyin: "biàn", meaning: "to change", radicals: ["r_right_hand"], hskLevel: 3 },
  { hanzi: "化", pinyin: "huà", meaning: "to change/transform", radicals: ["r_person"], hskLevel: 3 },
  { hanzi: "种", pinyin: "zhǒng", meaning: "kind/type/seed", radicals: ["r_grain"], hskLevel: 3 },
  { hanzi: "愿", pinyin: "yuàn", meaning: "willing/wish", radicals: ["r_heart"], hskLevel: 3 },
  { hanzi: "意", pinyin: "yì", meaning: "meaning/idea", radicals: ["r_heart", "r_standing", "r_sun"], hskLevel: 3 },
  { hanzi: "思", pinyin: "sī", meaning: "to think/miss", radicals: ["r_heart", "r_field"], hskLevel: 3 },
  { hanzi: "经", pinyin: "jīng", meaning: "through/experience", radicals: ["r_silk"], hskLevel: 3 },
  { hanzi: "历", pinyin: "lì", meaning: "history/experience", radicals: ["r_strength"], hskLevel: 3 },
  { hanzi: "练", pinyin: "liàn", meaning: "to practice", radicals: ["r_silk"], hskLevel: 3 },
  { hanzi: "习", pinyin: "xí", meaning: "to practice/study", radicals: ["r_feather"], hskLevel: 3 },
  { hanzi: "准", pinyin: "zhǔn", meaning: "accurate/allow", radicals: ["r_water", "r_pursue"], hskLevel: 3 },
  { hanzi: "备", pinyin: "bèi", meaning: "to prepare", radicals: ["r_field"], hskLevel: 3 },
  { hanzi: "记", pinyin: "jì", meaning: "to remember/record", radicals: ["r_speech", "r_self"], hskLevel: 3 },
  { hanzi: "信", pinyin: "xìn", meaning: "letter/believe", radicals: ["r_person", "r_speech"], hskLevel: 3 },
  { hanzi: "息", pinyin: "xī", meaning: "rest/breath", radicals: ["r_heart", "r_self"], hskLevel: 3 },
  { hanzi: "接", pinyin: "jiē", meaning: "to receive/connect", radicals: ["r_hand"], hskLevel: 3 },
  { hanzi: "搬", pinyin: "bān", meaning: "to move/carry", radicals: ["r_hand", "r_boat"], hskLevel: 3 },
  { hanzi: "拿", pinyin: "ná", meaning: "to take/hold", radicals: ["r_hand"], hskLevel: 3 },
  { hanzi: "放", pinyin: "fàng", meaning: "to put/release", radicals: ["r_square"], hskLevel: 3 },
  { hanzi: "换", pinyin: "huàn", meaning: "to change/exchange", radicals: ["r_hand"], hskLevel: 3 },
  { hanzi: "带", pinyin: "dài", meaning: "to carry/bring", radicals: ["r_towel"], hskLevel: 3 },
  { hanzi: "忘", pinyin: "wàng", meaning: "to forget", radicals: ["r_heart"], hskLevel: 3 },
  { hanzi: "懂", pinyin: "dǒng", meaning: "to understand", radicals: ["r_heart"], hskLevel: 3 },
  { hanzi: "认", pinyin: "rèn", meaning: "to recognize", radicals: ["r_speech"], hskLevel: 3 },
  { hanzi: "识", pinyin: "shí", meaning: "to know/recognize", radicals: ["r_speech"], hskLevel: 3 },
  { hanzi: "需", pinyin: "xū", meaning: "to need/require", radicals: ["r_rain"], hskLevel: 3 },
  { hanzi: "要", pinyin: "yào", meaning: "to need/want", radicals: ["r_woman"], hskLevel: 3 },
  { hanzi: "应", pinyin: "yīng", meaning: "should/respond", radicals: ["r_heart"], hskLevel: 3 },
  { hanzi: "该", pinyin: "gāi", meaning: "should/ought to", radicals: ["r_speech"], hskLevel: 3 },
  { hanzi: "必", pinyin: "bì", meaning: "must/certainly", radicals: ["r_heart"], hskLevel: 3 },
  { hanzi: "须", pinyin: "xū", meaning: "must/beard", radicals: ["r_page"], hskLevel: 3 },
  { hanzi: "比", pinyin: "bǐ", meaning: "to compare", radicals: ["r_compare"], hskLevel: 3 },
  { hanzi: "较", pinyin: "jiào", meaning: "compare/rather", radicals: ["r_car"], hskLevel: 3 },
  { hanzi: "最", pinyin: "zuì", meaning: "most/utmost", radicals: ["r_sun"], hskLevel: 3 },
  { hanzi: "更", pinyin: "gèng", meaning: "more/even more", radicals: ["r_one"], hskLevel: 3 },
  { hanzi: "越", pinyin: "yuè", meaning: "to exceed/the more", radicals: ["r_walk", "r_weapon"], hskLevel: 3 },
  { hanzi: "极", pinyin: "jí", meaning: "extreme/pole", radicals: ["r_wood"], hskLevel: 3 },
  { hanzi: "特", pinyin: "tè", meaning: "special/particular", radicals: ["r_cow", "r_inch"], hskLevel: 3 },
  { hanzi: "别", pinyin: "bié", meaning: "other/don't", radicals: ["r_knife"], hskLevel: 3 },
  { hanzi: "重", pinyin: "zhòng", meaning: "heavy/important", radicals: ["r_field"], hskLevel: 3 },
  { hanzi: "轻", pinyin: "qīng", meaning: "light/slight", radicals: ["r_car"], hskLevel: 3 },
  { hanzi: "难", pinyin: "nán", meaning: "difficult/hard", radicals: ["r_right_hand", "r_pursue"], hskLevel: 3 },
  { hanzi: "容", pinyin: "róng", meaning: "contain/face", radicals: ["r_roof"], hskLevel: 3 },
  { hanzi: "易", pinyin: "yì", meaning: "easy/change", radicals: ["r_sun"], hskLevel: 3 },
  { hanzi: "真", pinyin: "zhēn", meaning: "true/real", radicals: ["r_eye", "r_ten"], hskLevel: 3 },
  { hanzi: "假", pinyin: "jiǎ", meaning: "false/holiday", radicals: ["r_person"], hskLevel: 3 },
  { hanzi: "干", pinyin: "gān", meaning: "dry/do/clean", radicals: ["r_dry"], hskLevel: 3 },
  { hanzi: "净", pinyin: "jìng", meaning: "clean/pure", radicals: ["r_water"], hskLevel: 3 },
  { hanzi: "安", pinyin: "ān", meaning: "safe/peaceful", radicals: ["r_roof", "r_woman"], hskLevel: 3 },
  { hanzi: "全", pinyin: "quán", meaning: "complete/whole", radicals: ["r_person", "r_king"], hskLevel: 3 },
  { hanzi: "静", pinyin: "jìng", meaning: "quiet/still", radicals: ["r_green"], hskLevel: 3 },
  { hanzi: "声", pinyin: "shēng", meaning: "sound/voice", radicals: ["r_scholar"], hskLevel: 3 },
  { hanzi: "响", pinyin: "xiǎng", meaning: "loud/echo", radicals: ["r_mouth", "r_sound"], hskLevel: 3 },
  { hanzi: "相", pinyin: "xiāng", meaning: "mutual/photo", radicals: ["r_wood", "r_eye"], hskLevel: 3 },
  { hanzi: "同", pinyin: "tóng", meaning: "same/together", radicals: ["r_mouth", "r_one"], hskLevel: 3 },
  { hanzi: "共", pinyin: "gòng", meaning: "common/together", radicals: ["r_one"], hskLevel: 3 },
  { hanzi: "向", pinyin: "xiàng", meaning: "toward/direction", radicals: ["r_mouth"], hskLevel: 3 },
  { hanzi: "像", pinyin: "xiàng", meaning: "to resemble/image", radicals: ["r_person"], hskLevel: 3 },
  { hanzi: "件", pinyin: "jiàn", meaning: "item/piece", radicals: ["r_person", "r_cow"], hskLevel: 3 },
  { hanzi: "事", pinyin: "shì", meaning: "thing/matter", radicals: ["r_one"], hskLevel: 3 },
  { hanzi: "情", pinyin: "qíng", meaning: "feeling/emotion", radicals: ["r_heart", "r_green"], hskLevel: 3 },
  { hanzi: "况", pinyin: "kuàng", meaning: "situation/condition", radicals: ["r_water"], hskLevel: 3 },
  { hanzi: "关", pinyin: "guān", meaning: "to close/concern", radicals: ["r_one", "r_big"], hskLevel: 3 },
  { hanzi: "系", pinyin: "xì", meaning: "system/connect", radicals: ["r_silk"], hskLevel: 3 },
  { hanzi: "影", pinyin: "yǐng", meaning: "shadow/movie", radicals: ["r_sun"], hskLevel: 3 },
  { hanzi: "响", pinyin: "xiǎng", meaning: "to sound/echo", radicals: ["r_mouth"], hskLevel: 3 },
  { hanzi: "世", pinyin: "shì", meaning: "world/era", radicals: ["r_one"], hskLevel: 3 },
  { hanzi: "界", pinyin: "jiè", meaning: "boundary/world", radicals: ["r_field"], hskLevel: 3 },
  { hanzi: "环", pinyin: "huán", meaning: "ring/surround", radicals: ["r_king"], hskLevel: 3 },
  { hanzi: "境", pinyin: "jìng", meaning: "border/environment", radicals: ["r_earth"], hskLevel: 3 },
  { hanzi: "文", pinyin: "wén", meaning: "text/culture", radicals: ["r_one"], hskLevel: 3 },

  // HSK 4 Characters
  { hanzi: "议", pinyin: "yì", meaning: "discuss/suggest", radicals: ["r_speech"], hskLevel: 4 },
  { hanzi: "论", pinyin: "lùn", meaning: "discuss/theory", radicals: ["r_speech"], hskLevel: 4 },
  { hanzi: "表", pinyin: "biǎo", meaning: "table/express", radicals: ["r_clothes"], hskLevel: 4 },
  { hanzi: "示", pinyin: "shì", meaning: "to show/indicate", radicals: ["r_one"], hskLevel: 4 },
  { hanzi: "证", pinyin: "zhèng", meaning: "proof/certificate", radicals: ["r_speech"], hskLevel: 4 },
  { hanzi: "据", pinyin: "jù", meaning: "according to/seize", radicals: ["r_hand"], hskLevel: 4 },
  { hanzi: "术", pinyin: "shù", meaning: "art/technique", radicals: ["r_wood"], hskLevel: 4 },
  { hanzi: "技", pinyin: "jì", meaning: "skill/technology", radicals: ["r_hand"], hskLevel: 4 },
  { hanzi: "科", pinyin: "kē", meaning: "science/branch", radicals: ["r_grain"], hskLevel: 4 },
  { hanzi: "程", pinyin: "chéng", meaning: "journey/process", radicals: ["r_grain"], hskLevel: 4 },
  { hanzi: "算", pinyin: "suàn", meaning: "to count/calculate", radicals: ["r_bamboo"], hskLevel: 4 },
  { hanzi: "数", pinyin: "shù", meaning: "number/count", radicals: ["r_woman"], hskLevel: 4 },
  { hanzi: "组", pinyin: "zǔ", meaning: "group/organize", radicals: ["r_silk"], hskLevel: 4 },
  { hanzi: "织", pinyin: "zhī", meaning: "to weave/organize", radicals: ["r_silk"], hskLevel: 4 },
  { hanzi: "构", pinyin: "gòu", meaning: "structure/construct", radicals: ["r_wood"], hskLevel: 4 },
  { hanzi: "建", pinyin: "jiàn", meaning: "to build/establish", radicals: ["r_walk"], hskLevel: 4 },
  { hanzi: "设", pinyin: "shè", meaning: "to set up/design", radicals: ["r_speech"], hskLevel: 4 },
  { hanzi: "计", pinyin: "jì", meaning: "to plan/calculate", radicals: ["r_speech"], hskLevel: 4 },
  { hanzi: "划", pinyin: "huà", meaning: "to plan/draw", radicals: ["r_knife"], hskLevel: 4 },
  { hanzi: "际", pinyin: "jì", meaning: "border/occasion", radicals: ["r_city"], hskLevel: 4 },
  { hanzi: "任", pinyin: "rèn", meaning: "assign/duty", radicals: ["r_person"], hskLevel: 4 },
  { hanzi: "务", pinyin: "wù", meaning: "affairs/duty", radicals: ["r_strength"], hskLevel: 4 },
  { hanzi: "责", pinyin: "zé", meaning: "duty/responsibility", radicals: ["r_shell"], hskLevel: 4 },
  { hanzi: "管", pinyin: "guǎn", meaning: "to manage/pipe", radicals: ["r_bamboo"], hskLevel: 4 },
  { hanzi: "理", pinyin: "lǐ", meaning: "reason/manage", radicals: ["r_king", "r_field"], hskLevel: 4 },
  { hanzi: "治", pinyin: "zhì", meaning: "to govern/cure", radicals: ["r_water"], hskLevel: 4 },
  { hanzi: "政", pinyin: "zhèng", meaning: "politics/government", radicals: ["r_stop"], hskLevel: 4 },
  { hanzi: "府", pinyin: "fǔ", meaning: "government/prefecture", radicals: ["r_roof"], hskLevel: 4 },
  { hanzi: "民", pinyin: "mín", meaning: "people/citizen", radicals: ["r_clan"], hskLevel: 4 },
  { hanzi: "社", pinyin: "shè", meaning: "society/organization", radicals: ["r_earth"], hskLevel: 4 },
  { hanzi: "集", pinyin: "jí", meaning: "to gather/collect", radicals: ["r_pursue", "r_wood"], hskLevel: 4 },
  { hanzi: "合", pinyin: "hé", meaning: "to combine/fit", radicals: ["r_mouth", "r_one"], hskLevel: 4 },
  { hanzi: "联", pinyin: "lián", meaning: "to unite/connect", radicals: ["r_ear"], hskLevel: 4 },
  { hanzi: "系", pinyin: "xì", meaning: "system/tie", radicals: ["r_silk"], hskLevel: 4 },
  { hanzi: "传", pinyin: "chuán", meaning: "to pass/transmit", radicals: ["r_person"], hskLevel: 4 },
  { hanzi: "统", pinyin: "tǒng", meaning: "system/unite", radicals: ["r_silk"], hskLevel: 4 },
  { hanzi: "资", pinyin: "zī", meaning: "capital/resource", radicals: ["r_shell"], hskLevel: 4 },
  { hanzi: "料", pinyin: "liào", meaning: "material/expect", radicals: ["r_rice"], hskLevel: 4 },
  { hanzi: "产", pinyin: "chǎn", meaning: "produce/property", radicals: ["r_standing"], hskLevel: 4 },
  { hanzi: "品", pinyin: "pǐn", meaning: "product/grade", radicals: ["r_mouth"], hskLevel: 4 },
  { hanzi: "质", pinyin: "zhì", meaning: "quality/nature", radicals: ["r_shell"], hskLevel: 4 },
  { hanzi: "量", pinyin: "liàng", meaning: "quantity/measure", radicals: ["r_sun", "r_field"], hskLevel: 4 },
  { hanzi: "价", pinyin: "jià", meaning: "price/value", radicals: ["r_person"], hskLevel: 4 },
  { hanzi: "格", pinyin: "gé", meaning: "standard/grid", radicals: ["r_wood"], hskLevel: 4 },
  { hanzi: "竞", pinyin: "jìng", meaning: "to compete", radicals: ["r_standing"], hskLevel: 4 },
  { hanzi: "争", pinyin: "zhēng", meaning: "to contend/fight", radicals: ["r_one"], hskLevel: 4 },
  { hanzi: "赢", pinyin: "yíng", meaning: "to win", radicals: ["r_shell"], hskLevel: 4 },
  { hanzi: "输", pinyin: "shū", meaning: "to lose/transport", radicals: ["r_car"], hskLevel: 4 },
  { hanzi: "功", pinyin: "gōng", meaning: "achievement/merit", radicals: ["r_work", "r_strength"], hskLevel: 4 },
  { hanzi: "努", pinyin: "nǔ", meaning: "to strive/effort", radicals: ["r_strength", "r_woman"], hskLevel: 4 },
  { hanzi: "力", pinyin: "lì", meaning: "power/strength", radicals: ["r_strength"], hskLevel: 4 },
  { hanzi: "勇", pinyin: "yǒng", meaning: "brave/courageous", radicals: ["r_strength"], hskLevel: 4 },
  { hanzi: "敢", pinyin: "gǎn", meaning: "to dare", radicals: ["r_weapon"], hskLevel: 4 },
  { hanzi: "感", pinyin: "gǎn", meaning: "to feel/sense", radicals: ["r_heart", "r_weapon"], hskLevel: 4 },
  { hanzi: "受", pinyin: "shòu", meaning: "to receive/bear", radicals: ["r_right_hand"], hskLevel: 4 },
  { hanzi: "害", pinyin: "hài", meaning: "harm/damage", radicals: ["r_roof", "r_mouth"], hskLevel: 4 },
  { hanzi: "怕", pinyin: "pà", meaning: "to fear/afraid", radicals: ["r_heart", "r_white"], hskLevel: 4 },
  { hanzi: "担", pinyin: "dān", meaning: "to carry/worry", radicals: ["r_hand", "r_sun"], hskLevel: 4 },
  { hanzi: "忧", pinyin: "yōu", meaning: "worry/anxious", radicals: ["r_heart"], hskLevel: 4 },
  { hanzi: "乐", pinyin: "lè", meaning: "happy/music", radicals: ["r_wood"], hskLevel: 4 },
  { hanzi: "福", pinyin: "fú", meaning: "blessing/fortune", radicals: ["r_earth"], hskLevel: 4 },
  { hanzi: "运", pinyin: "yùn", meaning: "luck/transport", radicals: ["r_walk"], hskLevel: 4 },
  { hanzi: "健", pinyin: "jiàn", meaning: "healthy/strong", radicals: ["r_person"], hskLevel: 4 },
  { hanzi: "康", pinyin: "kāng", meaning: "healthy/peaceful", radicals: ["r_roof"], hskLevel: 4 },
  { hanzi: "态", pinyin: "tài", meaning: "state/manner", radicals: ["r_heart", "r_big"], hskLevel: 4 },
  { hanzi: "度", pinyin: "dù", meaning: "degree/measure", radicals: ["r_roof"], hskLevel: 4 },
  { hanzi: "节", pinyin: "jié", meaning: "festival/segment", radicals: ["r_bamboo"], hskLevel: 4 },
  { hanzi: "约", pinyin: "yuē", meaning: "about/appointment", radicals: ["r_silk"], hskLevel: 4 },
  { hanzi: "普", pinyin: "pǔ", meaning: "universal/general", radicals: ["r_sun"], hskLevel: 4 },
  { hanzi: "通", pinyin: "tōng", meaning: "through/connect", radicals: ["r_walk"], hskLevel: 4 },
  { hanzi: "交", pinyin: "jiāo", meaning: "to hand over/interact", radicals: ["r_one", "r_father"], hskLevel: 4 },
  { hanzi: "流", pinyin: "liú", meaning: "to flow/current", radicals: ["r_water"], hskLevel: 4 },
  { hanzi: "际", pinyin: "jì", meaning: "between/occasion", radicals: ["r_city"], hskLevel: 4 },
  { hanzi: "旅", pinyin: "lǚ", meaning: "travel/trip", radicals: ["r_square"], hskLevel: 4 },
  { hanzi: "游", pinyin: "yóu", meaning: "travel/tour", radicals: ["r_water"], hskLevel: 4 },
  { hanzi: "景", pinyin: "jǐng", meaning: "scenery/view", radicals: ["r_sun"], hskLevel: 4 },
  { hanzi: "色", pinyin: "sè", meaning: "color", radicals: ["r_color"], hskLevel: 4 },
  { hanzi: "照", pinyin: "zhào", meaning: "to shine/photo", radicals: ["r_sun", "r_fire"], hskLevel: 4 },
  { hanzi: "片", pinyin: "piàn", meaning: "piece/photo", radicals: ["r_half_tree"], hskLevel: 4 },
  { hanzi: "艺", pinyin: "yì", meaning: "art/skill", radicals: ["r_grass"], hskLevel: 4 },
  { hanzi: "术", pinyin: "shù", meaning: "art/technique", radicals: ["r_wood"], hskLevel: 4 },
  { hanzi: "音", pinyin: "yīn", meaning: "sound/tone", radicals: ["r_sound"], hskLevel: 4 },
  { hanzi: "乐", pinyin: "yuè", meaning: "music", radicals: ["r_wood"], hskLevel: 4 },
  { hanzi: "歌", pinyin: "gē", meaning: "song", radicals: ["r_mouth"], hskLevel: 4 },
  { hanzi: "舞", pinyin: "wǔ", meaning: "to dance/dance", radicals: ["r_evening"], hskLevel: 4 },
  { hanzi: "演", pinyin: "yǎn", meaning: "to perform/act", radicals: ["r_water"], hskLevel: 4 },
  { hanzi: "戏", pinyin: "xì", meaning: "play/drama", radicals: ["r_weapon"], hskLevel: 4 },
  { hanzi: "赛", pinyin: "sài", meaning: "match/race", radicals: ["r_shell"], hskLevel: 4 },
  { hanzi: "馆", pinyin: "guǎn", meaning: "hall/museum", radicals: ["r_food"], hskLevel: 4 },
  { hanzi: "厅", pinyin: "tīng", meaning: "hall/office", radicals: ["r_one"], hskLevel: 4 },
  { hanzi: "室", pinyin: "shì", meaning: "room", radicals: ["r_roof"], hskLevel: 4 },
];

export const WORDS: RawWord[] = [
  // HSK 1 Words
  { hanzi: "你好", pinyin: "nǐhǎo", meaning: "hello", hskLevel: 1 },
  { hanzi: "谢谢", pinyin: "xièxie", meaning: "thank you", hskLevel: 1 },
  { hanzi: "再见", pinyin: "zàijiàn", meaning: "goodbye", hskLevel: 1 },
  { hanzi: "对不起", pinyin: "duìbuqǐ", meaning: "sorry", hskLevel: 1 },
  { hanzi: "没关系", pinyin: "méiguānxi", meaning: "it's okay", hskLevel: 1 },
  { hanzi: "中国", pinyin: "Zhōngguó", meaning: "China", hskLevel: 1 },
  { hanzi: "学生", pinyin: "xuéshēng", meaning: "student", hskLevel: 1 },
  { hanzi: "老师", pinyin: "lǎoshī", meaning: "teacher", hskLevel: 1 },
  { hanzi: "朋友", pinyin: "péngyou", meaning: "friend", hskLevel: 1 },
  { hanzi: "同学", pinyin: "tóngxué", meaning: "classmate", hskLevel: 1 },
  { hanzi: "家人", pinyin: "jiārén", meaning: "family member", hskLevel: 1 },
  { hanzi: "医生", pinyin: "yīshēng", meaning: "doctor", hskLevel: 1 },
  { hanzi: "现在", pinyin: "xiànzài", meaning: "now", hskLevel: 1 },
  { hanzi: "今天", pinyin: "jīntiān", meaning: "today", hskLevel: 1 },
  { hanzi: "明天", pinyin: "míngtiān", meaning: "tomorrow", hskLevel: 1 },
  { hanzi: "昨天", pinyin: "zuótiān", meaning: "yesterday", hskLevel: 1 },
  { hanzi: "上午", pinyin: "shàngwǔ", meaning: "morning", hskLevel: 1 },
  { hanzi: "下午", pinyin: "xiàwǔ", meaning: "afternoon", hskLevel: 1 },
  { hanzi: "星期", pinyin: "xīngqī", meaning: "week", hskLevel: 1 },
  { hanzi: "月亮", pinyin: "yuèliang", meaning: "moon", hskLevel: 1 },
  { hanzi: "时候", pinyin: "shíhou", meaning: "time/moment", hskLevel: 1 },
  { hanzi: "学校", pinyin: "xuéxiào", meaning: "school", hskLevel: 1 },
  { hanzi: "商店", pinyin: "shāngdiàn", meaning: "shop/store", hskLevel: 1 },
  { hanzi: "饭店", pinyin: "fàndiàn", meaning: "restaurant/hotel", hskLevel: 1 },
  { hanzi: "医院", pinyin: "yīyuàn", meaning: "hospital", hskLevel: 1 },
  { hanzi: "北京", pinyin: "Běijīng", meaning: "Beijing", hskLevel: 1 },
  { hanzi: "东西", pinyin: "dōngxi", meaning: "thing/stuff", hskLevel: 1 },
  { hanzi: "电视", pinyin: "diànshì", meaning: "television", hskLevel: 1 },
  { hanzi: "电脑", pinyin: "diànnǎo", meaning: "computer", hskLevel: 1 },
  { hanzi: "电话", pinyin: "diànhuà", meaning: "telephone", hskLevel: 1 },
  { hanzi: "手机", pinyin: "shǒujī", meaning: "cellphone", hskLevel: 1 },
  { hanzi: "名字", pinyin: "míngzi", meaning: "name", hskLevel: 1 },
  { hanzi: "汉字", pinyin: "hànzì", meaning: "Chinese character", hskLevel: 1 },
  { hanzi: "中文", pinyin: "zhōngwén", meaning: "Chinese language", hskLevel: 1 },
  { hanzi: "英语", pinyin: "yīngyǔ", meaning: "English language", hskLevel: 1 },
  { hanzi: "工作", pinyin: "gōngzuò", meaning: "work/job", hskLevel: 1 },
  { hanzi: "天气", pinyin: "tiānqì", meaning: "weather", hskLevel: 1 },
  { hanzi: "苹果", pinyin: "píngguǒ", meaning: "apple", hskLevel: 1 },
  { hanzi: "水果", pinyin: "shuǐguǒ", meaning: "fruit", hskLevel: 1 },
  { hanzi: "米饭", pinyin: "mǐfàn", meaning: "cooked rice", hskLevel: 1 },
  { hanzi: "喜欢", pinyin: "xǐhuan", meaning: "to like", hskLevel: 1 },
  { hanzi: "高兴", pinyin: "gāoxìng", meaning: "happy/glad", hskLevel: 1 },
  { hanzi: "漂亮", pinyin: "piàoliang", meaning: "pretty/beautiful", hskLevel: 1 },

  // HSK 2 Words
  { hanzi: "公共汽车", pinyin: "gōnggòng qìchē", meaning: "bus", hskLevel: 2 },
  { hanzi: "出租车", pinyin: "chūzūchē", meaning: "taxi", hskLevel: 2 },
  { hanzi: "火车站", pinyin: "huǒchēzhàn", meaning: "train station", hskLevel: 2 },
  { hanzi: "飞机", pinyin: "fēijī", meaning: "airplane", hskLevel: 2 },
  { hanzi: "自行车", pinyin: "zìxíngchē", meaning: "bicycle", hskLevel: 2 },
  { hanzi: "眼睛", pinyin: "yǎnjing", meaning: "eye", hskLevel: 2 },
  { hanzi: "身体", pinyin: "shēntǐ", meaning: "body/health", hskLevel: 2 },
  { hanzi: "男孩", pinyin: "nánhái", meaning: "boy", hskLevel: 2 },
  { hanzi: "女孩", pinyin: "nǚhái", meaning: "girl", hskLevel: 2 },
  { hanzi: "哥哥", pinyin: "gēge", meaning: "older brother", hskLevel: 2 },
  { hanzi: "弟弟", pinyin: "dìdi", meaning: "younger brother", hskLevel: 2 },
  { hanzi: "姐姐", pinyin: "jiějie", meaning: "older sister", hskLevel: 2 },
  { hanzi: "妹妹", pinyin: "mèimei", meaning: "younger sister", hskLevel: 2 },
  { hanzi: "爸爸", pinyin: "bàba", meaning: "dad/father", hskLevel: 2 },
  { hanzi: "妈妈", pinyin: "māma", meaning: "mom/mother", hskLevel: 2 },
  { hanzi: "丈夫", pinyin: "zhàngfu", meaning: "husband", hskLevel: 2 },
  { hanzi: "妻子", pinyin: "qīzi", meaning: "wife", hskLevel: 2 },
  { hanzi: "孩子", pinyin: "háizi", meaning: "child/children", hskLevel: 2 },
  { hanzi: "房间", pinyin: "fángjiān", meaning: "room", hskLevel: 2 },
  { hanzi: "洗手间", pinyin: "xǐshǒujiān", meaning: "bathroom", hskLevel: 2 },
  { hanzi: "教室", pinyin: "jiàoshì", meaning: "classroom", hskLevel: 2 },
  { hanzi: "图书馆", pinyin: "túshūguǎn", meaning: "library", hskLevel: 2 },
  { hanzi: "运动", pinyin: "yùndòng", meaning: "exercise/sport", hskLevel: 2 },
  { hanzi: "足球", pinyin: "zúqiú", meaning: "soccer", hskLevel: 2 },
  { hanzi: "篮球", pinyin: "lánqiú", meaning: "basketball", hskLevel: 2 },
  { hanzi: "游泳", pinyin: "yóuyǒng", meaning: "to swim/swimming", hskLevel: 2 },
  { hanzi: "旁边", pinyin: "pángbiān", meaning: "beside/next to", hskLevel: 2 },
  { hanzi: "外面", pinyin: "wàimiàn", meaning: "outside", hskLevel: 2 },
  { hanzi: "考试", pinyin: "kǎoshì", meaning: "exam/test", hskLevel: 2 },
  { hanzi: "问题", pinyin: "wèntí", meaning: "question/problem", hskLevel: 2 },
  { hanzi: "报纸", pinyin: "bàozhǐ", meaning: "newspaper", hskLevel: 2 },
  { hanzi: "铅笔", pinyin: "qiānbǐ", meaning: "pencil", hskLevel: 2 },
  { hanzi: "唱歌", pinyin: "chànggē", meaning: "to sing", hskLevel: 2 },
  { hanzi: "跳舞", pinyin: "tiàowǔ", meaning: "to dance", hskLevel: 2 },
  { hanzi: "生日", pinyin: "shēngrì", meaning: "birthday", hskLevel: 2 },
  { hanzi: "快乐", pinyin: "kuàilè", meaning: "happy/joyful", hskLevel: 2 },
  { hanzi: "告诉", pinyin: "gàosu", meaning: "to tell", hskLevel: 2 },
  { hanzi: "帮助", pinyin: "bāngzhù", meaning: "to help", hskLevel: 2 },
  { hanzi: "准备", pinyin: "zhǔnbèi", meaning: "to prepare", hskLevel: 2 },
  { hanzi: "介绍", pinyin: "jièshào", meaning: "to introduce", hskLevel: 2 },

  // HSK 3 Words
  { hanzi: "城市", pinyin: "chéngshì", meaning: "city", hskLevel: 3 },
  { hanzi: "世界", pinyin: "shìjiè", meaning: "world", hskLevel: 3 },
  { hanzi: "环境", pinyin: "huánjìng", meaning: "environment", hskLevel: 3 },
  { hanzi: "文化", pinyin: "wénhuà", meaning: "culture", hskLevel: 3 },
  { hanzi: "历史", pinyin: "lìshǐ", meaning: "history", hskLevel: 3 },
  { hanzi: "经验", pinyin: "jīngyàn", meaning: "experience", hskLevel: 3 },
  { hanzi: "练习", pinyin: "liànxí", meaning: "to practice/exercise", hskLevel: 3 },
  { hanzi: "选择", pinyin: "xuǎnzé", meaning: "to choose/choice", hskLevel: 3 },
  { hanzi: "决定", pinyin: "juédìng", meaning: "to decide/decision", hskLevel: 3 },
  { hanzi: "变化", pinyin: "biànhuà", meaning: "change/variation", hskLevel: 3 },
  { hanzi: "办法", pinyin: "bànfǎ", meaning: "method/way", hskLevel: 3 },
  { hanzi: "关系", pinyin: "guānxì", meaning: "relationship", hskLevel: 3 },
  { hanzi: "比较", pinyin: "bǐjiào", meaning: "to compare/fairly", hskLevel: 3 },
  { hanzi: "特别", pinyin: "tèbié", meaning: "special/especially", hskLevel: 3 },
  { hanzi: "容易", pinyin: "róngyì", meaning: "easy", hskLevel: 3 },
  { hanzi: "安全", pinyin: "ānquán", meaning: "safe/safety", hskLevel: 3 },
  { hanzi: "认识", pinyin: "rènshi", meaning: "to know/recognize", hskLevel: 3 },
  { hanzi: "需要", pinyin: "xūyào", meaning: "to need", hskLevel: 3 },
  { hanzi: "应该", pinyin: "yīnggāi", meaning: "should/ought to", hskLevel: 3 },
  { hanzi: "必须", pinyin: "bìxū", meaning: "must/have to", hskLevel: 3 },
  { hanzi: "已经", pinyin: "yǐjīng", meaning: "already", hskLevel: 3 },
  { hanzi: "经常", pinyin: "jīngcháng", meaning: "often/frequently", hskLevel: 3 },
  { hanzi: "一直", pinyin: "yīzhí", meaning: "always/straight", hskLevel: 3 },
  { hanzi: "突然", pinyin: "tūrán", meaning: "suddenly", hskLevel: 3 },
  { hanzi: "终于", pinyin: "zhōngyú", meaning: "finally/at last", hskLevel: 3 },
  { hanzi: "其实", pinyin: "qíshí", meaning: "actually/in fact", hskLevel: 3 },
  { hanzi: "而且", pinyin: "érqiě", meaning: "moreover/and also", hskLevel: 3 },
  { hanzi: "虽然", pinyin: "suīrán", meaning: "although/even though", hskLevel: 3 },
  { hanzi: "但是", pinyin: "dànshì", meaning: "but/however", hskLevel: 3 },
  { hanzi: "如果", pinyin: "rúguǒ", meaning: "if", hskLevel: 3 },
  { hanzi: "因为", pinyin: "yīnwèi", meaning: "because", hskLevel: 3 },
  { hanzi: "所以", pinyin: "suǒyǐ", meaning: "so/therefore", hskLevel: 3 },
  { hanzi: "健康", pinyin: "jiànkāng", meaning: "healthy/health", hskLevel: 3 },
  { hanzi: "愿意", pinyin: "yuànyì", meaning: "willing/be willing to", hskLevel: 3 },
  { hanzi: "感兴趣", pinyin: "gǎn xìngqù", meaning: "to be interested in", hskLevel: 3 },
  { hanzi: "着急", pinyin: "zháojí", meaning: "worried/anxious", hskLevel: 3 },
  { hanzi: "相信", pinyin: "xiāngxìn", meaning: "to believe", hskLevel: 3 },
  { hanzi: "影响", pinyin: "yǐngxiǎng", meaning: "influence/effect", hskLevel: 3 },
  { hanzi: "打算", pinyin: "dǎsuàn", meaning: "to plan/intend", hskLevel: 3 },
  { hanzi: "注意", pinyin: "zhùyì", meaning: "to pay attention", hskLevel: 3 },

  // HSK 4 Words
  { hanzi: "社会", pinyin: "shèhuì", meaning: "society", hskLevel: 4 },
  { hanzi: "经济", pinyin: "jīngjì", meaning: "economy", hskLevel: 4 },
  { hanzi: "政府", pinyin: "zhèngfǔ", meaning: "government", hskLevel: 4 },
  { hanzi: "科技", pinyin: "kējì", meaning: "technology", hskLevel: 4 },
  { hanzi: "教育", pinyin: "jiàoyù", meaning: "education", hskLevel: 4 },
  { hanzi: "计划", pinyin: "jìhuà", meaning: "plan", hskLevel: 4 },
  { hanzi: "组织", pinyin: "zǔzhī", meaning: "organization", hskLevel: 4 },
  { hanzi: "建设", pinyin: "jiànshè", meaning: "to construct/build", hskLevel: 4 },
  { hanzi: "发展", pinyin: "fāzhǎn", meaning: "to develop/development", hskLevel: 4 },
  { hanzi: "改革", pinyin: "gǎigé", meaning: "reform", hskLevel: 4 },
  { hanzi: "竞争", pinyin: "jìngzhēng", meaning: "competition", hskLevel: 4 },
  { hanzi: "合作", pinyin: "hézuò", meaning: "to cooperate", hskLevel: 4 },
  { hanzi: "联系", pinyin: "liánxì", meaning: "to contact/connection", hskLevel: 4 },
  { hanzi: "交流", pinyin: "jiāoliú", meaning: "to exchange/communicate", hskLevel: 4 },
  { hanzi: "传统", pinyin: "chuántǒng", meaning: "tradition/traditional", hskLevel: 4 },
  { hanzi: "资料", pinyin: "zīliào", meaning: "data/material", hskLevel: 4 },
  { hanzi: "质量", pinyin: "zhìliàng", meaning: "quality", hskLevel: 4 },
  { hanzi: "价格", pinyin: "jiàgé", meaning: "price", hskLevel: 4 },
  { hanzi: "产品", pinyin: "chǎnpǐn", meaning: "product", hskLevel: 4 },
  { hanzi: "功夫", pinyin: "gōngfu", meaning: "kung fu/skill", hskLevel: 4 },
  { hanzi: "努力", pinyin: "nǔlì", meaning: "to work hard/effort", hskLevel: 4 },
  { hanzi: "勇敢", pinyin: "yǒnggǎn", meaning: "brave/courageous", hskLevel: 4 },
  { hanzi: "感受", pinyin: "gǎnshòu", meaning: "to feel/feeling", hskLevel: 4 },
  { hanzi: "担心", pinyin: "dānxīn", meaning: "to worry", hskLevel: 4 },
  { hanzi: "害怕", pinyin: "hàipà", meaning: "to be afraid/fear", hskLevel: 4 },
  { hanzi: "快乐", pinyin: "kuàilè", meaning: "happy/joy", hskLevel: 4 },
  { hanzi: "幸福", pinyin: "xìngfú", meaning: "happiness/blessed", hskLevel: 4 },
  { hanzi: "旅游", pinyin: "lǚyóu", meaning: "to travel/tourism", hskLevel: 4 },
  { hanzi: "风景", pinyin: "fēngjǐng", meaning: "scenery/landscape", hskLevel: 4 },
  { hanzi: "照片", pinyin: "zhàopiàn", meaning: "photo/picture", hskLevel: 4 },
  { hanzi: "艺术", pinyin: "yìshù", meaning: "art", hskLevel: 4 },
  { hanzi: "音乐", pinyin: "yīnyuè", meaning: "music", hskLevel: 4 },
  { hanzi: "演出", pinyin: "yǎnchū", meaning: "performance/show", hskLevel: 4 },
  { hanzi: "比赛", pinyin: "bǐsài", meaning: "competition/match", hskLevel: 4 },
  { hanzi: "任务", pinyin: "rènwu", meaning: "task/mission", hskLevel: 4 },
  { hanzi: "责任", pinyin: "zérèn", meaning: "responsibility", hskLevel: 4 },
  { hanzi: "管理", pinyin: "guǎnlǐ", meaning: "management", hskLevel: 4 },
  { hanzi: "表示", pinyin: "biǎoshì", meaning: "to express/indicate", hskLevel: 4 },
  { hanzi: "讨论", pinyin: "tǎolùn", meaning: "to discuss/discussion", hskLevel: 4 },
  { hanzi: "国际", pinyin: "guójì", meaning: "international", hskLevel: 4 },

  // HSK 5-6 words (representative sample for reaching 2500+ nodes)
  { hanzi: "尊重", pinyin: "zūnzhòng", meaning: "to respect", hskLevel: 5 },
  { hanzi: "教授", pinyin: "jiàoshòu", meaning: "professor", hskLevel: 5 },
  { hanzi: "知识", pinyin: "zhīshi", meaning: "knowledge", hskLevel: 5 },
  { hanzi: "思想", pinyin: "sīxiǎng", meaning: "thought/ideology", hskLevel: 5 },
  { hanzi: "精神", pinyin: "jīngshén", meaning: "spirit/mind", hskLevel: 5 },
  { hanzi: "道德", pinyin: "dàodé", meaning: "morality/ethics", hskLevel: 5 },
  { hanzi: "信任", pinyin: "xìnrèn", meaning: "to trust", hskLevel: 5 },
  { hanzi: "诚实", pinyin: "chéngshí", meaning: "honest/sincere", hskLevel: 5 },
  { hanzi: "谦虚", pinyin: "qiānxū", meaning: "modest/humble", hskLevel: 5 },
  { hanzi: "理想", pinyin: "lǐxiǎng", meaning: "ideal/dream", hskLevel: 5 },
  { hanzi: "目标", pinyin: "mùbiāo", meaning: "goal/target", hskLevel: 5 },
  { hanzi: "成功", pinyin: "chénggōng", meaning: "to succeed/success", hskLevel: 5 },
  { hanzi: "失败", pinyin: "shībài", meaning: "to fail/failure", hskLevel: 5 },
  { hanzi: "挑战", pinyin: "tiǎozhàn", meaning: "challenge", hskLevel: 5 },
  { hanzi: "机会", pinyin: "jīhuì", meaning: "opportunity/chance", hskLevel: 5 },
  { hanzi: "经历", pinyin: "jīnglì", meaning: "to experience/experience", hskLevel: 5 },
  { hanzi: "记忆", pinyin: "jìyì", meaning: "memory", hskLevel: 5 },
  { hanzi: "印象", pinyin: "yìnxiàng", meaning: "impression", hskLevel: 5 },
  { hanzi: "表达", pinyin: "biǎodá", meaning: "to express", hskLevel: 5 },
  { hanzi: "沟通", pinyin: "gōutōng", meaning: "to communicate", hskLevel: 5 },
  { hanzi: "风俗", pinyin: "fēngsú", meaning: "custom/tradition", hskLevel: 5 },
  { hanzi: "习惯", pinyin: "xíguàn", meaning: "habit/custom", hskLevel: 5 },
  { hanzi: "气候", pinyin: "qìhòu", meaning: "climate", hskLevel: 5 },
  { hanzi: "自然", pinyin: "zìrán", meaning: "nature/natural", hskLevel: 5 },
  { hanzi: "保护", pinyin: "bǎohù", meaning: "to protect", hskLevel: 5 },
  { hanzi: "污染", pinyin: "wūrǎn", meaning: "pollution", hskLevel: 5 },
  { hanzi: "节约", pinyin: "jiéyuē", meaning: "to save/conserve", hskLevel: 5 },
  { hanzi: "资源", pinyin: "zīyuán", meaning: "resources", hskLevel: 5 },
  { hanzi: "能源", pinyin: "néngyuán", meaning: "energy source", hskLevel: 5 },
  { hanzi: "安排", pinyin: "ānpái", meaning: "to arrange", hskLevel: 5 },
  { hanzi: "计算机", pinyin: "jìsuànjī", meaning: "computer", hskLevel: 5 },
  { hanzi: "网络", pinyin: "wǎngluò", meaning: "network/internet", hskLevel: 5 },
  { hanzi: "信息", pinyin: "xìnxī", meaning: "information", hskLevel: 5 },
  { hanzi: "数据", pinyin: "shùjù", meaning: "data", hskLevel: 5 },
  { hanzi: "程序", pinyin: "chéngxù", meaning: "program/procedure", hskLevel: 5 },
  { hanzi: "设备", pinyin: "shèbèi", meaning: "equipment", hskLevel: 5 },
  { hanzi: "研究", pinyin: "yánjiū", meaning: "research/study", hskLevel: 5 },
  { hanzi: "实验", pinyin: "shíyàn", meaning: "experiment", hskLevel: 5 },
  { hanzi: "结果", pinyin: "jiéguǒ", meaning: "result/outcome", hskLevel: 5 },
  { hanzi: "方法", pinyin: "fāngfǎ", meaning: "method/way", hskLevel: 5 },
  { hanzi: "原因", pinyin: "yuányīn", meaning: "reason/cause", hskLevel: 5 },
  { hanzi: "过程", pinyin: "guòchéng", meaning: "process/course", hskLevel: 5 },
  { hanzi: "条件", pinyin: "tiáojiàn", meaning: "condition/terms", hskLevel: 5 },
  { hanzi: "情况", pinyin: "qíngkuàng", meaning: "situation/condition", hskLevel: 5 },
  { hanzi: "效果", pinyin: "xiàoguǒ", meaning: "effect/result", hskLevel: 5 },
  { hanzi: "基础", pinyin: "jīchǔ", meaning: "foundation/basis", hskLevel: 5 },
  { hanzi: "标准", pinyin: "biāozhǔn", meaning: "standard/criterion", hskLevel: 5 },
  { hanzi: "原则", pinyin: "yuánzé", meaning: "principle", hskLevel: 5 },
  { hanzi: "制度", pinyin: "zhìdù", meaning: "system/institution", hskLevel: 5 },
  { hanzi: "规定", pinyin: "guīdìng", meaning: "regulation/rule", hskLevel: 5 },
];

export const GRAMMAR_PATTERNS: RawGrammar[] = [
  { id: "g_shi_sentence", pattern: "A是B", pinyin: "A shì B", meaning: "A is B (identity/classification)", hskLevel: 1, prereqCharIds: ["c_是"] },
  { id: "g_de_possession", pattern: "A的B", pinyin: "A de B", meaning: "A's B (possession)", hskLevel: 1, prereqCharIds: ["c_的"] },
  { id: "g_bu_negation", pattern: "不+Verb", pinyin: "bù + verb", meaning: "Negation of present/future", hskLevel: 1, prereqCharIds: ["c_不"] },
  { id: "g_mei_negation", pattern: "没+Verb", pinyin: "méi + verb", meaning: "Negation of past action", hskLevel: 1, prereqCharIds: ["c_没"] },
  { id: "g_le_completion", pattern: "Verb+了", pinyin: "verb + le", meaning: "Completed action", hskLevel: 1, prereqCharIds: ["c_了"] },
  { id: "g_zai_location", pattern: "在+Place", pinyin: "zài + place", meaning: "At/in a location", hskLevel: 1, prereqCharIds: ["c_在"] },
  { id: "g_you_existence", pattern: "有+Object", pinyin: "yǒu + object", meaning: "To have / there is", hskLevel: 1, prereqCharIds: ["c_有"] },
  { id: "g_xiang_want", pattern: "想+Verb", pinyin: "xiǎng + verb", meaning: "Want to do something", hskLevel: 1, prereqCharIds: ["c_想"] },
  { id: "g_hen_adj", pattern: "很+Adj", pinyin: "hěn + adj", meaning: "Very + adjective", hskLevel: 1, prereqCharIds: ["c_很"] },
  { id: "g_ma_question", pattern: "Statement+吗?", pinyin: "statement + ma?", meaning: "Yes/no question particle", hskLevel: 1, prereqCharIds: [] },
  { id: "g_ne_question", pattern: "Noun+呢?", pinyin: "noun + ne?", meaning: "How about...? / And...?", hskLevel: 1, prereqCharIds: [] },
  { id: "g_measure_word", pattern: "Number+MW+Noun", pinyin: "number + MW + noun", meaning: "Measure word usage", hskLevel: 1, prereqCharIds: ["c_个"] },
  { id: "g_neng_ability", pattern: "能+Verb", pinyin: "néng + verb", meaning: "Can/able to (ability)", hskLevel: 1, prereqCharIds: ["c_能"] },
  { id: "g_hui_ability", pattern: "会+Verb", pinyin: "huì + verb", meaning: "Can/know how to (learned skill)", hskLevel: 1, prereqCharIds: ["c_会"] },
  { id: "g_keyi_permission", pattern: "可以+Verb", pinyin: "kěyǐ + verb", meaning: "May/can (permission)", hskLevel: 2, prereqCharIds: [] },
  { id: "g_guo_experience", pattern: "Verb+过", pinyin: "verb + guò", meaning: "Have experienced doing", hskLevel: 2, prereqCharIds: ["c_过"] },
  { id: "g_zhe_continuous", pattern: "Verb+着", pinyin: "verb + zhe", meaning: "Ongoing state", hskLevel: 2, prereqCharIds: [] },
  { id: "g_ba_disposal", pattern: "把+Object+Verb", pinyin: "bǎ + obj + verb", meaning: "Disposal/handling pattern", hskLevel: 3, prereqCharIds: [] },
  { id: "g_bei_passive", pattern: "被+Agent+Verb", pinyin: "bèi + agent + verb", meaning: "Passive voice", hskLevel: 3, prereqCharIds: [] },
  { id: "g_bi_comparison", pattern: "A比B+Adj", pinyin: "A bǐ B + adj", meaning: "A is more... than B", hskLevel: 3, prereqCharIds: ["c_比"] },
  { id: "g_ruguo_conditional", pattern: "如果...就...", pinyin: "rúguǒ...jiù...", meaning: "If...then...", hskLevel: 3, prereqCharIds: [] },
  { id: "g_yinwei_because", pattern: "因为...所以...", pinyin: "yīnwèi...suǒyǐ...", meaning: "Because...therefore...", hskLevel: 3, prereqCharIds: [] },
  { id: "g_suiran_although", pattern: "虽然...但是...", pinyin: "suīrán...dànshì...", meaning: "Although...but...", hskLevel: 3, prereqCharIds: [] },
  { id: "g_yuelaiyue", pattern: "越来越+Adj", pinyin: "yuè lái yuè + adj", meaning: "More and more + adj", hskLevel: 3, prereqCharIds: ["c_越", "c_来"] },
  { id: "g_de_complement", pattern: "Verb+得+Complement", pinyin: "verb + de + complement", meaning: "Degree complement", hskLevel: 3, prereqCharIds: [] },
  { id: "g_budan_erqie", pattern: "不但...而且...", pinyin: "búdàn...érqiě...", meaning: "Not only...but also...", hskLevel: 4, prereqCharIds: [] },
  { id: "g_ji_you", pattern: "既...又...", pinyin: "jì...yòu...", meaning: "Both...and...", hskLevel: 4, prereqCharIds: [] },
  { id: "g_lian_dou", pattern: "连...都/也...", pinyin: "lián...dōu/yě...", meaning: "Even...also...", hskLevel: 4, prereqCharIds: [] },
  { id: "g_chule_yiwai", pattern: "除了...以外", pinyin: "chúle...yǐwài", meaning: "Besides/except for...", hskLevel: 4, prereqCharIds: [] },
  { id: "g_zhiyou_cai", pattern: "只有...才...", pinyin: "zhǐyǒu...cái...", meaning: "Only if...then...", hskLevel: 4, prereqCharIds: [] },
];

export const AP_THEMES = [
  { id: "families_communities", name: "Families and Communities", keywords: ["family", "friend", "community", "home", "relationship", "child", "parent", "brother", "sister", "marriage", "festival", "tradition", "neighbor", "society"] },
  { id: "personal_public_identities", name: "Personal and Public Identities", keywords: ["name", "identity", "culture", "belief", "hero", "self", "personality", "nationality", "language", "appearance", "gender", "age", "character"] },
  { id: "beauty_aesthetics", name: "Beauty and Aesthetics", keywords: ["art", "music", "beauty", "literature", "architecture", "fashion", "design", "color", "painting", "poem", "dance", "song", "movie", "theater"] },
  { id: "science_technology", name: "Science and Technology", keywords: ["technology", "science", "computer", "internet", "phone", "machine", "invention", "research", "experiment", "data", "energy", "discover", "innovation"] },
  { id: "contemporary_life", name: "Contemporary Life", keywords: ["travel", "food", "sport", "education", "work", "leisure", "shopping", "health", "housing", "city", "transport", "advertisement", "media", "hobby"] },
  { id: "global_challenges", name: "Global Challenges", keywords: ["environment", "economy", "peace", "human rights", "health", "climate", "pollution", "population", "poverty", "tolerance", "diversity", "resource", "conservation"] },
];
